export enum DtmRequestType {
	SEND_PROGRAM = "SEND_PROGRAM",
	GET_AVAILABILITY = "GET_AVAILABILITY",
	SEND_ORDER = "SEND_ORDER",
	GET_TRACKING = "GET_TRACKING",
	UPDATE_STATUS = "UPDATE_STATUS",
	GET_TRAINS = "GET_TRAINS",
	GET_WAGONS = "GET_WAGONS",
	SYNC_DATA = "SYNC_DATA",
}
