export enum OrderStatus {
	DRAFT = "DRAFT",
	SUBMITTED = "SUBMITTED",
	APPROVED = "APPROVED",
	REJECTED = "REJECTED",
	IN_PROGRESS = "IN_PROGRESS",
	PARTIALLY_EXECUTED = "PARTIALLY_EXECUTED",
	COMPLETED = "COMPLETED",
	CANCELLED = "CANCELLED",
	SENT_TO_DTM = "SENT_TO_DTM",
}

export enum ProgramStatus {
	DRAFT = "DRAFT",
	PENDING_APPROVAL = "PENDING_APPROVAL",
	APPROVED = "APPROVED",
	SENT_TO_DTM = "SENT_TO_DTM",
	CONFIRMED = "CONFIRMED",
	IN_PROGRESS = "IN_PROGRESS",
	COMPLETED = "COMPLETED",
	CANCELLED = "CANCELLED",
}

export enum MovementType {
	IMPORT = "IMPORT",
	EXPORT = "EXPORT",
	EMPTY = "EMPTY",
	FULL_TRAIN = "FULL_TRAIN",
}

export enum PickupLocationType {
	SIDING = "SIDING",
	DOMICILE = "DOMICILE",
}

export enum DispatchType {
	PORT_DUE = "PORT_DUE",
	PORT_PAID = "PORT_PAID",
}
