/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ONCF ECommand API
 * ONCF freight order management
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiErrorResponseDto,
  ManagedReferenceDataDto
} from './generated.schemas';

import { customFetch } from '../axios';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const activeReferenceDataControllerFindAll = (
    resource: 'stations' | 'agencies' | 'ports' | 'berths' | 'sidings' | 'vessels' | 'shippingCompanies',
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<ManagedReferenceDataDto[]>(
      {url: `/catalog/active-reference-data/${resource}`, method: 'GET', signal
    },
      options);
    }




export const getActiveReferenceDataControllerFindAllQueryKey = (resource: 'stations' | 'agencies' | 'ports' | 'berths' | 'sidings' | 'vessels' | 'shippingCompanies',) => {
    return [
    `/catalog/active-reference-data/${resource}`
    ] as const;
    }


export const getActiveReferenceDataControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof activeReferenceDataControllerFindAll>>, TError = ApiErrorResponseDto>(resource: 'stations' | 'agencies' | 'ports' | 'berths' | 'sidings' | 'vessels' | 'shippingCompanies', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof activeReferenceDataControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getActiveReferenceDataControllerFindAllQueryKey(resource);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof activeReferenceDataControllerFindAll>>> = ({ signal }) => activeReferenceDataControllerFindAll(resource, requestOptions, signal);





   return  { queryKey, queryFn, enabled: resource !== null && resource !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof activeReferenceDataControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ActiveReferenceDataControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof activeReferenceDataControllerFindAll>>>
export type ActiveReferenceDataControllerFindAllQueryError = ApiErrorResponseDto


export function useActiveReferenceDataControllerFindAll<TData = Awaited<ReturnType<typeof activeReferenceDataControllerFindAll>>, TError = ApiErrorResponseDto>(
 resource: 'stations' | 'agencies' | 'ports' | 'berths' | 'sidings' | 'vessels' | 'shippingCompanies', options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof activeReferenceDataControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof activeReferenceDataControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof activeReferenceDataControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useActiveReferenceDataControllerFindAll<TData = Awaited<ReturnType<typeof activeReferenceDataControllerFindAll>>, TError = ApiErrorResponseDto>(
 resource: 'stations' | 'agencies' | 'ports' | 'berths' | 'sidings' | 'vessels' | 'shippingCompanies', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof activeReferenceDataControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof activeReferenceDataControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof activeReferenceDataControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useActiveReferenceDataControllerFindAll<TData = Awaited<ReturnType<typeof activeReferenceDataControllerFindAll>>, TError = ApiErrorResponseDto>(
 resource: 'stations' | 'agencies' | 'ports' | 'berths' | 'sidings' | 'vessels' | 'shippingCompanies', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof activeReferenceDataControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useActiveReferenceDataControllerFindAll<TData = Awaited<ReturnType<typeof activeReferenceDataControllerFindAll>>, TError = ApiErrorResponseDto>(
 resource: 'stations' | 'agencies' | 'ports' | 'berths' | 'sidings' | 'vessels' | 'shippingCompanies', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof activeReferenceDataControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getActiveReferenceDataControllerFindAllQueryOptions(resource,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






