/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ONCF ECommand API
 * ONCF freight order management
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AccessoryOperationDto,
  ApiErrorResponseDto,
  CreateAccessoryOperationDto,
  CreateGoodDto,
  CreateGoodsTypeDto,
  CreateRejectionReasonDto,
  CreateUnitDto,
  CustomerTypeDto,
  GoodDto,
  GoodsTypeDto,
  RejectionReasonDto,
  UnitDto,
  UpdateAccessoryOperationDto,
  UpdateGoodDto,
  UpdateGoodsTypeDto,
  UpdateRejectionReasonDto,
  UpdateUnitDto
} from './generated.schemas';

import { customFetch } from '../axios';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const catalogControllerFindCustomerTypes = (

 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<CustomerTypeDto[]>(
      {url: `/catalog/customer-types`, method: 'GET', signal
    },
      options);
    }




export const getCatalogControllerFindCustomerTypesQueryKey = () => {
    return [
    `/catalog/customer-types`
    ] as const;
    }


export const getCatalogControllerFindCustomerTypesQueryOptions = <TData = Awaited<ReturnType<typeof catalogControllerFindCustomerTypes>>, TError = ApiErrorResponseDto>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindCustomerTypes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCatalogControllerFindCustomerTypesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof catalogControllerFindCustomerTypes>>> = ({ signal }) => catalogControllerFindCustomerTypes(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindCustomerTypes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CatalogControllerFindCustomerTypesQueryResult = NonNullable<Awaited<ReturnType<typeof catalogControllerFindCustomerTypes>>>
export type CatalogControllerFindCustomerTypesQueryError = ApiErrorResponseDto


export function useCatalogControllerFindCustomerTypes<TData = Awaited<ReturnType<typeof catalogControllerFindCustomerTypes>>, TError = ApiErrorResponseDto>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindCustomerTypes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindCustomerTypes>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindCustomerTypes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindCustomerTypes<TData = Awaited<ReturnType<typeof catalogControllerFindCustomerTypes>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindCustomerTypes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindCustomerTypes>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindCustomerTypes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindCustomerTypes<TData = Awaited<ReturnType<typeof catalogControllerFindCustomerTypes>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindCustomerTypes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCatalogControllerFindCustomerTypes<TData = Awaited<ReturnType<typeof catalogControllerFindCustomerTypes>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindCustomerTypes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCatalogControllerFindCustomerTypesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const catalogControllerFindUnits = (

 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<UnitDto[]>(
      {url: `/catalog/units`, method: 'GET', signal
    },
      options);
    }




export const getCatalogControllerFindUnitsQueryKey = () => {
    return [
    `/catalog/units`
    ] as const;
    }


export const getCatalogControllerFindUnitsQueryOptions = <TData = Awaited<ReturnType<typeof catalogControllerFindUnits>>, TError = ApiErrorResponseDto>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindUnits>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCatalogControllerFindUnitsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof catalogControllerFindUnits>>> = ({ signal }) => catalogControllerFindUnits(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindUnits>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CatalogControllerFindUnitsQueryResult = NonNullable<Awaited<ReturnType<typeof catalogControllerFindUnits>>>
export type CatalogControllerFindUnitsQueryError = ApiErrorResponseDto


export function useCatalogControllerFindUnits<TData = Awaited<ReturnType<typeof catalogControllerFindUnits>>, TError = ApiErrorResponseDto>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindUnits>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindUnits>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindUnits>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindUnits<TData = Awaited<ReturnType<typeof catalogControllerFindUnits>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindUnits>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindUnits>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindUnits>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindUnits<TData = Awaited<ReturnType<typeof catalogControllerFindUnits>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindUnits>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCatalogControllerFindUnits<TData = Awaited<ReturnType<typeof catalogControllerFindUnits>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindUnits>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCatalogControllerFindUnitsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const catalogControllerCreateUnit = (
    createUnitDto: CreateUnitDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<UnitDto>(
      {url: `/catalog/units`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUnitDto, signal
    },
      options);
    }




export const getCatalogControllerCreateUnitMutationOptions = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateUnit>>, TError,{data: CreateUnitDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateUnit>>, TError,{data: CreateUnitDto}, TContext> => {

const mutationKey = ['catalogControllerCreateUnit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catalogControllerCreateUnit>>, {data: CreateUnitDto}> = (props) => {
          const {data} = props ?? {};

          return  catalogControllerCreateUnit(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CatalogControllerCreateUnitMutationResult = NonNullable<Awaited<ReturnType<typeof catalogControllerCreateUnit>>>
    export type CatalogControllerCreateUnitMutationBody = CreateUnitDto
    export type CatalogControllerCreateUnitMutationError = ApiErrorResponseDto

    export const useCatalogControllerCreateUnit = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateUnit>>, TError,{data: CreateUnitDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catalogControllerCreateUnit>>,
        TError,
        {data: CreateUnitDto},
        TContext
      > => {
      return useMutation(getCatalogControllerCreateUnitMutationOptions(options), queryClient);
    }
    export const catalogControllerFindManageUnits = (

 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<UnitDto[]>(
      {url: `/catalog/manage/units`, method: 'GET', signal
    },
      options);
    }




export const getCatalogControllerFindManageUnitsQueryKey = () => {
    return [
    `/catalog/manage/units`
    ] as const;
    }


export const getCatalogControllerFindManageUnitsQueryOptions = <TData = Awaited<ReturnType<typeof catalogControllerFindManageUnits>>, TError = ApiErrorResponseDto>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageUnits>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCatalogControllerFindManageUnitsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof catalogControllerFindManageUnits>>> = ({ signal }) => catalogControllerFindManageUnits(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageUnits>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CatalogControllerFindManageUnitsQueryResult = NonNullable<Awaited<ReturnType<typeof catalogControllerFindManageUnits>>>
export type CatalogControllerFindManageUnitsQueryError = ApiErrorResponseDto


export function useCatalogControllerFindManageUnits<TData = Awaited<ReturnType<typeof catalogControllerFindManageUnits>>, TError = ApiErrorResponseDto>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageUnits>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindManageUnits>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindManageUnits>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindManageUnits<TData = Awaited<ReturnType<typeof catalogControllerFindManageUnits>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageUnits>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindManageUnits>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindManageUnits>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindManageUnits<TData = Awaited<ReturnType<typeof catalogControllerFindManageUnits>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageUnits>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCatalogControllerFindManageUnits<TData = Awaited<ReturnType<typeof catalogControllerFindManageUnits>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageUnits>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCatalogControllerFindManageUnitsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const catalogControllerUpdateUnit = (
    id: string,
    updateUnitDto: UpdateUnitDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<UnitDto>(
      {url: `/catalog/manage/units/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateUnitDto, signal
    },
      options);
    }




export const getCatalogControllerUpdateUnitMutationOptions = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerUpdateUnit>>, TError,{id: string;data: UpdateUnitDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof catalogControllerUpdateUnit>>, TError,{id: string;data: UpdateUnitDto}, TContext> => {

const mutationKey = ['catalogControllerUpdateUnit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catalogControllerUpdateUnit>>, {id: string;data: UpdateUnitDto}> = (props) => {
          const {id,data} = props ?? {};

          return  catalogControllerUpdateUnit(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CatalogControllerUpdateUnitMutationResult = NonNullable<Awaited<ReturnType<typeof catalogControllerUpdateUnit>>>
    export type CatalogControllerUpdateUnitMutationBody = UpdateUnitDto
    export type CatalogControllerUpdateUnitMutationError = ApiErrorResponseDto

    export const useCatalogControllerUpdateUnit = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerUpdateUnit>>, TError,{id: string;data: UpdateUnitDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catalogControllerUpdateUnit>>,
        TError,
        {id: string;data: UpdateUnitDto},
        TContext
      > => {
      return useMutation(getCatalogControllerUpdateUnitMutationOptions(options), queryClient);
    }
    export const catalogControllerFindGoodsTypes = (

 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<GoodsTypeDto[]>(
      {url: `/catalog/goods-types`, method: 'GET', signal
    },
      options);
    }




export const getCatalogControllerFindGoodsTypesQueryKey = () => {
    return [
    `/catalog/goods-types`
    ] as const;
    }


export const getCatalogControllerFindGoodsTypesQueryOptions = <TData = Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>, TError = ApiErrorResponseDto>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCatalogControllerFindGoodsTypesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>> = ({ signal }) => catalogControllerFindGoodsTypes(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CatalogControllerFindGoodsTypesQueryResult = NonNullable<Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>>
export type CatalogControllerFindGoodsTypesQueryError = ApiErrorResponseDto


export function useCatalogControllerFindGoodsTypes<TData = Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>, TError = ApiErrorResponseDto>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindGoodsTypes<TData = Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindGoodsTypes<TData = Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCatalogControllerFindGoodsTypes<TData = Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCatalogControllerFindGoodsTypesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const catalogControllerCreateGoodsType = (
    createGoodsTypeDto: CreateGoodsTypeDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<GoodsTypeDto>(
      {url: `/catalog/goods-types`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createGoodsTypeDto, signal
    },
      options);
    }




export const getCatalogControllerCreateGoodsTypeMutationOptions = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateGoodsType>>, TError,{data: CreateGoodsTypeDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateGoodsType>>, TError,{data: CreateGoodsTypeDto}, TContext> => {

const mutationKey = ['catalogControllerCreateGoodsType'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catalogControllerCreateGoodsType>>, {data: CreateGoodsTypeDto}> = (props) => {
          const {data} = props ?? {};

          return  catalogControllerCreateGoodsType(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CatalogControllerCreateGoodsTypeMutationResult = NonNullable<Awaited<ReturnType<typeof catalogControllerCreateGoodsType>>>
    export type CatalogControllerCreateGoodsTypeMutationBody = CreateGoodsTypeDto
    export type CatalogControllerCreateGoodsTypeMutationError = ApiErrorResponseDto

    export const useCatalogControllerCreateGoodsType = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateGoodsType>>, TError,{data: CreateGoodsTypeDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catalogControllerCreateGoodsType>>,
        TError,
        {data: CreateGoodsTypeDto},
        TContext
      > => {
      return useMutation(getCatalogControllerCreateGoodsTypeMutationOptions(options), queryClient);
    }
    export const catalogControllerFindManageGoodsTypes = (

 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<GoodsTypeDto[]>(
      {url: `/catalog/manage/goods-types`, method: 'GET', signal
    },
      options);
    }




export const getCatalogControllerFindManageGoodsTypesQueryKey = () => {
    return [
    `/catalog/manage/goods-types`
    ] as const;
    }


export const getCatalogControllerFindManageGoodsTypesQueryOptions = <TData = Awaited<ReturnType<typeof catalogControllerFindManageGoodsTypes>>, TError = ApiErrorResponseDto>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageGoodsTypes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCatalogControllerFindManageGoodsTypesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof catalogControllerFindManageGoodsTypes>>> = ({ signal }) => catalogControllerFindManageGoodsTypes(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageGoodsTypes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CatalogControllerFindManageGoodsTypesQueryResult = NonNullable<Awaited<ReturnType<typeof catalogControllerFindManageGoodsTypes>>>
export type CatalogControllerFindManageGoodsTypesQueryError = ApiErrorResponseDto


export function useCatalogControllerFindManageGoodsTypes<TData = Awaited<ReturnType<typeof catalogControllerFindManageGoodsTypes>>, TError = ApiErrorResponseDto>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageGoodsTypes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindManageGoodsTypes>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindManageGoodsTypes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindManageGoodsTypes<TData = Awaited<ReturnType<typeof catalogControllerFindManageGoodsTypes>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageGoodsTypes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindManageGoodsTypes>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindManageGoodsTypes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindManageGoodsTypes<TData = Awaited<ReturnType<typeof catalogControllerFindManageGoodsTypes>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageGoodsTypes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCatalogControllerFindManageGoodsTypes<TData = Awaited<ReturnType<typeof catalogControllerFindManageGoodsTypes>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageGoodsTypes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCatalogControllerFindManageGoodsTypesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const catalogControllerUpdateGoodsType = (
    id: string,
    updateGoodsTypeDto: UpdateGoodsTypeDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<GoodsTypeDto>(
      {url: `/catalog/manage/goods-types/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateGoodsTypeDto, signal
    },
      options);
    }




export const getCatalogControllerUpdateGoodsTypeMutationOptions = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerUpdateGoodsType>>, TError,{id: string;data: UpdateGoodsTypeDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof catalogControllerUpdateGoodsType>>, TError,{id: string;data: UpdateGoodsTypeDto}, TContext> => {

const mutationKey = ['catalogControllerUpdateGoodsType'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catalogControllerUpdateGoodsType>>, {id: string;data: UpdateGoodsTypeDto}> = (props) => {
          const {id,data} = props ?? {};

          return  catalogControllerUpdateGoodsType(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CatalogControllerUpdateGoodsTypeMutationResult = NonNullable<Awaited<ReturnType<typeof catalogControllerUpdateGoodsType>>>
    export type CatalogControllerUpdateGoodsTypeMutationBody = UpdateGoodsTypeDto
    export type CatalogControllerUpdateGoodsTypeMutationError = ApiErrorResponseDto

    export const useCatalogControllerUpdateGoodsType = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerUpdateGoodsType>>, TError,{id: string;data: UpdateGoodsTypeDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catalogControllerUpdateGoodsType>>,
        TError,
        {id: string;data: UpdateGoodsTypeDto},
        TContext
      > => {
      return useMutation(getCatalogControllerUpdateGoodsTypeMutationOptions(options), queryClient);
    }
    export const catalogControllerFindGoods = (

 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<GoodDto[]>(
      {url: `/catalog/goods`, method: 'GET', signal
    },
      options);
    }




export const getCatalogControllerFindGoodsQueryKey = () => {
    return [
    `/catalog/goods`
    ] as const;
    }


export const getCatalogControllerFindGoodsQueryOptions = <TData = Awaited<ReturnType<typeof catalogControllerFindGoods>>, TError = ApiErrorResponseDto>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindGoods>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCatalogControllerFindGoodsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof catalogControllerFindGoods>>> = ({ signal }) => catalogControllerFindGoods(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindGoods>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CatalogControllerFindGoodsQueryResult = NonNullable<Awaited<ReturnType<typeof catalogControllerFindGoods>>>
export type CatalogControllerFindGoodsQueryError = ApiErrorResponseDto


export function useCatalogControllerFindGoods<TData = Awaited<ReturnType<typeof catalogControllerFindGoods>>, TError = ApiErrorResponseDto>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindGoods>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindGoods>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindGoods>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindGoods<TData = Awaited<ReturnType<typeof catalogControllerFindGoods>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindGoods>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindGoods>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindGoods>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindGoods<TData = Awaited<ReturnType<typeof catalogControllerFindGoods>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindGoods>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCatalogControllerFindGoods<TData = Awaited<ReturnType<typeof catalogControllerFindGoods>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindGoods>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCatalogControllerFindGoodsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const catalogControllerCreateGood = (
    createGoodDto: CreateGoodDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<GoodDto>(
      {url: `/catalog/goods`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createGoodDto, signal
    },
      options);
    }




export const getCatalogControllerCreateGoodMutationOptions = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateGood>>, TError,{data: CreateGoodDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateGood>>, TError,{data: CreateGoodDto}, TContext> => {

const mutationKey = ['catalogControllerCreateGood'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catalogControllerCreateGood>>, {data: CreateGoodDto}> = (props) => {
          const {data} = props ?? {};

          return  catalogControllerCreateGood(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CatalogControllerCreateGoodMutationResult = NonNullable<Awaited<ReturnType<typeof catalogControllerCreateGood>>>
    export type CatalogControllerCreateGoodMutationBody = CreateGoodDto
    export type CatalogControllerCreateGoodMutationError = ApiErrorResponseDto

    export const useCatalogControllerCreateGood = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateGood>>, TError,{data: CreateGoodDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catalogControllerCreateGood>>,
        TError,
        {data: CreateGoodDto},
        TContext
      > => {
      return useMutation(getCatalogControllerCreateGoodMutationOptions(options), queryClient);
    }
    export const catalogControllerFindManageGoods = (

 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<GoodDto[]>(
      {url: `/catalog/manage/goods`, method: 'GET', signal
    },
      options);
    }




export const getCatalogControllerFindManageGoodsQueryKey = () => {
    return [
    `/catalog/manage/goods`
    ] as const;
    }


export const getCatalogControllerFindManageGoodsQueryOptions = <TData = Awaited<ReturnType<typeof catalogControllerFindManageGoods>>, TError = ApiErrorResponseDto>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageGoods>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCatalogControllerFindManageGoodsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof catalogControllerFindManageGoods>>> = ({ signal }) => catalogControllerFindManageGoods(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageGoods>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CatalogControllerFindManageGoodsQueryResult = NonNullable<Awaited<ReturnType<typeof catalogControllerFindManageGoods>>>
export type CatalogControllerFindManageGoodsQueryError = ApiErrorResponseDto


export function useCatalogControllerFindManageGoods<TData = Awaited<ReturnType<typeof catalogControllerFindManageGoods>>, TError = ApiErrorResponseDto>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageGoods>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindManageGoods>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindManageGoods>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindManageGoods<TData = Awaited<ReturnType<typeof catalogControllerFindManageGoods>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageGoods>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindManageGoods>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindManageGoods>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindManageGoods<TData = Awaited<ReturnType<typeof catalogControllerFindManageGoods>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageGoods>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCatalogControllerFindManageGoods<TData = Awaited<ReturnType<typeof catalogControllerFindManageGoods>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageGoods>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCatalogControllerFindManageGoodsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const catalogControllerUpdateGood = (
    id: number,
    updateGoodDto: UpdateGoodDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<GoodDto>(
      {url: `/catalog/manage/goods/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateGoodDto, signal
    },
      options);
    }




export const getCatalogControllerUpdateGoodMutationOptions = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerUpdateGood>>, TError,{id: number;data: UpdateGoodDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof catalogControllerUpdateGood>>, TError,{id: number;data: UpdateGoodDto}, TContext> => {

const mutationKey = ['catalogControllerUpdateGood'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catalogControllerUpdateGood>>, {id: number;data: UpdateGoodDto}> = (props) => {
          const {id,data} = props ?? {};

          return  catalogControllerUpdateGood(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CatalogControllerUpdateGoodMutationResult = NonNullable<Awaited<ReturnType<typeof catalogControllerUpdateGood>>>
    export type CatalogControllerUpdateGoodMutationBody = UpdateGoodDto
    export type CatalogControllerUpdateGoodMutationError = ApiErrorResponseDto

    export const useCatalogControllerUpdateGood = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerUpdateGood>>, TError,{id: number;data: UpdateGoodDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catalogControllerUpdateGood>>,
        TError,
        {id: number;data: UpdateGoodDto},
        TContext
      > => {
      return useMutation(getCatalogControllerUpdateGoodMutationOptions(options), queryClient);
    }
    export const catalogControllerFindAccessoryOperations = (

 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<AccessoryOperationDto[]>(
      {url: `/catalog/accessory-operations`, method: 'GET', signal
    },
      options);
    }




export const getCatalogControllerFindAccessoryOperationsQueryKey = () => {
    return [
    `/catalog/accessory-operations`
    ] as const;
    }


export const getCatalogControllerFindAccessoryOperationsQueryOptions = <TData = Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>, TError = ApiErrorResponseDto>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCatalogControllerFindAccessoryOperationsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>> = ({ signal }) => catalogControllerFindAccessoryOperations(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CatalogControllerFindAccessoryOperationsQueryResult = NonNullable<Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>>
export type CatalogControllerFindAccessoryOperationsQueryError = ApiErrorResponseDto


export function useCatalogControllerFindAccessoryOperations<TData = Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>, TError = ApiErrorResponseDto>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindAccessoryOperations<TData = Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindAccessoryOperations<TData = Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCatalogControllerFindAccessoryOperations<TData = Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCatalogControllerFindAccessoryOperationsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const catalogControllerCreateAccessoryOperation = (
    createAccessoryOperationDto: CreateAccessoryOperationDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<AccessoryOperationDto>(
      {url: `/catalog/accessory-operations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createAccessoryOperationDto, signal
    },
      options);
    }




export const getCatalogControllerCreateAccessoryOperationMutationOptions = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateAccessoryOperation>>, TError,{data: CreateAccessoryOperationDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateAccessoryOperation>>, TError,{data: CreateAccessoryOperationDto}, TContext> => {

const mutationKey = ['catalogControllerCreateAccessoryOperation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catalogControllerCreateAccessoryOperation>>, {data: CreateAccessoryOperationDto}> = (props) => {
          const {data} = props ?? {};

          return  catalogControllerCreateAccessoryOperation(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CatalogControllerCreateAccessoryOperationMutationResult = NonNullable<Awaited<ReturnType<typeof catalogControllerCreateAccessoryOperation>>>
    export type CatalogControllerCreateAccessoryOperationMutationBody = CreateAccessoryOperationDto
    export type CatalogControllerCreateAccessoryOperationMutationError = ApiErrorResponseDto

    export const useCatalogControllerCreateAccessoryOperation = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateAccessoryOperation>>, TError,{data: CreateAccessoryOperationDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catalogControllerCreateAccessoryOperation>>,
        TError,
        {data: CreateAccessoryOperationDto},
        TContext
      > => {
      return useMutation(getCatalogControllerCreateAccessoryOperationMutationOptions(options), queryClient);
    }
    export const catalogControllerFindManageAccessoryOperations = (

 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<AccessoryOperationDto[]>(
      {url: `/catalog/manage/accessory-operations`, method: 'GET', signal
    },
      options);
    }




export const getCatalogControllerFindManageAccessoryOperationsQueryKey = () => {
    return [
    `/catalog/manage/accessory-operations`
    ] as const;
    }


export const getCatalogControllerFindManageAccessoryOperationsQueryOptions = <TData = Awaited<ReturnType<typeof catalogControllerFindManageAccessoryOperations>>, TError = ApiErrorResponseDto>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageAccessoryOperations>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCatalogControllerFindManageAccessoryOperationsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof catalogControllerFindManageAccessoryOperations>>> = ({ signal }) => catalogControllerFindManageAccessoryOperations(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageAccessoryOperations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CatalogControllerFindManageAccessoryOperationsQueryResult = NonNullable<Awaited<ReturnType<typeof catalogControllerFindManageAccessoryOperations>>>
export type CatalogControllerFindManageAccessoryOperationsQueryError = ApiErrorResponseDto


export function useCatalogControllerFindManageAccessoryOperations<TData = Awaited<ReturnType<typeof catalogControllerFindManageAccessoryOperations>>, TError = ApiErrorResponseDto>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageAccessoryOperations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindManageAccessoryOperations>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindManageAccessoryOperations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindManageAccessoryOperations<TData = Awaited<ReturnType<typeof catalogControllerFindManageAccessoryOperations>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageAccessoryOperations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindManageAccessoryOperations>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindManageAccessoryOperations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindManageAccessoryOperations<TData = Awaited<ReturnType<typeof catalogControllerFindManageAccessoryOperations>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageAccessoryOperations>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCatalogControllerFindManageAccessoryOperations<TData = Awaited<ReturnType<typeof catalogControllerFindManageAccessoryOperations>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageAccessoryOperations>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCatalogControllerFindManageAccessoryOperationsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const catalogControllerUpdateAccessoryOperation = (
    id: string,
    updateAccessoryOperationDto: UpdateAccessoryOperationDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<AccessoryOperationDto>(
      {url: `/catalog/manage/accessory-operations/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateAccessoryOperationDto, signal
    },
      options);
    }




export const getCatalogControllerUpdateAccessoryOperationMutationOptions = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerUpdateAccessoryOperation>>, TError,{id: string;data: UpdateAccessoryOperationDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof catalogControllerUpdateAccessoryOperation>>, TError,{id: string;data: UpdateAccessoryOperationDto}, TContext> => {

const mutationKey = ['catalogControllerUpdateAccessoryOperation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catalogControllerUpdateAccessoryOperation>>, {id: string;data: UpdateAccessoryOperationDto}> = (props) => {
          const {id,data} = props ?? {};

          return  catalogControllerUpdateAccessoryOperation(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CatalogControllerUpdateAccessoryOperationMutationResult = NonNullable<Awaited<ReturnType<typeof catalogControllerUpdateAccessoryOperation>>>
    export type CatalogControllerUpdateAccessoryOperationMutationBody = UpdateAccessoryOperationDto
    export type CatalogControllerUpdateAccessoryOperationMutationError = ApiErrorResponseDto

    export const useCatalogControllerUpdateAccessoryOperation = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerUpdateAccessoryOperation>>, TError,{id: string;data: UpdateAccessoryOperationDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catalogControllerUpdateAccessoryOperation>>,
        TError,
        {id: string;data: UpdateAccessoryOperationDto},
        TContext
      > => {
      return useMutation(getCatalogControllerUpdateAccessoryOperationMutationOptions(options), queryClient);
    }
    export const catalogControllerFindRejectionReasons = (

 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<RejectionReasonDto[]>(
      {url: `/catalog/rejection-reasons`, method: 'GET', signal
    },
      options);
    }




export const getCatalogControllerFindRejectionReasonsQueryKey = () => {
    return [
    `/catalog/rejection-reasons`
    ] as const;
    }


export const getCatalogControllerFindRejectionReasonsQueryOptions = <TData = Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>, TError = ApiErrorResponseDto>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCatalogControllerFindRejectionReasonsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>> = ({ signal }) => catalogControllerFindRejectionReasons(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CatalogControllerFindRejectionReasonsQueryResult = NonNullable<Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>>
export type CatalogControllerFindRejectionReasonsQueryError = ApiErrorResponseDto


export function useCatalogControllerFindRejectionReasons<TData = Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>, TError = ApiErrorResponseDto>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindRejectionReasons<TData = Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindRejectionReasons<TData = Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCatalogControllerFindRejectionReasons<TData = Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCatalogControllerFindRejectionReasonsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const catalogControllerCreateRejectionReason = (
    createRejectionReasonDto: CreateRejectionReasonDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<RejectionReasonDto>(
      {url: `/catalog/rejection-reasons`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createRejectionReasonDto, signal
    },
      options);
    }




export const getCatalogControllerCreateRejectionReasonMutationOptions = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateRejectionReason>>, TError,{data: CreateRejectionReasonDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateRejectionReason>>, TError,{data: CreateRejectionReasonDto}, TContext> => {

const mutationKey = ['catalogControllerCreateRejectionReason'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catalogControllerCreateRejectionReason>>, {data: CreateRejectionReasonDto}> = (props) => {
          const {data} = props ?? {};

          return  catalogControllerCreateRejectionReason(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CatalogControllerCreateRejectionReasonMutationResult = NonNullable<Awaited<ReturnType<typeof catalogControllerCreateRejectionReason>>>
    export type CatalogControllerCreateRejectionReasonMutationBody = CreateRejectionReasonDto
    export type CatalogControllerCreateRejectionReasonMutationError = ApiErrorResponseDto

    export const useCatalogControllerCreateRejectionReason = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateRejectionReason>>, TError,{data: CreateRejectionReasonDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catalogControllerCreateRejectionReason>>,
        TError,
        {data: CreateRejectionReasonDto},
        TContext
      > => {
      return useMutation(getCatalogControllerCreateRejectionReasonMutationOptions(options), queryClient);
    }
    export const catalogControllerFindManageRejectionReasons = (

 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<RejectionReasonDto[]>(
      {url: `/catalog/manage/rejection-reasons`, method: 'GET', signal
    },
      options);
    }




export const getCatalogControllerFindManageRejectionReasonsQueryKey = () => {
    return [
    `/catalog/manage/rejection-reasons`
    ] as const;
    }


export const getCatalogControllerFindManageRejectionReasonsQueryOptions = <TData = Awaited<ReturnType<typeof catalogControllerFindManageRejectionReasons>>, TError = ApiErrorResponseDto>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageRejectionReasons>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCatalogControllerFindManageRejectionReasonsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof catalogControllerFindManageRejectionReasons>>> = ({ signal }) => catalogControllerFindManageRejectionReasons(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageRejectionReasons>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CatalogControllerFindManageRejectionReasonsQueryResult = NonNullable<Awaited<ReturnType<typeof catalogControllerFindManageRejectionReasons>>>
export type CatalogControllerFindManageRejectionReasonsQueryError = ApiErrorResponseDto


export function useCatalogControllerFindManageRejectionReasons<TData = Awaited<ReturnType<typeof catalogControllerFindManageRejectionReasons>>, TError = ApiErrorResponseDto>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageRejectionReasons>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindManageRejectionReasons>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindManageRejectionReasons>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindManageRejectionReasons<TData = Awaited<ReturnType<typeof catalogControllerFindManageRejectionReasons>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageRejectionReasons>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindManageRejectionReasons>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindManageRejectionReasons>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindManageRejectionReasons<TData = Awaited<ReturnType<typeof catalogControllerFindManageRejectionReasons>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageRejectionReasons>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCatalogControllerFindManageRejectionReasons<TData = Awaited<ReturnType<typeof catalogControllerFindManageRejectionReasons>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindManageRejectionReasons>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCatalogControllerFindManageRejectionReasonsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const catalogControllerUpdateRejectionReason = (
    id: string,
    updateRejectionReasonDto: UpdateRejectionReasonDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<RejectionReasonDto>(
      {url: `/catalog/manage/rejection-reasons/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateRejectionReasonDto, signal
    },
      options);
    }




export const getCatalogControllerUpdateRejectionReasonMutationOptions = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerUpdateRejectionReason>>, TError,{id: string;data: UpdateRejectionReasonDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof catalogControllerUpdateRejectionReason>>, TError,{id: string;data: UpdateRejectionReasonDto}, TContext> => {

const mutationKey = ['catalogControllerUpdateRejectionReason'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catalogControllerUpdateRejectionReason>>, {id: string;data: UpdateRejectionReasonDto}> = (props) => {
          const {id,data} = props ?? {};

          return  catalogControllerUpdateRejectionReason(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CatalogControllerUpdateRejectionReasonMutationResult = NonNullable<Awaited<ReturnType<typeof catalogControllerUpdateRejectionReason>>>
    export type CatalogControllerUpdateRejectionReasonMutationBody = UpdateRejectionReasonDto
    export type CatalogControllerUpdateRejectionReasonMutationError = ApiErrorResponseDto

    export const useCatalogControllerUpdateRejectionReason = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerUpdateRejectionReason>>, TError,{id: string;data: UpdateRejectionReasonDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catalogControllerUpdateRejectionReason>>,
        TError,
        {id: string;data: UpdateRejectionReasonDto},
        TContext
      > => {
      return useMutation(getCatalogControllerUpdateRejectionReasonMutationOptions(options), queryClient);
    }
