/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ONCF Ecommand API
 * ONCF freight order management
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AccessoryOperationDto,
  CreateAccessoryOperationDto,
  CreateGoodDto,
  CreateGoodsTypeDto,
  CreateRejectionReasonDto,
  CreateUnitDto,
  GoodDto,
  GoodsTypeDto,
  RejectionReasonDto,
  UnitDto
} from './generated.schemas';

import { customFetch } from '../axios';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const catalogControllerFindUnits = (

 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<UnitDto[]>(
      {url: `/catalog/units`, method: 'GET', signal
    },
      options);
    }




export const getCatalogControllerFindUnitsQueryKey = () => {
    return [
    `/catalog/units`
    ] as const;
    }


export const getCatalogControllerFindUnitsQueryOptions = <TData = Awaited<ReturnType<typeof catalogControllerFindUnits>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindUnits>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCatalogControllerFindUnitsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof catalogControllerFindUnits>>> = ({ signal }) => catalogControllerFindUnits(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindUnits>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CatalogControllerFindUnitsQueryResult = NonNullable<Awaited<ReturnType<typeof catalogControllerFindUnits>>>
export type CatalogControllerFindUnitsQueryError = void


export function useCatalogControllerFindUnits<TData = Awaited<ReturnType<typeof catalogControllerFindUnits>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindUnits>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindUnits>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindUnits>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindUnits<TData = Awaited<ReturnType<typeof catalogControllerFindUnits>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindUnits>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindUnits>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindUnits>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindUnits<TData = Awaited<ReturnType<typeof catalogControllerFindUnits>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindUnits>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCatalogControllerFindUnits<TData = Awaited<ReturnType<typeof catalogControllerFindUnits>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindUnits>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCatalogControllerFindUnitsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const catalogControllerCreateUnit = (
    createUnitDto: CreateUnitDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<UnitDto>(
      {url: `/catalog/units`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUnitDto, signal
    },
      options);
    }




export const getCatalogControllerCreateUnitMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateUnit>>, TError,{data: CreateUnitDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateUnit>>, TError,{data: CreateUnitDto}, TContext> => {

const mutationKey = ['catalogControllerCreateUnit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catalogControllerCreateUnit>>, {data: CreateUnitDto}> = (props) => {
          const {data} = props ?? {};

          return  catalogControllerCreateUnit(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CatalogControllerCreateUnitMutationResult = NonNullable<Awaited<ReturnType<typeof catalogControllerCreateUnit>>>
    export type CatalogControllerCreateUnitMutationBody = CreateUnitDto
    export type CatalogControllerCreateUnitMutationError = void

    export const useCatalogControllerCreateUnit = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateUnit>>, TError,{data: CreateUnitDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catalogControllerCreateUnit>>,
        TError,
        {data: CreateUnitDto},
        TContext
      > => {
      return useMutation(getCatalogControllerCreateUnitMutationOptions(options), queryClient);
    }
    export const catalogControllerFindGoodsTypes = (

 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<GoodsTypeDto[]>(
      {url: `/catalog/goods-types`, method: 'GET', signal
    },
      options);
    }




export const getCatalogControllerFindGoodsTypesQueryKey = () => {
    return [
    `/catalog/goods-types`
    ] as const;
    }


export const getCatalogControllerFindGoodsTypesQueryOptions = <TData = Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCatalogControllerFindGoodsTypesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>> = ({ signal }) => catalogControllerFindGoodsTypes(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CatalogControllerFindGoodsTypesQueryResult = NonNullable<Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>>
export type CatalogControllerFindGoodsTypesQueryError = void


export function useCatalogControllerFindGoodsTypes<TData = Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindGoodsTypes<TData = Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindGoodsTypes<TData = Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCatalogControllerFindGoodsTypes<TData = Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindGoodsTypes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCatalogControllerFindGoodsTypesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const catalogControllerCreateGoodsType = (
    createGoodsTypeDto: CreateGoodsTypeDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<GoodsTypeDto>(
      {url: `/catalog/goods-types`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createGoodsTypeDto, signal
    },
      options);
    }




export const getCatalogControllerCreateGoodsTypeMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateGoodsType>>, TError,{data: CreateGoodsTypeDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateGoodsType>>, TError,{data: CreateGoodsTypeDto}, TContext> => {

const mutationKey = ['catalogControllerCreateGoodsType'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catalogControllerCreateGoodsType>>, {data: CreateGoodsTypeDto}> = (props) => {
          const {data} = props ?? {};

          return  catalogControllerCreateGoodsType(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CatalogControllerCreateGoodsTypeMutationResult = NonNullable<Awaited<ReturnType<typeof catalogControllerCreateGoodsType>>>
    export type CatalogControllerCreateGoodsTypeMutationBody = CreateGoodsTypeDto
    export type CatalogControllerCreateGoodsTypeMutationError = void

    export const useCatalogControllerCreateGoodsType = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateGoodsType>>, TError,{data: CreateGoodsTypeDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catalogControllerCreateGoodsType>>,
        TError,
        {data: CreateGoodsTypeDto},
        TContext
      > => {
      return useMutation(getCatalogControllerCreateGoodsTypeMutationOptions(options), queryClient);
    }
    export const catalogControllerFindGoods = (

 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<GoodDto[]>(
      {url: `/catalog/goods`, method: 'GET', signal
    },
      options);
    }




export const getCatalogControllerFindGoodsQueryKey = () => {
    return [
    `/catalog/goods`
    ] as const;
    }


export const getCatalogControllerFindGoodsQueryOptions = <TData = Awaited<ReturnType<typeof catalogControllerFindGoods>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindGoods>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCatalogControllerFindGoodsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof catalogControllerFindGoods>>> = ({ signal }) => catalogControllerFindGoods(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindGoods>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CatalogControllerFindGoodsQueryResult = NonNullable<Awaited<ReturnType<typeof catalogControllerFindGoods>>>
export type CatalogControllerFindGoodsQueryError = void


export function useCatalogControllerFindGoods<TData = Awaited<ReturnType<typeof catalogControllerFindGoods>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindGoods>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindGoods>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindGoods>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindGoods<TData = Awaited<ReturnType<typeof catalogControllerFindGoods>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindGoods>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindGoods>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindGoods>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindGoods<TData = Awaited<ReturnType<typeof catalogControllerFindGoods>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindGoods>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCatalogControllerFindGoods<TData = Awaited<ReturnType<typeof catalogControllerFindGoods>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindGoods>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCatalogControllerFindGoodsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const catalogControllerCreateGood = (
    createGoodDto: CreateGoodDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<GoodDto>(
      {url: `/catalog/goods`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createGoodDto, signal
    },
      options);
    }




export const getCatalogControllerCreateGoodMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateGood>>, TError,{data: CreateGoodDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateGood>>, TError,{data: CreateGoodDto}, TContext> => {

const mutationKey = ['catalogControllerCreateGood'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catalogControllerCreateGood>>, {data: CreateGoodDto}> = (props) => {
          const {data} = props ?? {};

          return  catalogControllerCreateGood(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CatalogControllerCreateGoodMutationResult = NonNullable<Awaited<ReturnType<typeof catalogControllerCreateGood>>>
    export type CatalogControllerCreateGoodMutationBody = CreateGoodDto
    export type CatalogControllerCreateGoodMutationError = void

    export const useCatalogControllerCreateGood = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateGood>>, TError,{data: CreateGoodDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catalogControllerCreateGood>>,
        TError,
        {data: CreateGoodDto},
        TContext
      > => {
      return useMutation(getCatalogControllerCreateGoodMutationOptions(options), queryClient);
    }
    export const catalogControllerFindAccessoryOperations = (

 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<AccessoryOperationDto[]>(
      {url: `/catalog/accessory-operations`, method: 'GET', signal
    },
      options);
    }




export const getCatalogControllerFindAccessoryOperationsQueryKey = () => {
    return [
    `/catalog/accessory-operations`
    ] as const;
    }


export const getCatalogControllerFindAccessoryOperationsQueryOptions = <TData = Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCatalogControllerFindAccessoryOperationsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>> = ({ signal }) => catalogControllerFindAccessoryOperations(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CatalogControllerFindAccessoryOperationsQueryResult = NonNullable<Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>>
export type CatalogControllerFindAccessoryOperationsQueryError = void


export function useCatalogControllerFindAccessoryOperations<TData = Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindAccessoryOperations<TData = Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindAccessoryOperations<TData = Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCatalogControllerFindAccessoryOperations<TData = Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindAccessoryOperations>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCatalogControllerFindAccessoryOperationsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const catalogControllerCreateAccessoryOperation = (
    createAccessoryOperationDto: CreateAccessoryOperationDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<AccessoryOperationDto>(
      {url: `/catalog/accessory-operations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createAccessoryOperationDto, signal
    },
      options);
    }




export const getCatalogControllerCreateAccessoryOperationMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateAccessoryOperation>>, TError,{data: CreateAccessoryOperationDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateAccessoryOperation>>, TError,{data: CreateAccessoryOperationDto}, TContext> => {

const mutationKey = ['catalogControllerCreateAccessoryOperation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catalogControllerCreateAccessoryOperation>>, {data: CreateAccessoryOperationDto}> = (props) => {
          const {data} = props ?? {};

          return  catalogControllerCreateAccessoryOperation(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CatalogControllerCreateAccessoryOperationMutationResult = NonNullable<Awaited<ReturnType<typeof catalogControllerCreateAccessoryOperation>>>
    export type CatalogControllerCreateAccessoryOperationMutationBody = CreateAccessoryOperationDto
    export type CatalogControllerCreateAccessoryOperationMutationError = void

    export const useCatalogControllerCreateAccessoryOperation = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateAccessoryOperation>>, TError,{data: CreateAccessoryOperationDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catalogControllerCreateAccessoryOperation>>,
        TError,
        {data: CreateAccessoryOperationDto},
        TContext
      > => {
      return useMutation(getCatalogControllerCreateAccessoryOperationMutationOptions(options), queryClient);
    }
    export const catalogControllerFindRejectionReasons = (

 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<RejectionReasonDto[]>(
      {url: `/catalog/rejection-reasons`, method: 'GET', signal
    },
      options);
    }




export const getCatalogControllerFindRejectionReasonsQueryKey = () => {
    return [
    `/catalog/rejection-reasons`
    ] as const;
    }


export const getCatalogControllerFindRejectionReasonsQueryOptions = <TData = Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCatalogControllerFindRejectionReasonsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>> = ({ signal }) => catalogControllerFindRejectionReasons(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CatalogControllerFindRejectionReasonsQueryResult = NonNullable<Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>>
export type CatalogControllerFindRejectionReasonsQueryError = void


export function useCatalogControllerFindRejectionReasons<TData = Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindRejectionReasons<TData = Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>,
          TError,
          Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogControllerFindRejectionReasons<TData = Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCatalogControllerFindRejectionReasons<TData = Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogControllerFindRejectionReasons>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCatalogControllerFindRejectionReasonsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const catalogControllerCreateRejectionReason = (
    createRejectionReasonDto: CreateRejectionReasonDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<RejectionReasonDto>(
      {url: `/catalog/rejection-reasons`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createRejectionReasonDto, signal
    },
      options);
    }




export const getCatalogControllerCreateRejectionReasonMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateRejectionReason>>, TError,{data: CreateRejectionReasonDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateRejectionReason>>, TError,{data: CreateRejectionReasonDto}, TContext> => {

const mutationKey = ['catalogControllerCreateRejectionReason'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catalogControllerCreateRejectionReason>>, {data: CreateRejectionReasonDto}> = (props) => {
          const {data} = props ?? {};

          return  catalogControllerCreateRejectionReason(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CatalogControllerCreateRejectionReasonMutationResult = NonNullable<Awaited<ReturnType<typeof catalogControllerCreateRejectionReason>>>
    export type CatalogControllerCreateRejectionReasonMutationBody = CreateRejectionReasonDto
    export type CatalogControllerCreateRejectionReasonMutationError = void

    export const useCatalogControllerCreateRejectionReason = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogControllerCreateRejectionReason>>, TError,{data: CreateRejectionReasonDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catalogControllerCreateRejectionReason>>,
        TError,
        {data: CreateRejectionReasonDto},
        TContext
      > => {
      return useMutation(getCatalogControllerCreateRejectionReasonMutationOptions(options), queryClient);
    }
