/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ONCF Ecommand API
 * ONCF freight order management
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ClaimCommentDto,
  ClaimDeleteDto,
  ClaimDetailDto,
  ClaimListDto,
  ClaimsControllerFindAllParams,
  CreateClaimCommentDto,
  CreateClaimDto,
  RejectClaimDto,
  ResolveClaimDto,
  UpdateClaimDto
} from './generated.schemas';

import { customFetch } from '../axios';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const claimsControllerCreate = (
    createClaimDto: CreateClaimDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<ClaimDetailDto>(
      {url: `/claims`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createClaimDto, signal
    },
      options);
    }




export const getClaimsControllerCreateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimsControllerCreate>>, TError,{data: CreateClaimDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof claimsControllerCreate>>, TError,{data: CreateClaimDto}, TContext> => {

const mutationKey = ['claimsControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof claimsControllerCreate>>, {data: CreateClaimDto}> = (props) => {
          const {data} = props ?? {};

          return  claimsControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClaimsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof claimsControllerCreate>>>
    export type ClaimsControllerCreateMutationBody = CreateClaimDto
    export type ClaimsControllerCreateMutationError = void

    export const useClaimsControllerCreate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimsControllerCreate>>, TError,{data: CreateClaimDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof claimsControllerCreate>>,
        TError,
        {data: CreateClaimDto},
        TContext
      > => {
      return useMutation(getClaimsControllerCreateMutationOptions(options), queryClient);
    }
    export const claimsControllerFindAll = (
    params: ClaimsControllerFindAllParams,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<ClaimListDto[]>(
      {url: `/claims`, method: 'GET',
        params, signal
    },
      options);
    }




export const getClaimsControllerFindAllQueryKey = (params?: ClaimsControllerFindAllParams,) => {
    return [
    `/claims`, ...(params ? [params] : [])
    ] as const;
    }


export const getClaimsControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof claimsControllerFindAll>>, TError = void>(params: ClaimsControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof claimsControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getClaimsControllerFindAllQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof claimsControllerFindAll>>> = ({ signal }) => claimsControllerFindAll(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof claimsControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ClaimsControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof claimsControllerFindAll>>>
export type ClaimsControllerFindAllQueryError = void


export function useClaimsControllerFindAll<TData = Awaited<ReturnType<typeof claimsControllerFindAll>>, TError = void>(
 params: ClaimsControllerFindAllParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof claimsControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof claimsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof claimsControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useClaimsControllerFindAll<TData = Awaited<ReturnType<typeof claimsControllerFindAll>>, TError = void>(
 params: ClaimsControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof claimsControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof claimsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof claimsControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useClaimsControllerFindAll<TData = Awaited<ReturnType<typeof claimsControllerFindAll>>, TError = void>(
 params: ClaimsControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof claimsControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useClaimsControllerFindAll<TData = Awaited<ReturnType<typeof claimsControllerFindAll>>, TError = void>(
 params: ClaimsControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof claimsControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getClaimsControllerFindAllQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const claimsControllerFindOne = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<ClaimDetailDto>(
      {url: `/claims/${id}`, method: 'GET', signal
    },
      options);
    }




export const getClaimsControllerFindOneQueryKey = (id: number,) => {
    return [
    `/claims/${id}`
    ] as const;
    }


export const getClaimsControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof claimsControllerFindOne>>, TError = void>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof claimsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getClaimsControllerFindOneQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof claimsControllerFindOne>>> = ({ signal }) => claimsControllerFindOne(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof claimsControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ClaimsControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof claimsControllerFindOne>>>
export type ClaimsControllerFindOneQueryError = void


export function useClaimsControllerFindOne<TData = Awaited<ReturnType<typeof claimsControllerFindOne>>, TError = void>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof claimsControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof claimsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof claimsControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useClaimsControllerFindOne<TData = Awaited<ReturnType<typeof claimsControllerFindOne>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof claimsControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof claimsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof claimsControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useClaimsControllerFindOne<TData = Awaited<ReturnType<typeof claimsControllerFindOne>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof claimsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useClaimsControllerFindOne<TData = Awaited<ReturnType<typeof claimsControllerFindOne>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof claimsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getClaimsControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const claimsControllerUpdate = (
    id: number,
    updateClaimDto: UpdateClaimDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<ClaimDetailDto>(
      {url: `/claims/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateClaimDto, signal
    },
      options);
    }




export const getClaimsControllerUpdateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimsControllerUpdate>>, TError,{id: number;data: UpdateClaimDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof claimsControllerUpdate>>, TError,{id: number;data: UpdateClaimDto}, TContext> => {

const mutationKey = ['claimsControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof claimsControllerUpdate>>, {id: number;data: UpdateClaimDto}> = (props) => {
          const {id,data} = props ?? {};

          return  claimsControllerUpdate(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClaimsControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof claimsControllerUpdate>>>
    export type ClaimsControllerUpdateMutationBody = UpdateClaimDto
    export type ClaimsControllerUpdateMutationError = void

    export const useClaimsControllerUpdate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimsControllerUpdate>>, TError,{id: number;data: UpdateClaimDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof claimsControllerUpdate>>,
        TError,
        {id: number;data: UpdateClaimDto},
        TContext
      > => {
      return useMutation(getClaimsControllerUpdateMutationOptions(options), queryClient);
    }
    export const claimsControllerRemove = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<ClaimDeleteDto>(
      {url: `/claims/${id}`, method: 'DELETE', signal
    },
      options);
    }




export const getClaimsControllerRemoveMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimsControllerRemove>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof claimsControllerRemove>>, TError,{id: number}, TContext> => {

const mutationKey = ['claimsControllerRemove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof claimsControllerRemove>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  claimsControllerRemove(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClaimsControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof claimsControllerRemove>>>

    export type ClaimsControllerRemoveMutationError = void

    export const useClaimsControllerRemove = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimsControllerRemove>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof claimsControllerRemove>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getClaimsControllerRemoveMutationOptions(options), queryClient);
    }
    export const claimsControllerAddComment = (
    id: number,
    createClaimCommentDto: CreateClaimCommentDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<ClaimCommentDto | void>(
      {url: `/claims/${id}/comments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createClaimCommentDto, signal
    },
      options);
    }




export const getClaimsControllerAddCommentMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimsControllerAddComment>>, TError,{id: number;data: CreateClaimCommentDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof claimsControllerAddComment>>, TError,{id: number;data: CreateClaimCommentDto}, TContext> => {

const mutationKey = ['claimsControllerAddComment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof claimsControllerAddComment>>, {id: number;data: CreateClaimCommentDto}> = (props) => {
          const {id,data} = props ?? {};

          return  claimsControllerAddComment(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClaimsControllerAddCommentMutationResult = NonNullable<Awaited<ReturnType<typeof claimsControllerAddComment>>>
    export type ClaimsControllerAddCommentMutationBody = CreateClaimCommentDto
    export type ClaimsControllerAddCommentMutationError = void

    export const useClaimsControllerAddComment = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimsControllerAddComment>>, TError,{id: number;data: CreateClaimCommentDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof claimsControllerAddComment>>,
        TError,
        {id: number;data: CreateClaimCommentDto},
        TContext
      > => {
      return useMutation(getClaimsControllerAddCommentMutationOptions(options), queryClient);
    }
    export const claimsControllerGetComments = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<ClaimCommentDto[]>(
      {url: `/claims/${id}/comments`, method: 'GET', signal
    },
      options);
    }




export const getClaimsControllerGetCommentsQueryKey = (id: number,) => {
    return [
    `/claims/${id}/comments`
    ] as const;
    }


export const getClaimsControllerGetCommentsQueryOptions = <TData = Awaited<ReturnType<typeof claimsControllerGetComments>>, TError = void>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof claimsControllerGetComments>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getClaimsControllerGetCommentsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof claimsControllerGetComments>>> = ({ signal }) => claimsControllerGetComments(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof claimsControllerGetComments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ClaimsControllerGetCommentsQueryResult = NonNullable<Awaited<ReturnType<typeof claimsControllerGetComments>>>
export type ClaimsControllerGetCommentsQueryError = void


export function useClaimsControllerGetComments<TData = Awaited<ReturnType<typeof claimsControllerGetComments>>, TError = void>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof claimsControllerGetComments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof claimsControllerGetComments>>,
          TError,
          Awaited<ReturnType<typeof claimsControllerGetComments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useClaimsControllerGetComments<TData = Awaited<ReturnType<typeof claimsControllerGetComments>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof claimsControllerGetComments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof claimsControllerGetComments>>,
          TError,
          Awaited<ReturnType<typeof claimsControllerGetComments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useClaimsControllerGetComments<TData = Awaited<ReturnType<typeof claimsControllerGetComments>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof claimsControllerGetComments>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useClaimsControllerGetComments<TData = Awaited<ReturnType<typeof claimsControllerGetComments>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof claimsControllerGetComments>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getClaimsControllerGetCommentsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const claimsControllerStartProgress = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<ClaimDetailDto>(
      {url: `/claims/${id}/start-progress`, method: 'POST', signal
    },
      options);
    }




export const getClaimsControllerStartProgressMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimsControllerStartProgress>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof claimsControllerStartProgress>>, TError,{id: number}, TContext> => {

const mutationKey = ['claimsControllerStartProgress'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof claimsControllerStartProgress>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  claimsControllerStartProgress(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClaimsControllerStartProgressMutationResult = NonNullable<Awaited<ReturnType<typeof claimsControllerStartProgress>>>

    export type ClaimsControllerStartProgressMutationError = void

    export const useClaimsControllerStartProgress = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimsControllerStartProgress>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof claimsControllerStartProgress>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getClaimsControllerStartProgressMutationOptions(options), queryClient);
    }
    export const claimsControllerAwaitInfo = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<ClaimDetailDto>(
      {url: `/claims/${id}/await-info`, method: 'POST', signal
    },
      options);
    }




export const getClaimsControllerAwaitInfoMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimsControllerAwaitInfo>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof claimsControllerAwaitInfo>>, TError,{id: number}, TContext> => {

const mutationKey = ['claimsControllerAwaitInfo'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof claimsControllerAwaitInfo>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  claimsControllerAwaitInfo(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClaimsControllerAwaitInfoMutationResult = NonNullable<Awaited<ReturnType<typeof claimsControllerAwaitInfo>>>

    export type ClaimsControllerAwaitInfoMutationError = void

    export const useClaimsControllerAwaitInfo = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimsControllerAwaitInfo>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof claimsControllerAwaitInfo>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getClaimsControllerAwaitInfoMutationOptions(options), queryClient);
    }
    export const claimsControllerStartTreatment = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<ClaimDetailDto>(
      {url: `/claims/${id}/start-treatment`, method: 'POST', signal
    },
      options);
    }




export const getClaimsControllerStartTreatmentMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimsControllerStartTreatment>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof claimsControllerStartTreatment>>, TError,{id: number}, TContext> => {

const mutationKey = ['claimsControllerStartTreatment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof claimsControllerStartTreatment>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  claimsControllerStartTreatment(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClaimsControllerStartTreatmentMutationResult = NonNullable<Awaited<ReturnType<typeof claimsControllerStartTreatment>>>

    export type ClaimsControllerStartTreatmentMutationError = void

    export const useClaimsControllerStartTreatment = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimsControllerStartTreatment>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof claimsControllerStartTreatment>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getClaimsControllerStartTreatmentMutationOptions(options), queryClient);
    }
    export const claimsControllerResolve = (
    id: number,
    resolveClaimDto: ResolveClaimDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<ClaimDetailDto>(
      {url: `/claims/${id}/resolve`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resolveClaimDto, signal
    },
      options);
    }




export const getClaimsControllerResolveMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimsControllerResolve>>, TError,{id: number;data: ResolveClaimDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof claimsControllerResolve>>, TError,{id: number;data: ResolveClaimDto}, TContext> => {

const mutationKey = ['claimsControllerResolve'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof claimsControllerResolve>>, {id: number;data: ResolveClaimDto}> = (props) => {
          const {id,data} = props ?? {};

          return  claimsControllerResolve(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClaimsControllerResolveMutationResult = NonNullable<Awaited<ReturnType<typeof claimsControllerResolve>>>
    export type ClaimsControllerResolveMutationBody = ResolveClaimDto
    export type ClaimsControllerResolveMutationError = void

    export const useClaimsControllerResolve = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimsControllerResolve>>, TError,{id: number;data: ResolveClaimDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof claimsControllerResolve>>,
        TError,
        {id: number;data: ResolveClaimDto},
        TContext
      > => {
      return useMutation(getClaimsControllerResolveMutationOptions(options), queryClient);
    }
    export const claimsControllerClose = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<ClaimDetailDto>(
      {url: `/claims/${id}/close`, method: 'POST', signal
    },
      options);
    }




export const getClaimsControllerCloseMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimsControllerClose>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof claimsControllerClose>>, TError,{id: number}, TContext> => {

const mutationKey = ['claimsControllerClose'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof claimsControllerClose>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  claimsControllerClose(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClaimsControllerCloseMutationResult = NonNullable<Awaited<ReturnType<typeof claimsControllerClose>>>

    export type ClaimsControllerCloseMutationError = void

    export const useClaimsControllerClose = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimsControllerClose>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof claimsControllerClose>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getClaimsControllerCloseMutationOptions(options), queryClient);
    }
    export const claimsControllerReject = (
    id: number,
    rejectClaimDto: RejectClaimDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<ClaimDetailDto>(
      {url: `/claims/${id}/reject`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: rejectClaimDto, signal
    },
      options);
    }




export const getClaimsControllerRejectMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimsControllerReject>>, TError,{id: number;data: RejectClaimDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof claimsControllerReject>>, TError,{id: number;data: RejectClaimDto}, TContext> => {

const mutationKey = ['claimsControllerReject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof claimsControllerReject>>, {id: number;data: RejectClaimDto}> = (props) => {
          const {id,data} = props ?? {};

          return  claimsControllerReject(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClaimsControllerRejectMutationResult = NonNullable<Awaited<ReturnType<typeof claimsControllerReject>>>
    export type ClaimsControllerRejectMutationBody = RejectClaimDto
    export type ClaimsControllerRejectMutationError = void

    export const useClaimsControllerReject = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimsControllerReject>>, TError,{id: number;data: RejectClaimDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof claimsControllerReject>>,
        TError,
        {id: number;data: RejectClaimDto},
        TContext
      > => {
      return useMutation(getClaimsControllerRejectMutationOptions(options), queryClient);
    }
    export const claimsControllerSendToDtm = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<ClaimDetailDto>(
      {url: `/claims/${id}/send-to-dtm`, method: 'POST', signal
    },
      options);
    }




export const getClaimsControllerSendToDtmMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimsControllerSendToDtm>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof claimsControllerSendToDtm>>, TError,{id: number}, TContext> => {

const mutationKey = ['claimsControllerSendToDtm'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof claimsControllerSendToDtm>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  claimsControllerSendToDtm(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClaimsControllerSendToDtmMutationResult = NonNullable<Awaited<ReturnType<typeof claimsControllerSendToDtm>>>

    export type ClaimsControllerSendToDtmMutationError = void

    export const useClaimsControllerSendToDtm = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimsControllerSendToDtm>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof claimsControllerSendToDtm>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getClaimsControllerSendToDtmMutationOptions(options), queryClient);
    }
