/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ONCF ECommand API
 * ONCF freight order management
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiErrorResponseDto,
  CreateCustomerDto,
  CustomerDeleteDto,
  CustomerDetailDto,
  CustomerListDto,
  CustomerPortfolioOptionDto,
  CustomersControllerFindAllParams,
  UpdateCustomerDto
} from './generated.schemas';

import { customFetch } from '../axios';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const customersControllerFindPortfolioOptions = (

 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<CustomerPortfolioOptionDto[]>(
      {url: `/customers/portfolio-options`, method: 'GET', signal
    },
      options);
    }




export const getCustomersControllerFindPortfolioOptionsQueryKey = () => {
    return [
    `/customers/portfolio-options`
    ] as const;
    }


export const getCustomersControllerFindPortfolioOptionsQueryOptions = <TData = Awaited<ReturnType<typeof customersControllerFindPortfolioOptions>>, TError = ApiErrorResponseDto>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerFindPortfolioOptions>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCustomersControllerFindPortfolioOptionsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof customersControllerFindPortfolioOptions>>> = ({ signal }) => customersControllerFindPortfolioOptions(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof customersControllerFindPortfolioOptions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CustomersControllerFindPortfolioOptionsQueryResult = NonNullable<Awaited<ReturnType<typeof customersControllerFindPortfolioOptions>>>
export type CustomersControllerFindPortfolioOptionsQueryError = ApiErrorResponseDto


export function useCustomersControllerFindPortfolioOptions<TData = Awaited<ReturnType<typeof customersControllerFindPortfolioOptions>>, TError = ApiErrorResponseDto>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerFindPortfolioOptions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof customersControllerFindPortfolioOptions>>,
          TError,
          Awaited<ReturnType<typeof customersControllerFindPortfolioOptions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCustomersControllerFindPortfolioOptions<TData = Awaited<ReturnType<typeof customersControllerFindPortfolioOptions>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerFindPortfolioOptions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof customersControllerFindPortfolioOptions>>,
          TError,
          Awaited<ReturnType<typeof customersControllerFindPortfolioOptions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCustomersControllerFindPortfolioOptions<TData = Awaited<ReturnType<typeof customersControllerFindPortfolioOptions>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerFindPortfolioOptions>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCustomersControllerFindPortfolioOptions<TData = Awaited<ReturnType<typeof customersControllerFindPortfolioOptions>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerFindPortfolioOptions>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCustomersControllerFindPortfolioOptionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const customersControllerFindAll = (
    params?: CustomersControllerFindAllParams,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<CustomerListDto[]>(
      {url: `/customers`, method: 'GET',
        params, signal
    },
      options);
    }




export const getCustomersControllerFindAllQueryKey = (params?: CustomersControllerFindAllParams,) => {
    return [
    `/customers`, ...(params ? [params] : [])
    ] as const;
    }


export const getCustomersControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof customersControllerFindAll>>, TError = ApiErrorResponseDto>(params?: CustomersControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCustomersControllerFindAllQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof customersControllerFindAll>>> = ({ signal }) => customersControllerFindAll(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof customersControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CustomersControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof customersControllerFindAll>>>
export type CustomersControllerFindAllQueryError = ApiErrorResponseDto


export function useCustomersControllerFindAll<TData = Awaited<ReturnType<typeof customersControllerFindAll>>, TError = ApiErrorResponseDto>(
 params: undefined |  CustomersControllerFindAllParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof customersControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof customersControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCustomersControllerFindAll<TData = Awaited<ReturnType<typeof customersControllerFindAll>>, TError = ApiErrorResponseDto>(
 params?: CustomersControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof customersControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof customersControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCustomersControllerFindAll<TData = Awaited<ReturnType<typeof customersControllerFindAll>>, TError = ApiErrorResponseDto>(
 params?: CustomersControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCustomersControllerFindAll<TData = Awaited<ReturnType<typeof customersControllerFindAll>>, TError = ApiErrorResponseDto>(
 params?: CustomersControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCustomersControllerFindAllQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const customersControllerCreate = (
    createCustomerDto: CreateCustomerDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<CustomerDetailDto>(
      {url: `/customers`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCustomerDto, signal
    },
      options);
    }




export const getCustomersControllerCreateMutationOptions = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof customersControllerCreate>>, TError,{data: CreateCustomerDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof customersControllerCreate>>, TError,{data: CreateCustomerDto}, TContext> => {

const mutationKey = ['customersControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof customersControllerCreate>>, {data: CreateCustomerDto}> = (props) => {
          const {data} = props ?? {};

          return  customersControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CustomersControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof customersControllerCreate>>>
    export type CustomersControllerCreateMutationBody = CreateCustomerDto
    export type CustomersControllerCreateMutationError = ApiErrorResponseDto

    export const useCustomersControllerCreate = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof customersControllerCreate>>, TError,{data: CreateCustomerDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof customersControllerCreate>>,
        TError,
        {data: CreateCustomerDto},
        TContext
      > => {
      return useMutation(getCustomersControllerCreateMutationOptions(options), queryClient);
    }
    export const customersControllerFindOne = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<CustomerDetailDto>(
      {url: `/customers/${id}`, method: 'GET', signal
    },
      options);
    }




export const getCustomersControllerFindOneQueryKey = (id: number,) => {
    return [
    `/customers/${id}`
    ] as const;
    }


export const getCustomersControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof customersControllerFindOne>>, TError = ApiErrorResponseDto>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCustomersControllerFindOneQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof customersControllerFindOne>>> = ({ signal }) => customersControllerFindOne(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof customersControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CustomersControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof customersControllerFindOne>>>
export type CustomersControllerFindOneQueryError = ApiErrorResponseDto


export function useCustomersControllerFindOne<TData = Awaited<ReturnType<typeof customersControllerFindOne>>, TError = ApiErrorResponseDto>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof customersControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof customersControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCustomersControllerFindOne<TData = Awaited<ReturnType<typeof customersControllerFindOne>>, TError = ApiErrorResponseDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof customersControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof customersControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCustomersControllerFindOne<TData = Awaited<ReturnType<typeof customersControllerFindOne>>, TError = ApiErrorResponseDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCustomersControllerFindOne<TData = Awaited<ReturnType<typeof customersControllerFindOne>>, TError = ApiErrorResponseDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCustomersControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const customersControllerUpdate = (
    id: number,
    updateCustomerDto: UpdateCustomerDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<CustomerDetailDto>(
      {url: `/customers/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateCustomerDto, signal
    },
      options);
    }




export const getCustomersControllerUpdateMutationOptions = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof customersControllerUpdate>>, TError,{id: number;data: UpdateCustomerDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof customersControllerUpdate>>, TError,{id: number;data: UpdateCustomerDto}, TContext> => {

const mutationKey = ['customersControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof customersControllerUpdate>>, {id: number;data: UpdateCustomerDto}> = (props) => {
          const {id,data} = props ?? {};

          return  customersControllerUpdate(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CustomersControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof customersControllerUpdate>>>
    export type CustomersControllerUpdateMutationBody = UpdateCustomerDto
    export type CustomersControllerUpdateMutationError = ApiErrorResponseDto

    export const useCustomersControllerUpdate = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof customersControllerUpdate>>, TError,{id: number;data: UpdateCustomerDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof customersControllerUpdate>>,
        TError,
        {id: number;data: UpdateCustomerDto},
        TContext
      > => {
      return useMutation(getCustomersControllerUpdateMutationOptions(options), queryClient);
    }
    export const customersControllerDeactivate = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<CustomerDeleteDto>(
      {url: `/customers/${id}`, method: 'DELETE', signal
    },
      options);
    }




export const getCustomersControllerDeactivateMutationOptions = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof customersControllerDeactivate>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof customersControllerDeactivate>>, TError,{id: number}, TContext> => {

const mutationKey = ['customersControllerDeactivate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof customersControllerDeactivate>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  customersControllerDeactivate(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CustomersControllerDeactivateMutationResult = NonNullable<Awaited<ReturnType<typeof customersControllerDeactivate>>>

    export type CustomersControllerDeactivateMutationError = ApiErrorResponseDto

    export const useCustomersControllerDeactivate = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof customersControllerDeactivate>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof customersControllerDeactivate>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getCustomersControllerDeactivateMutationOptions(options), queryClient);
    }
