/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ONCF ECommand API
 * ONCF freight order management
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiErrorResponseDto,
  DtmOperationsDto,
  DtmRequestResolutionDto,
  ResolveDtmRequestDto
} from './generated.schemas';

import { customFetch } from '../axios';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const dtmOperationsControllerList = (

 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<DtmOperationsDto>(
      {url: `/dtm/requests`, method: 'GET', signal
    },
      options);
    }




export const getDtmOperationsControllerListQueryKey = () => {
    return [
    `/dtm/requests`
    ] as const;
    }


export const getDtmOperationsControllerListQueryOptions = <TData = Awaited<ReturnType<typeof dtmOperationsControllerList>>, TError = ApiErrorResponseDto>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dtmOperationsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDtmOperationsControllerListQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof dtmOperationsControllerList>>> = ({ signal }) => dtmOperationsControllerList(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof dtmOperationsControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DtmOperationsControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof dtmOperationsControllerList>>>
export type DtmOperationsControllerListQueryError = ApiErrorResponseDto


export function useDtmOperationsControllerList<TData = Awaited<ReturnType<typeof dtmOperationsControllerList>>, TError = ApiErrorResponseDto>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof dtmOperationsControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof dtmOperationsControllerList>>,
          TError,
          Awaited<ReturnType<typeof dtmOperationsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDtmOperationsControllerList<TData = Awaited<ReturnType<typeof dtmOperationsControllerList>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dtmOperationsControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof dtmOperationsControllerList>>,
          TError,
          Awaited<ReturnType<typeof dtmOperationsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDtmOperationsControllerList<TData = Awaited<ReturnType<typeof dtmOperationsControllerList>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dtmOperationsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDtmOperationsControllerList<TData = Awaited<ReturnType<typeof dtmOperationsControllerList>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dtmOperationsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDtmOperationsControllerListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const dtmOperationsControllerResolve = (
    id: number,
    resolveDtmRequestDto: ResolveDtmRequestDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<DtmRequestResolutionDto>(
      {url: `/dtm/requests/${id}/resolve`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resolveDtmRequestDto, signal
    },
      options);
    }




export const getDtmOperationsControllerResolveMutationOptions = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dtmOperationsControllerResolve>>, TError,{id: number;data: ResolveDtmRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof dtmOperationsControllerResolve>>, TError,{id: number;data: ResolveDtmRequestDto}, TContext> => {

const mutationKey = ['dtmOperationsControllerResolve'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dtmOperationsControllerResolve>>, {id: number;data: ResolveDtmRequestDto}> = (props) => {
          const {id,data} = props ?? {};

          return  dtmOperationsControllerResolve(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DtmOperationsControllerResolveMutationResult = NonNullable<Awaited<ReturnType<typeof dtmOperationsControllerResolve>>>
    export type DtmOperationsControllerResolveMutationBody = ResolveDtmRequestDto
    export type DtmOperationsControllerResolveMutationError = ApiErrorResponseDto

    export const useDtmOperationsControllerResolve = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dtmOperationsControllerResolve>>, TError,{id: number;data: ResolveDtmRequestDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof dtmOperationsControllerResolve>>,
        TError,
        {id: number;data: ResolveDtmRequestDto},
        TContext
      > => {
      return useMutation(getDtmOperationsControllerResolveMutationOptions(options), queryClient);
    }
