/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ONCF Ecommand API
 * ONCF freight order management
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ListFilesResponseDto,
  MessageResponseDto,
  UploadFileDto,
  UploadFileResponseDto
} from './generated.schemas';

import { customFetch } from '../axios';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const filesControllerUploadFile = (
    id: number,
    uploadFileDto: UploadFileDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {

      const formData = new FormData();
if(uploadFileDto.description !== undefined) {
 formData.append(`description`, uploadFileDto.description);
 }

      return customFetch<UploadFileResponseDto>(
      {url: `/orders/${id}/files`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      options);
    }




export const getFilesControllerUploadFileMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesControllerUploadFile>>, TError,{id: number;data: UploadFileDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof filesControllerUploadFile>>, TError,{id: number;data: UploadFileDto}, TContext> => {

const mutationKey = ['filesControllerUploadFile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof filesControllerUploadFile>>, {id: number;data: UploadFileDto}> = (props) => {
          const {id,data} = props ?? {};

          return  filesControllerUploadFile(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FilesControllerUploadFileMutationResult = NonNullable<Awaited<ReturnType<typeof filesControllerUploadFile>>>
    export type FilesControllerUploadFileMutationBody = UploadFileDto
    export type FilesControllerUploadFileMutationError = void

    export const useFilesControllerUploadFile = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesControllerUploadFile>>, TError,{id: number;data: UploadFileDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof filesControllerUploadFile>>,
        TError,
        {id: number;data: UploadFileDto},
        TContext
      > => {
      return useMutation(getFilesControllerUploadFileMutationOptions(options), queryClient);
    }
    export const filesControllerListFiles = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<ListFilesResponseDto[]>(
      {url: `/orders/${id}/files`, method: 'GET', signal
    },
      options);
    }




export const getFilesControllerListFilesQueryKey = (id: number,) => {
    return [
    `/orders/${id}/files`
    ] as const;
    }


export const getFilesControllerListFilesQueryOptions = <TData = Awaited<ReturnType<typeof filesControllerListFiles>>, TError = void>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerListFiles>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFilesControllerListFilesQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof filesControllerListFiles>>> = ({ signal }) => filesControllerListFiles(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof filesControllerListFiles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FilesControllerListFilesQueryResult = NonNullable<Awaited<ReturnType<typeof filesControllerListFiles>>>
export type FilesControllerListFilesQueryError = void


export function useFilesControllerListFiles<TData = Awaited<ReturnType<typeof filesControllerListFiles>>, TError = void>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerListFiles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesControllerListFiles>>,
          TError,
          Awaited<ReturnType<typeof filesControllerListFiles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesControllerListFiles<TData = Awaited<ReturnType<typeof filesControllerListFiles>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerListFiles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesControllerListFiles>>,
          TError,
          Awaited<ReturnType<typeof filesControllerListFiles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesControllerListFiles<TData = Awaited<ReturnType<typeof filesControllerListFiles>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerListFiles>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFilesControllerListFiles<TData = Awaited<ReturnType<typeof filesControllerListFiles>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerListFiles>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFilesControllerListFilesQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const filesControllerDownloadFile = (
    id: number,
    fileId: string,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<void>(
      {url: `/orders/${id}/files/${fileId}/download`, method: 'GET', signal
    },
      options);
    }




export const getFilesControllerDownloadFileQueryKey = (id: number,
    fileId: string,) => {
    return [
    `/orders/${id}/files/${fileId}/download`
    ] as const;
    }


export const getFilesControllerDownloadFileQueryOptions = <TData = Awaited<ReturnType<typeof filesControllerDownloadFile>>, TError = void>(id: number,
    fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerDownloadFile>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFilesControllerDownloadFileQueryKey(id,fileId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof filesControllerDownloadFile>>> = ({ signal }) => filesControllerDownloadFile(id,fileId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined && fileId !== null && fileId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof filesControllerDownloadFile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FilesControllerDownloadFileQueryResult = NonNullable<Awaited<ReturnType<typeof filesControllerDownloadFile>>>
export type FilesControllerDownloadFileQueryError = void


export function useFilesControllerDownloadFile<TData = Awaited<ReturnType<typeof filesControllerDownloadFile>>, TError = void>(
 id: number,
    fileId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerDownloadFile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesControllerDownloadFile>>,
          TError,
          Awaited<ReturnType<typeof filesControllerDownloadFile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesControllerDownloadFile<TData = Awaited<ReturnType<typeof filesControllerDownloadFile>>, TError = void>(
 id: number,
    fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerDownloadFile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesControllerDownloadFile>>,
          TError,
          Awaited<ReturnType<typeof filesControllerDownloadFile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesControllerDownloadFile<TData = Awaited<ReturnType<typeof filesControllerDownloadFile>>, TError = void>(
 id: number,
    fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerDownloadFile>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFilesControllerDownloadFile<TData = Awaited<ReturnType<typeof filesControllerDownloadFile>>, TError = void>(
 id: number,
    fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerDownloadFile>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFilesControllerDownloadFileQueryOptions(id,fileId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const filesControllerDeleteFile = (
    id: number,
    fileId: string,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<MessageResponseDto>(
      {url: `/orders/${id}/files/${fileId}`, method: 'DELETE', signal
    },
      options);
    }




export const getFilesControllerDeleteFileMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesControllerDeleteFile>>, TError,{id: number;fileId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof filesControllerDeleteFile>>, TError,{id: number;fileId: string}, TContext> => {

const mutationKey = ['filesControllerDeleteFile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof filesControllerDeleteFile>>, {id: number;fileId: string}> = (props) => {
          const {id,fileId} = props ?? {};

          return  filesControllerDeleteFile(id,fileId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FilesControllerDeleteFileMutationResult = NonNullable<Awaited<ReturnType<typeof filesControllerDeleteFile>>>

    export type FilesControllerDeleteFileMutationError = void

    export const useFilesControllerDeleteFile = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesControllerDeleteFile>>, TError,{id: number;fileId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof filesControllerDeleteFile>>,
        TError,
        {id: number;fileId: string},
        TContext
      > => {
      return useMutation(getFilesControllerDeleteFileMutationOptions(options), queryClient);
    }
