/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ONCF Ecommand API
 * ONCF freight order management
 * OpenAPI spec version: 1.0
 */
import { customInstance } from '../axios';
export interface LoginDto {
  username: string;
  /** @minLength 8 */
  password: string;
}

export interface ForgotPasswordDto {
  email: string;
  redirectUrl: string;
}

export interface ResetPasswordDto {
  token: string;
  /** @minLength 8 */
  newPassword: string;
}

export type CreateOrderDtoStatus = typeof CreateOrderDtoStatus[keyof typeof CreateOrderDtoStatus];


export const CreateOrderDtoStatus = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  IN_PROGRESS: 'IN_PROGRESS',
  PARTIALLY_EXECUTED: 'PARTIALLY_EXECUTED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  SENT_TO_DTM: 'SENT_TO_DTM',
} as const;

export interface CreateOrderDto {
  goodsId: number;
  customerId: number;
  userId?: number;
  status?: CreateOrderDtoStatus;
  /** @maxLength 200 */
  supervisor?: string;
  movementTypeId?: number;
  parentOrderId?: number;
  quantityDemanded: string;
  quantityAchieved?: string;
  unitId: number;
  departureStationId?: number;
  debtorCustomerId?: number;
  pickupLocationTypeId?: number;
  dispatchTypeId?: number;
  destinationCustomerId?: number;
  arrivalStationId?: number;
  deliveryLocationTypeId?: number;
  pickupPortId?: number;
  pickupBerthId?: number;
  pickupSidingId?: number;
  deliveryPortId?: number;
  deliveryBerthId?: number;
  deliverySidingId?: number;
  remarks?: string;
  orderDate?: string;
  startDate?: string;
  endDate?: string;
}

export type UpdateOrderDtoStatus = typeof UpdateOrderDtoStatus[keyof typeof UpdateOrderDtoStatus];


export const UpdateOrderDtoStatus = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  IN_PROGRESS: 'IN_PROGRESS',
  PARTIALLY_EXECUTED: 'PARTIALLY_EXECUTED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  SENT_TO_DTM: 'SENT_TO_DTM',
} as const;

export interface UpdateOrderDto {
  goodsId?: number;
  customerId?: number;
  userId?: number;
  status?: UpdateOrderDtoStatus;
  /** @maxLength 200 */
  supervisor?: string;
  movementTypeId?: number;
  parentOrderId?: number;
  quantityDemanded?: string;
  quantityAchieved?: string;
  unitId?: number;
  departureStationId?: number;
  debtorCustomerId?: number;
  pickupLocationTypeId?: number;
  dispatchTypeId?: number;
  destinationCustomerId?: number;
  arrivalStationId?: number;
  deliveryLocationTypeId?: number;
  pickupPortId?: number;
  pickupBerthId?: number;
  pickupSidingId?: number;
  deliveryPortId?: number;
  deliveryBerthId?: number;
  deliverySidingId?: number;
  remarks?: string;
  orderDate?: string;
  startDate?: string;
  endDate?: string;
}

export interface UploadFileDto {
  description?: string;
}

export type CreateProgramDtoStatus = typeof CreateProgramDtoStatus[keyof typeof CreateProgramDtoStatus];


export const CreateProgramDtoStatus = {
  DRAFT: 'DRAFT',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  SENT_TO_DTM: 'SENT_TO_DTM',
  CONFIRMED: 'CONFIRMED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export interface CreateProgramDto {
  orderId: number;
  userId?: number;
  status?: CreateProgramDtoStatus;
  plannedDate: string;
  quantityPlanned: string;
  quantityRealized?: string;
  dtmStatus?: string;
}

export type UpdateProgramDtoStatus = typeof UpdateProgramDtoStatus[keyof typeof UpdateProgramDtoStatus];


export const UpdateProgramDtoStatus = {
  DRAFT: 'DRAFT',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  SENT_TO_DTM: 'SENT_TO_DTM',
  CONFIRMED: 'CONFIRMED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export interface UpdateProgramDto {
  orderId?: number;
  userId?: number;
  status?: UpdateProgramDtoStatus;
  plannedDate?: string;
  quantityPlanned?: string;
  quantityRealized?: string;
  dtmStatus?: string;
}

export interface CreateCustomerDto {
  /** @maxLength 300 */
  companyName: string;
  /** @maxLength 500 */
  address?: string;
  /** @maxLength 100 */
  city?: string;
  /** @maxLength 20 */
  phone?: string;
  /** @maxLength 100 */
  email?: string;
  typeId?: number;
  /** @maxLength 50 */
  customerCode?: string;
  isActive?: boolean;
}

export interface UpdateCustomerDto {
  /** @maxLength 300 */
  companyName?: string;
  /** @maxLength 500 */
  address?: string;
  /** @maxLength 100 */
  city?: string;
  /** @maxLength 20 */
  phone?: string;
  /** @maxLength 100 */
  email?: string;
  typeId?: number;
  /** @maxLength 50 */
  customerCode?: string;
  isActive?: boolean;
}

export interface CreateClaimDto { [key: string]: unknown }

export interface UpdateClaimDto { [key: string]: unknown }

export type AuthControllerGetProfile200 = { [key: string]: unknown };

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const appControllerHealth = (

 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/health`, method: 'GET'
    },
      options);
    }

export const usersControllerFindAll = (

 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/users`, method: 'GET'
    },
      options);
    }

export const usersControllerFindOneById = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/users/${id}`, method: 'GET'
    },
      options);
    }

export const authControllerLogin = (
    loginDto: LoginDto,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginDto
    },
      options);
    }

export const authControllerGetProfile = (

 options?: SecondParameter<typeof customInstance<AuthControllerGetProfile200>>,) => {
      return customInstance<AuthControllerGetProfile200>(
      {url: `/auth/profile`, method: 'GET'
    },
      options);
    }

export const authControllerForgotPassword = (
    forgotPasswordDto: ForgotPasswordDto,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/auth/forgot-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: forgotPasswordDto
    },
      options);
    }

export const authControllerResetPassword = (
    resetPasswordDto: ResetPasswordDto,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/auth/reset-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resetPasswordDto
    },
      options);
    }

export const ordersControllerCreate = (
    createOrderDto: CreateOrderDto,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/orders`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createOrderDto
    },
      options);
    }

export const ordersControllerFindAll = (

 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/orders`, method: 'GET'
    },
      options);
    }

export const ordersControllerFindOne = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/orders/${id}`, method: 'GET'
    },
      options);
    }

export const ordersControllerUpdate = (
    id: number,
    updateOrderDto: UpdateOrderDto,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/orders/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateOrderDto
    },
      options);
    }

export const ordersControllerRemove = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/orders/${id}`, method: 'DELETE'
    },
      options);
    }

export const ordersControllerSubmit = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/orders/${id}/submit`, method: 'POST'
    },
      options);
    }

export const ordersControllerApprove = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/orders/${id}/approve`, method: 'POST'
    },
      options);
    }

export const ordersControllerReject = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/orders/${id}/reject`, method: 'POST'
    },
      options);
    }

export const ordersControllerCancel = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/orders/${id}/cancel`, method: 'POST'
    },
      options);
    }

export const ordersControllerSendToDtm = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/orders/${id}/send-to-dtm`, method: 'POST'
    },
      options);
    }

export const filesControllerUploadFile = (
    id: number,
    uploadFileDto: UploadFileDto,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/orders/${id}/files`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: uploadFileDto
    },
      options);
    }

export const filesControllerListFiles = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/orders/${id}/files`, method: 'GET'
    },
      options);
    }

export const filesControllerDownloadFile = (
    id: number,
    fileId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/orders/${id}/files/${fileId}/download`, method: 'GET'
    },
      options);
    }

export const filesControllerDeleteFile = (
    id: number,
    fileId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/orders/${id}/files/${fileId}`, method: 'DELETE'
    },
      options);
    }

export const programsControllerCreate = (
    createProgramDto: CreateProgramDto,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/programs`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createProgramDto
    },
      options);
    }

export const programsControllerFindAll = (

 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/programs`, method: 'GET'
    },
      options);
    }

export const programsControllerFindOne = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/programs/${id}`, method: 'GET'
    },
      options);
    }

export const programsControllerUpdate = (
    id: number,
    updateProgramDto: UpdateProgramDto,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/programs/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateProgramDto
    },
      options);
    }

export const programsControllerRemove = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/programs/${id}`, method: 'DELETE'
    },
      options);
    }

export const programsControllerSubmit = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/programs/${id}/submit`, method: 'POST'
    },
      options);
    }

export const programsControllerApprove = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/programs/${id}/approve`, method: 'POST'
    },
      options);
    }

export const programsControllerConfirm = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/programs/${id}/confirm`, method: 'POST'
    },
      options);
    }

export const programsControllerSendToDtm = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/programs/${id}/send`, method: 'POST'
    },
      options);
    }

export const programsControllerCancel = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/programs/${id}/cancel`, method: 'POST'
    },
      options);
    }

export const customersControllerFindAll = (

 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/customers`, method: 'GET'
    },
      options);
    }

export const customersControllerCreate = (
    createCustomerDto: CreateCustomerDto,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/customers`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCustomerDto
    },
      options);
    }

export const customersControllerFindOne = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/customers/${id}`, method: 'GET'
    },
      options);
    }

export const customersControllerUpdate = (
    id: number,
    updateCustomerDto: UpdateCustomerDto,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/customers/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateCustomerDto
    },
      options);
    }

export const customersControllerRemove = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/customers/${id}`, method: 'DELETE'
    },
      options);
    }

export const claimsControllerCreate = (
    createClaimDto: CreateClaimDto,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/claims`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createClaimDto
    },
      options);
    }

export const claimsControllerFindAll = (

 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/claims`, method: 'GET'
    },
      options);
    }

export const claimsControllerFindOne = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/claims/${id}`, method: 'GET'
    },
      options);
    }

export const claimsControllerUpdate = (
    id: number,
    updateClaimDto: UpdateClaimDto,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/claims/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateClaimDto
    },
      options);
    }

export const claimsControllerRemove = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/claims/${id}`, method: 'DELETE'
    },
      options);
    }

export const claimsControllerAddComment = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/claims/${id}/comments`, method: 'POST'
    },
      options);
    }

export const claimsControllerGetComments = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/claims/${id}/comments`, method: 'GET'
    },
      options);
    }

export const claimsControllerStartProgress = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/claims/${id}/start-progress`, method: 'POST'
    },
      options);
    }

export const claimsControllerAwaitInfo = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/claims/${id}/await-info`, method: 'POST'
    },
      options);
    }

export const claimsControllerStartTreatment = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/claims/${id}/start-treatment`, method: 'POST'
    },
      options);
    }

export const claimsControllerResolve = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/claims/${id}/resolve`, method: 'POST'
    },
      options);
    }

export const claimsControllerClose = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/claims/${id}/close`, method: 'POST'
    },
      options);
    }

export const claimsControllerReject = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/claims/${id}/reject`, method: 'POST'
    },
      options);
    }

export const claimsControllerSendToDtm = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/claims/${id}/send-to-dtm`, method: 'POST'
    },
      options);
    }

export const notificationsControllerFindAll = (

 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/notifications`, method: 'GET'
    },
      options);
    }

export const notificationsControllerGetUnreadCount = (

 options?: SecondParameter<typeof customInstance<number>>,) => {
      return customInstance<number>(
      {url: `/notifications/unread-count`, method: 'GET'
    },
      options);
    }

export const notificationsControllerMarkAsRead = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/notifications/${id}/read`, method: 'PATCH'
    },
      options);
    }

export const notificationsControllerMarkAllAsRead = (

 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/notifications/read-all`, method: 'PATCH'
    },
      options);
    }

export type AppControllerHealthResult = NonNullable<Awaited<ReturnType<typeof appControllerHealth>>>
export type UsersControllerFindAllResult = NonNullable<Awaited<ReturnType<typeof usersControllerFindAll>>>
export type UsersControllerFindOneByIdResult = NonNullable<Awaited<ReturnType<typeof usersControllerFindOneById>>>
export type AuthControllerLoginResult = NonNullable<Awaited<ReturnType<typeof authControllerLogin>>>
export type AuthControllerGetProfileResult = NonNullable<Awaited<ReturnType<typeof authControllerGetProfile>>>
export type AuthControllerForgotPasswordResult = NonNullable<Awaited<ReturnType<typeof authControllerForgotPassword>>>
export type AuthControllerResetPasswordResult = NonNullable<Awaited<ReturnType<typeof authControllerResetPassword>>>
export type OrdersControllerCreateResult = NonNullable<Awaited<ReturnType<typeof ordersControllerCreate>>>
export type OrdersControllerFindAllResult = NonNullable<Awaited<ReturnType<typeof ordersControllerFindAll>>>
export type OrdersControllerFindOneResult = NonNullable<Awaited<ReturnType<typeof ordersControllerFindOne>>>
export type OrdersControllerUpdateResult = NonNullable<Awaited<ReturnType<typeof ordersControllerUpdate>>>
export type OrdersControllerRemoveResult = NonNullable<Awaited<ReturnType<typeof ordersControllerRemove>>>
export type OrdersControllerSubmitResult = NonNullable<Awaited<ReturnType<typeof ordersControllerSubmit>>>
export type OrdersControllerApproveResult = NonNullable<Awaited<ReturnType<typeof ordersControllerApprove>>>
export type OrdersControllerRejectResult = NonNullable<Awaited<ReturnType<typeof ordersControllerReject>>>
export type OrdersControllerCancelResult = NonNullable<Awaited<ReturnType<typeof ordersControllerCancel>>>
export type OrdersControllerSendToDtmResult = NonNullable<Awaited<ReturnType<typeof ordersControllerSendToDtm>>>
export type FilesControllerUploadFileResult = NonNullable<Awaited<ReturnType<typeof filesControllerUploadFile>>>
export type FilesControllerListFilesResult = NonNullable<Awaited<ReturnType<typeof filesControllerListFiles>>>
export type FilesControllerDownloadFileResult = NonNullable<Awaited<ReturnType<typeof filesControllerDownloadFile>>>
export type FilesControllerDeleteFileResult = NonNullable<Awaited<ReturnType<typeof filesControllerDeleteFile>>>
export type ProgramsControllerCreateResult = NonNullable<Awaited<ReturnType<typeof programsControllerCreate>>>
export type ProgramsControllerFindAllResult = NonNullable<Awaited<ReturnType<typeof programsControllerFindAll>>>
export type ProgramsControllerFindOneResult = NonNullable<Awaited<ReturnType<typeof programsControllerFindOne>>>
export type ProgramsControllerUpdateResult = NonNullable<Awaited<ReturnType<typeof programsControllerUpdate>>>
export type ProgramsControllerRemoveResult = NonNullable<Awaited<ReturnType<typeof programsControllerRemove>>>
export type ProgramsControllerSubmitResult = NonNullable<Awaited<ReturnType<typeof programsControllerSubmit>>>
export type ProgramsControllerApproveResult = NonNullable<Awaited<ReturnType<typeof programsControllerApprove>>>
export type ProgramsControllerConfirmResult = NonNullable<Awaited<ReturnType<typeof programsControllerConfirm>>>
export type ProgramsControllerSendToDtmResult = NonNullable<Awaited<ReturnType<typeof programsControllerSendToDtm>>>
export type ProgramsControllerCancelResult = NonNullable<Awaited<ReturnType<typeof programsControllerCancel>>>
export type CustomersControllerFindAllResult = NonNullable<Awaited<ReturnType<typeof customersControllerFindAll>>>
export type CustomersControllerCreateResult = NonNullable<Awaited<ReturnType<typeof customersControllerCreate>>>
export type CustomersControllerFindOneResult = NonNullable<Awaited<ReturnType<typeof customersControllerFindOne>>>
export type CustomersControllerUpdateResult = NonNullable<Awaited<ReturnType<typeof customersControllerUpdate>>>
export type CustomersControllerRemoveResult = NonNullable<Awaited<ReturnType<typeof customersControllerRemove>>>
export type ClaimsControllerCreateResult = NonNullable<Awaited<ReturnType<typeof claimsControllerCreate>>>
export type ClaimsControllerFindAllResult = NonNullable<Awaited<ReturnType<typeof claimsControllerFindAll>>>
export type ClaimsControllerFindOneResult = NonNullable<Awaited<ReturnType<typeof claimsControllerFindOne>>>
export type ClaimsControllerUpdateResult = NonNullable<Awaited<ReturnType<typeof claimsControllerUpdate>>>
export type ClaimsControllerRemoveResult = NonNullable<Awaited<ReturnType<typeof claimsControllerRemove>>>
export type ClaimsControllerAddCommentResult = NonNullable<Awaited<ReturnType<typeof claimsControllerAddComment>>>
export type ClaimsControllerGetCommentsResult = NonNullable<Awaited<ReturnType<typeof claimsControllerGetComments>>>
export type ClaimsControllerStartProgressResult = NonNullable<Awaited<ReturnType<typeof claimsControllerStartProgress>>>
export type ClaimsControllerAwaitInfoResult = NonNullable<Awaited<ReturnType<typeof claimsControllerAwaitInfo>>>
export type ClaimsControllerStartTreatmentResult = NonNullable<Awaited<ReturnType<typeof claimsControllerStartTreatment>>>
export type ClaimsControllerResolveResult = NonNullable<Awaited<ReturnType<typeof claimsControllerResolve>>>
export type ClaimsControllerCloseResult = NonNullable<Awaited<ReturnType<typeof claimsControllerClose>>>
export type ClaimsControllerRejectResult = NonNullable<Awaited<ReturnType<typeof claimsControllerReject>>>
export type ClaimsControllerSendToDtmResult = NonNullable<Awaited<ReturnType<typeof claimsControllerSendToDtm>>>
export type NotificationsControllerFindAllResult = NonNullable<Awaited<ReturnType<typeof notificationsControllerFindAll>>>
export type NotificationsControllerGetUnreadCountResult = NonNullable<Awaited<ReturnType<typeof notificationsControllerGetUnreadCount>>>
export type NotificationsControllerMarkAsReadResult = NonNullable<Awaited<ReturnType<typeof notificationsControllerMarkAsRead>>>
export type NotificationsControllerMarkAllAsReadResult = NonNullable<Awaited<ReturnType<typeof notificationsControllerMarkAllAsRead>>>
