/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ONCF Ecommand API
 * ONCF freight order management
 * OpenAPI spec version: 1.0
 */
export type UserListDtoRole = {
  id: string;
  name: string;
};

export interface UserListDto {
  id: number;
  email: string;
  lastName: string;
  firstName: string;
  /** @nullable */
  employeeId: string | null;
  /** @nullable */
  type: string | null;
  roleId: string;
  role: UserListDtoRole;
  /** @nullable */
  customerId: number | null;
  /** @nullable */
  agencyId: number | null;
  createdAt: string;
  updatedAt: string;
  isActive: boolean;
  /** @nullable */
  lastLogin: string | null;
}

export type UserDetailDtoRole = {
  id: string;
  name: string;
};

export interface UserDetailDto {
  id: number;
  email: string;
  lastName: string;
  firstName: string;
  /** @nullable */
  employeeId: string | null;
  /** @nullable */
  type: string | null;
  roleId: string;
  role: UserDetailDtoRole;
  /** @nullable */
  customerId: number | null;
  /** @nullable */
  agencyId: number | null;
  createdAt: string;
  updatedAt: string;
  isActive: boolean;
  /** @nullable */
  lastLogin: string | null;
}

export type CreateUserDtoRole = typeof CreateUserDtoRole[keyof typeof CreateUserDtoRole];


export const CreateUserDtoRole = {
  ADMIN: 'ADMIN',
  AGENT_COMMERCIAL: 'AGENT_COMMERCIAL',
  CLIENT_REPRESENTATIVE: 'CLIENT_REPRESENTATIVE',
} as const;

/**
 * @maxLength 20
 */
export type CreateUserDtoType = typeof CreateUserDtoType[keyof typeof CreateUserDtoType];


export const CreateUserDtoType = {
  internal: 'internal',
  external: 'external',
} as const;

export interface CreateUserDto {
  /** @maxLength 100 */
  email: string;
  /**
     * @minLength 8
     * @maxLength 255
     */
  password: string;
  /** @maxLength 100 */
  firstName: string;
  /** @maxLength 100 */
  lastName: string;
  role: CreateUserDtoRole;
  /** @maxLength 50 */
  employeeId?: string;
  /** @maxLength 20 */
  type?: CreateUserDtoType;
  customerId?: number;
  agencyId?: number;
  isActive?: boolean;
}

export type UpdateUserDtoRole = typeof UpdateUserDtoRole[keyof typeof UpdateUserDtoRole];


export const UpdateUserDtoRole = {
  ADMIN: 'ADMIN',
  AGENT_COMMERCIAL: 'AGENT_COMMERCIAL',
  CLIENT_REPRESENTATIVE: 'CLIENT_REPRESENTATIVE',
} as const;

/**
 * @maxLength 20
 */
export type UpdateUserDtoType = typeof UpdateUserDtoType[keyof typeof UpdateUserDtoType];


export const UpdateUserDtoType = {
  internal: 'internal',
  external: 'external',
} as const;

export interface UpdateUserDto {
  /** @maxLength 100 */
  email?: string;
  /** @maxLength 100 */
  firstName?: string;
  /** @maxLength 100 */
  lastName?: string;
  role?: UpdateUserDtoRole;
  /** @maxLength 50 */
  employeeId?: string;
  /** @maxLength 20 */
  type?: UpdateUserDtoType;
  customerId?: number;
  agencyId?: number;
  isActive?: boolean;
}

export interface UserDeleteDto {
  id: number;
}

export interface LoginDto {
  username: string;
  /** @minLength 8 */
  password: string;
}

export interface LoginDetailDto {
  access_token: string;
}

export interface ChangePasswordDto {
  currentPassword: string;
  /** @minLength 8 */
  newPassword: string;
}

export interface ForgotPasswordDto {
  email: string;
  redirectUrl: string;
}

export interface ResetPasswordDto {
  token: string;
  /** @minLength 8 */
  newPassword: string;
}

export type CreateOrderDtoStatus = typeof CreateOrderDtoStatus[keyof typeof CreateOrderDtoStatus];


export const CreateOrderDtoStatus = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  IN_PROGRESS: 'IN_PROGRESS',
  PARTIALLY_EXECUTED: 'PARTIALLY_EXECUTED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  SENT_TO_DTM: 'SENT_TO_DTM',
} as const;

export interface CreateOrderDto {
  goodsId: number;
  customerId: number;
  status?: CreateOrderDtoStatus;
  /** @maxLength 200 */
  supervisor?: string;
  movementTypeId?: string;
  parentOrderId?: number;
  quantityDemanded: string;
  quantityAchieved?: string;
  unitId: string;
  departureStationId?: number;
  debtorCustomerId?: number;
  pickupLocationTypeId?: string;
  dispatchTypeId?: string;
  destinationCustomerId?: number;
  arrivalStationId?: number;
  deliveryLocationTypeId?: string;
  pickupPortId?: number;
  pickupBerthId?: number;
  pickupSidingId?: number;
  deliveryPortId?: number;
  deliveryBerthId?: number;
  deliverySidingId?: number;
  remarks?: string;
  orderDate?: string;
  startDate?: string;
  endDate?: string;
}

export type OrderDetailDtoOrderStatus = {
  id: string;
  name: string;
};

export type OrderDetailDtoForecastProgramsItem = {
  id: number;
  createdByUserId: number;
  statusId: string;
  createdAt: string;
  updatedAt: string;
  orderId: number;
  programNumber: string;
  plannedDate: string;
  quantityPlanned: string;
  /** @nullable */
  quantityRealized: string | null;
  /** @nullable */
  deviationReason: string | null;
  /** @nullable */
  realizedAt: string | null;
  /** @nullable */
  realizedByUserId: number | null;
  /** @nullable */
  sentToDtmAt: string | null;
  /** @nullable */
  dtmStatus: string | null;
};

export type OrderDetailDtoOrderExecutionsItem = {
  id: number;
  createdAt: string;
  orderId: number;
  /** @nullable */
  comment: string | null;
  /** @nullable */
  completionRate: string | null;
  executionDate: string;
  quantityExecuted: string;
  executedByUserId: number;
};

export type OrderDetailDtoOrderFilesItem = {
  /** @nullable */
  description: string | null;
  orderId: number;
  fileId: number;
  fileName: string;
  fileType: string;
  fileSize: number;
  filePath: string;
  /** @nullable */
  mimeType: string | null;
  uploadedByUserId: number;
  uploadedAt: string;
};

export type OrderDetailDtoClaimsItem = {
  id: number;
  customerId: number;
  createdByUserId: number;
  statusId: string;
  createdAt: string;
  updatedAt: string;
  typeId: string;
  description: string;
  /** @nullable */
  orderId: number | null;
  /** @nullable */
  operationId: string | null;
  /** @nullable */
  priority: string | null;
  /** @nullable */
  resolution: string | null;
  /** @nullable */
  closedByUserId: number | null;
  /** @nullable */
  closedAt: string | null;
};

export type OrderDetailDtoUnit = {
  name: string;
};

export type OrderDetailDtoCustomer = {
  id: number;
  companyName: string;
};

export type OrderDetailDtoOrderStatusHistoriesItem = {
  id: number;
  statusId: string;
  orderId: number;
  changedById: number;
  changedAt: string;
  /** @nullable */
  comment: string | null;
  /** @nullable */
  rejectionReasonId: string | null;
};

export type OrderDetailDtoGood = {
  id: number;
  name: string;
};

export type OrderDetailDtoCreatedByUser = {
  id: number;
  lastName: string;
  firstName: string;
};

export interface OrderDetailDto {
  id: number;
  goodsId: number;
  customerId: number;
  createdByUserId: number;
  statusId: string;
  /** @nullable */
  supervisor: string | null;
  orderNumber: string;
  /** @nullable */
  movementTypeId: string | null;
  /** @nullable */
  parentOrderId: number | null;
  quantityDemanded: string;
  /** @nullable */
  quantityAchieved: string | null;
  unitId: string;
  /** @nullable */
  departureStationId: number | null;
  /** @nullable */
  debtorCustomerId: number | null;
  /** @nullable */
  pickupLocationTypeId: string | null;
  /** @nullable */
  dispatchTypeId: string | null;
  /** @nullable */
  destinationCustomerId: number | null;
  /** @nullable */
  arrivalStationId: number | null;
  /** @nullable */
  deliveryLocationTypeId: string | null;
  /** @nullable */
  pickupPortId: number | null;
  /** @nullable */
  pickupBerthId: number | null;
  /** @nullable */
  pickupSidingId: number | null;
  /** @nullable */
  deliveryPortId: number | null;
  /** @nullable */
  deliveryBerthId: number | null;
  /** @nullable */
  deliverySidingId: number | null;
  /** @nullable */
  remarks: string | null;
  orderDate: string;
  /** @nullable */
  startDate: string | null;
  /** @nullable */
  endDate: string | null;
  createdAt: string;
  updatedAt: string;
  orderStatus: OrderDetailDtoOrderStatus;
  forecastPrograms: OrderDetailDtoForecastProgramsItem[];
  orderExecutions: OrderDetailDtoOrderExecutionsItem[];
  orderFiles: OrderDetailDtoOrderFilesItem[];
  claims: OrderDetailDtoClaimsItem[];
  unit: OrderDetailDtoUnit;
  customer: OrderDetailDtoCustomer;
  orderStatusHistories: OrderDetailDtoOrderStatusHistoriesItem[];
  good: OrderDetailDtoGood;
  createdByUser: OrderDetailDtoCreatedByUser;
}

export interface Object { [key: string]: unknown }

export type OrderListDtoOrderStatus = {
  id: string;
  name: string;
};

export type OrderListDtoUnit = {
  name: string;
};

export type OrderListDtoCustomer = {
  id: number;
  companyName: string;
};

export type OrderListDtoGood = {
  id: number;
  name: string;
};

export type OrderListDtoCreatedByUser = {
  id: number;
  lastName: string;
  firstName: string;
};

export interface OrderListDto {
  id: number;
  createdAt: string;
  orderNumber: string;
  quantityDemanded: string;
  /** @nullable */
  quantityAchieved: string | null;
  orderDate: string;
  /** @nullable */
  startDate: string | null;
  /** @nullable */
  endDate: string | null;
  orderStatus: OrderListDtoOrderStatus;
  unit: OrderListDtoUnit;
  customer: OrderListDtoCustomer;
  good: OrderListDtoGood;
  createdByUser: OrderListDtoCreatedByUser;
}

export interface EligibleOrderForProgramDto {
  id: number;
  orderNumber: string;
  quantityDemanded: string;
}

export type UpdateOrderDtoStatus = typeof UpdateOrderDtoStatus[keyof typeof UpdateOrderDtoStatus];


export const UpdateOrderDtoStatus = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  IN_PROGRESS: 'IN_PROGRESS',
  PARTIALLY_EXECUTED: 'PARTIALLY_EXECUTED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  SENT_TO_DTM: 'SENT_TO_DTM',
} as const;

export interface UpdateOrderDto {
  goodsId?: number;
  customerId?: number;
  status?: UpdateOrderDtoStatus;
  /** @maxLength 200 */
  supervisor?: string;
  movementTypeId?: string;
  parentOrderId?: number;
  quantityDemanded?: string;
  quantityAchieved?: string;
  unitId?: string;
  departureStationId?: number;
  debtorCustomerId?: number;
  pickupLocationTypeId?: string;
  dispatchTypeId?: string;
  destinationCustomerId?: number;
  arrivalStationId?: number;
  deliveryLocationTypeId?: string;
  pickupPortId?: number;
  pickupBerthId?: number;
  pickupSidingId?: number;
  deliveryPortId?: number;
  deliveryBerthId?: number;
  deliverySidingId?: number;
  remarks?: string;
  orderDate?: string;
  startDate?: string;
  endDate?: string;
}

export interface RejectOrderDto {
  reason: string;
}

export interface OrderDeleteDto {
  id: number;
}

export interface UploadFileDto {
  description?: string;
}

export interface FileDto {
  /** @nullable */
  description: string | null;
  orderId: number;
  fileId: number;
  fileName: string;
  fileType: string;
  fileSize: number;
  filePath: string;
  /** @nullable */
  mimeType: string | null;
  uploadedByUserId: number;
  uploadedAt: string;
}

export interface MessageResponseDto {
  message: string;
}

export type CreateProgramDtoStatus = typeof CreateProgramDtoStatus[keyof typeof CreateProgramDtoStatus];


export const CreateProgramDtoStatus = {
  DRAFT: 'DRAFT',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  SENT_TO_DTM: 'SENT_TO_DTM',
  CONFIRMED: 'CONFIRMED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export interface CreateProgramDto {
  orderId: number;
  userId?: number;
  status?: CreateProgramDtoStatus;
  plannedDate: string;
  quantityPlanned: string;
  quantityRealized?: string;
  dtmStatus?: string;
}

export type ProgramDetailDtoProgramStatus = {
  id: string;
  name: string;
};

export type ProgramDetailDtoOrderWagonsItem = {
  id: number;
  orderId: number;
  createdAt: string;
  /** @nullable */
  trainId: number | null;
  wagonId: number;
  /** @nullable */
  quantityLoaded: string | null;
  /** @nullable */
  forecastProgramId: number | null;
};

export type ProgramDetailDtoForecastProgramHistoriesItem = {
  id: number;
  /** @nullable */
  quantityRealized: string | null;
  /** @nullable */
  deviationReason: string | null;
  changedAt: string;
  /** @nullable */
  programId: number | null;
  eventType: string;
  /** @nullable */
  oldQuantity: string | null;
  /** @nullable */
  newQuantity: string | null;
  /** @nullable */
  oldStatusId: string | null;
  /** @nullable */
  newStatusId: string | null;
  /** @nullable */
  oldPlannedDate: string | null;
  /** @nullable */
  newPlannedDate: string | null;
  /** @nullable */
  completionRate: string | null;
  /** @nullable */
  changedByName: string | null;
  changedByUserId: number;
  /** @nullable */
  reason: string | null;
};

export type ProgramDetailDtoOrder = {
  id: number;
  orderNumber: string;
};

export type ProgramDetailDtoCreatedByUser = {
  id: number;
  lastName: string;
  firstName: string;
};

export type ProgramDetailDtoRealizedByUser = {
  id: number;
  lastName: string;
  firstName: string;
};

export type ProgramDetailDtoProgramConvoisItem = {
  id: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  status: string | null;
  trainId: number;
  forecastProgramId: number;
  /** @nullable */
  lastLatitude: string | null;
  /** @nullable */
  lastLongitude: string | null;
  convoy: string;
  /** @nullable */
  since: string | null;
  /** @nullable */
  quantity: string | null;
  /** @nullable */
  unit: string | null;
  /** @nullable */
  wagonCount: number | null;
  /** @nullable */
  eta: string | null;
  /** @nullable */
  delayMinutes: number | null;
};

export interface ProgramDetailDto {
  id: number;
  programNumber: string;
  orderId: number;
  statusId: string;
  plannedDate: string;
  quantityPlanned: string;
  /** @nullable */
  quantityRealized: string | null;
  /** @nullable */
  deviationReason: string | null;
  /** @nullable */
  realizedAt: string | null;
  /** @nullable */
  realizedByUserId: number | null;
  createdByUserId: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  sentToDtmAt: string | null;
  /** @nullable */
  dtmStatus: string | null;
  programStatus: ProgramDetailDtoProgramStatus;
  orderWagons: ProgramDetailDtoOrderWagonsItem[];
  forecastProgramHistories: ProgramDetailDtoForecastProgramHistoriesItem[];
  order: ProgramDetailDtoOrder;
  createdByUser: ProgramDetailDtoCreatedByUser;
  realizedByUser: ProgramDetailDtoRealizedByUser;
  programConvois: ProgramDetailDtoProgramConvoisItem[];
}

export type ProgramListDtoProgramStatus = {
  id: string;
  name: string;
};

export type ProgramListDtoOrder = {
  id: number;
  orderNumber: string;
};

export type ProgramListDtoCreatedByUser = {
  id: number;
  lastName: string;
  firstName: string;
};

export interface ProgramListDto {
  id: number;
  createdAt: string;
  /** @nullable */
  quantityRealized: string | null;
  plannedDate: string;
  quantityPlanned: string;
  /** @nullable */
  sentToDtmAt: string | null;
  programNumber: string;
  programStatus: ProgramListDtoProgramStatus;
  order: ProgramListDtoOrder;
  createdByUser: ProgramListDtoCreatedByUser;
}

export type UpdateProgramDtoStatus = typeof UpdateProgramDtoStatus[keyof typeof UpdateProgramDtoStatus];


export const UpdateProgramDtoStatus = {
  DRAFT: 'DRAFT',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  SENT_TO_DTM: 'SENT_TO_DTM',
  CONFIRMED: 'CONFIRMED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export interface UpdateProgramDto {
  orderId?: number;
  userId?: number;
  status?: UpdateProgramDtoStatus;
  plannedDate?: string;
  quantityPlanned?: string;
  quantityRealized?: string;
  dtmStatus?: string;
}

export interface ProgramDeleteDto {
  id: number;
}

export interface CustomerListDto {
  id: number;
  createdAt: string;
  isActive: boolean;
  updatedAt: string;
  companyName: string;
  /** @nullable */
  address: string | null;
  /** @nullable */
  city: string | null;
  /** @nullable */
  phone: string | null;
  /** @nullable */
  email: string | null;
  /** @nullable */
  typeId: string | null;
  /** @nullable */
  customerCode: string | null;
}

export interface CustomerDetailDto {
  id: number;
  companyName: string;
  /** @nullable */
  address: string | null;
  /** @nullable */
  city: string | null;
  /** @nullable */
  phone: string | null;
  /** @nullable */
  email: string | null;
  /** @nullable */
  typeId: string | null;
  createdAt: string;
  updatedAt: string;
  isActive: boolean;
  /** @nullable */
  customerCode: string | null;
}

export interface CreateCustomerDto {
  /** @maxLength 300 */
  companyName: string;
  /** @maxLength 500 */
  address?: string;
  /** @maxLength 100 */
  city?: string;
  /** @maxLength 20 */
  phone?: string;
  /** @maxLength 100 */
  email?: string;
  typeId?: string;
  /** @maxLength 50 */
  customerCode?: string;
  isActive?: boolean;
}

export interface UpdateCustomerDto {
  /** @maxLength 300 */
  companyName?: string;
  /** @maxLength 500 */
  address?: string;
  /** @maxLength 100 */
  city?: string;
  /** @maxLength 20 */
  phone?: string;
  /** @maxLength 100 */
  email?: string;
  typeId?: string;
  /** @maxLength 50 */
  customerCode?: string;
  isActive?: boolean;
}

export interface CustomerDeleteDto {
  id: number;
}

export type CreateClaimDtoType = typeof CreateClaimDtoType[keyof typeof CreateClaimDtoType];


export const CreateClaimDtoType = {
  DELIVERY_DELAY: 'DELIVERY_DELAY',
  DAMAGED_GOODS: 'DAMAGED_GOODS',
  INCORRECT_QUANTITY: 'INCORRECT_QUANTITY',
  NON_COMPLIANT_QUALITY: 'NON_COMPLIANT_QUALITY',
  BILLING_ISSUE: 'BILLING_ISSUE',
  DOCUMENTATION_PROBLEM: 'DOCUMENTATION_PROBLEM',
  CUSTOMER_SERVICE: 'CUSTOMER_SERVICE',
  OTHER: 'OTHER',
} as const;

export type CreateClaimDtoStatus = typeof CreateClaimDtoStatus[keyof typeof CreateClaimDtoStatus];


export const CreateClaimDtoStatus = {
  NEW: 'NEW',
  IN_PROGRESS: 'IN_PROGRESS',
  AWAITING_INFO: 'AWAITING_INFO',
  IN_TREATMENT: 'IN_TREATMENT',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
  REJECTED: 'REJECTED',
  SENT_TO_DTM: 'SENT_TO_DTM',
} as const;

export type CreateClaimDtoPriority = typeof CreateClaimDtoPriority[keyof typeof CreateClaimDtoPriority];


export const CreateClaimDtoPriority = {
  low: 'low',
  medium: 'medium',
  high: 'high',
  urgent: 'urgent',
} as const;

export interface CreateClaimDto {
  customerId: number;
  userId?: number;
  orderId?: number;
  operationId?: string;
  type: CreateClaimDtoType;
  status?: CreateClaimDtoStatus;
  priority?: CreateClaimDtoPriority;
  description: string;
  /** @maxLength 1000 */
  resolution?: string;
}

export type ClaimDetailDtoClaimStatus = {
  id: string;
  name: string;
};

export type ClaimDetailDtoClaimCommentsItem = {
  id: number;
  createdAt: string;
  comment: string;
  claimId: number;
  authorUserId: number;
};

export type ClaimDetailDtoCustomer = {
  id: number;
  companyName: string;
};

export type ClaimDetailDtoClaimStatusHistoriesItem = {
  id: number;
  statusId: string;
  changedAt: string;
  /** @nullable */
  comment: string | null;
  changedByUserId: number;
  claimId: number;
};

export type ClaimDetailDtoCreatedByUser = {
  id: number;
  lastName: string;
  firstName: string;
};

export type ClaimDetailDtoOrder = {
  id: number;
  orderNumber: string;
};

export type ClaimDetailDtoAccessoryOperation = {
  id: string;
  name: string;
};

export type ClaimDetailDtoClaimType = {
  id: string;
  name: string;
};

export type ClaimDetailDtoClosedByUser = {
  id: number;
  lastName: string;
  firstName: string;
};

export interface ClaimDetailDto {
  id: number;
  customerId: number;
  createdByUserId: number;
  /** @nullable */
  orderId: number | null;
  /** @nullable */
  operationId: string | null;
  typeId: string;
  statusId: string;
  /** @nullable */
  priority: string | null;
  description: string;
  /** @nullable */
  resolution: string | null;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  closedByUserId: number | null;
  /** @nullable */
  closedAt: string | null;
  claimStatus: ClaimDetailDtoClaimStatus;
  claimComments: ClaimDetailDtoClaimCommentsItem[];
  customer: ClaimDetailDtoCustomer;
  claimStatusHistories: ClaimDetailDtoClaimStatusHistoriesItem[];
  createdByUser: ClaimDetailDtoCreatedByUser;
  order: ClaimDetailDtoOrder;
  accessoryOperation: ClaimDetailDtoAccessoryOperation;
  claimType: ClaimDetailDtoClaimType;
  closedByUser: ClaimDetailDtoClosedByUser;
}

export type ClaimListDtoClaimStatus = {
  id: string;
  name: string;
};

export type ClaimListDtoCustomer = {
  id: number;
  companyName: string;
};

export type ClaimListDtoCreatedByUser = {
  id: number;
  lastName: string;
  firstName: string;
};

export type ClaimListDtoOrder = {
  id: number;
  orderNumber: string;
};

export type ClaimListDtoAccessoryOperation = {
  id: string;
  name: string;
};

export type ClaimListDtoClaimType = {
  id: string;
  name: string;
};

export interface ClaimListDto {
  id: number;
  description: string;
  createdAt: string;
  updatedAt: string;
  typeId: string;
  customerId: number;
  createdByUserId: number;
  statusId: string;
  /** @nullable */
  orderId: number | null;
  /** @nullable */
  operationId: string | null;
  /** @nullable */
  priority: string | null;
  /** @nullable */
  resolution: string | null;
  /** @nullable */
  closedByUserId: number | null;
  /** @nullable */
  closedAt: string | null;
  claimStatus: ClaimListDtoClaimStatus;
  customer: ClaimListDtoCustomer;
  createdByUser: ClaimListDtoCreatedByUser;
  order: ClaimListDtoOrder;
  accessoryOperation: ClaimListDtoAccessoryOperation;
  claimType: ClaimListDtoClaimType;
}

export type UpdateClaimDtoType = typeof UpdateClaimDtoType[keyof typeof UpdateClaimDtoType];


export const UpdateClaimDtoType = {
  DELIVERY_DELAY: 'DELIVERY_DELAY',
  DAMAGED_GOODS: 'DAMAGED_GOODS',
  INCORRECT_QUANTITY: 'INCORRECT_QUANTITY',
  NON_COMPLIANT_QUALITY: 'NON_COMPLIANT_QUALITY',
  BILLING_ISSUE: 'BILLING_ISSUE',
  DOCUMENTATION_PROBLEM: 'DOCUMENTATION_PROBLEM',
  CUSTOMER_SERVICE: 'CUSTOMER_SERVICE',
  OTHER: 'OTHER',
} as const;

export type UpdateClaimDtoStatus = typeof UpdateClaimDtoStatus[keyof typeof UpdateClaimDtoStatus];


export const UpdateClaimDtoStatus = {
  NEW: 'NEW',
  IN_PROGRESS: 'IN_PROGRESS',
  AWAITING_INFO: 'AWAITING_INFO',
  IN_TREATMENT: 'IN_TREATMENT',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
  REJECTED: 'REJECTED',
  SENT_TO_DTM: 'SENT_TO_DTM',
} as const;

export type UpdateClaimDtoPriority = typeof UpdateClaimDtoPriority[keyof typeof UpdateClaimDtoPriority];


export const UpdateClaimDtoPriority = {
  low: 'low',
  medium: 'medium',
  high: 'high',
  urgent: 'urgent',
} as const;

export interface UpdateClaimDto {
  customerId?: number;
  userId?: number;
  orderId?: number;
  operationId?: string;
  type?: UpdateClaimDtoType;
  status?: UpdateClaimDtoStatus;
  priority?: UpdateClaimDtoPriority;
  description?: string;
  /** @maxLength 1000 */
  resolution?: string;
}

export interface ClaimDeleteDto {
  id: number;
}

export interface CreateClaimCommentDto {
  /** @maxLength 2000 */
  content: string;
}

export interface ClaimCommentDto {
  id: number;
  claimId: number;
  authorUserId: number;
  comment: string;
  createdAt: string;
}

export interface ResolveClaimDto {
  /** @maxLength 1000 */
  resolution: string;
}

export interface RejectClaimDto {
  /** @maxLength 1000 */
  rejectionReason: string;
}

export type NotificationListDtoNotificationType = {
  id: string;
  name: string;
};

export type NotificationListDtoNotificationChannel = {
  id: string;
  name: string;
};

export interface NotificationListDto {
  id: number;
  createdAt: string;
  typeId: string;
  recipientUserId: number;
  status: string;
  channelId: string;
  title: string;
  message: string;
  /** @nullable */
  relatedEntityType: string | null;
  /** @nullable */
  relatedEntityId: number | null;
  /** @nullable */
  sentAt: string | null;
  /** @nullable */
  readAt: string | null;
  /** @nullable */
  retryCount: number | null;
  notificationType: NotificationListDtoNotificationType;
  notificationChannel: NotificationListDtoNotificationChannel;
}

export interface NotificationUnreadCountDto {
  count: number;
}

export type NotificationDetailDtoRecipientUser = {
  id: number;
  lastName: string;
  firstName: string;
};

export type NotificationDetailDtoNotificationType = {
  id: string;
  name: string;
};

export type NotificationDetailDtoNotificationChannel = {
  id: string;
  name: string;
};

export interface NotificationDetailDto {
  id: number;
  recipientUserId: number;
  typeId: string;
  channelId: string;
  title: string;
  message: string;
  /** @nullable */
  relatedEntityType: string | null;
  /** @nullable */
  relatedEntityId: number | null;
  status: string;
  /** @nullable */
  sentAt: string | null;
  /** @nullable */
  readAt: string | null;
  /** @nullable */
  errorMessage: string | null;
  /** @nullable */
  retryCount: number | null;
  createdAt: string;
  recipientUser: NotificationDetailDtoRecipientUser;
  notificationType: NotificationDetailDtoNotificationType;
  notificationChannel: NotificationDetailDtoNotificationChannel;
}

export interface ProfileDto {
  id: number;
  email: string;
  lastName: string;
  firstName: string;
  role: string;
  permissions: string[];
  /** @nullable */
  employeeId: string | null;
  /** @nullable */
  type: string | null;
  roleId: string;
  /** @nullable */
  customerId: number | null;
  /** @nullable */
  agencyId: number | null;
  createdAt: string;
  /** @nullable */
  lastLogin: string | null;
}

export interface UpdateProfileDto {
  /** @maxLength 100 */
  email?: string;
  /** @maxLength 100 */
  firstName?: string;
  /** @maxLength 100 */
  lastName?: string;
}

export interface UnitDto {
  id: string;
  name: string;
  isActive: boolean;
  createdAt: string;
}

export interface CreateUnitDto {
  name: string;
}

export interface GoodsTypeDto {
  id: string;
  name: string;
  isActive: boolean;
  createdAt: string;
}

export interface CreateGoodsTypeDto {
  name: string;
}

export interface GoodDto {
  id: number;
  name: string;
  createdAt: string;
  isActive: boolean;
  goodsTypeId: string;
  goodsCode: string;
  updatedAt: string;
}

export interface CreateGoodDto {
  name: string;
  goodsCode: string;
  goodsTypeId: string;
}

export interface AccessoryOperationDto {
  id: string;
  name: string;
  isActive: boolean;
  createdAt: string;
}

export interface CreateAccessoryOperationDto {
  name: string;
}

export interface RejectionReasonDto {
  id: string;
  name: string;
  isActive: boolean;
  createdAt: string;
}

export interface CreateRejectionReasonDto {
  name: string;
}

export type OrdersControllerFindAllParams = {
goodsId?: number;
customerId?: number;
status?: OrdersControllerFindAllStatus;
movementTypeId?: string;
startDate?: string;
endDate?: string;
/**
 * @minimum 1
 */
page?: Object;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: Object;
search?: string;
sortBy?: string;
sortOrder?: OrdersControllerFindAllSortOrder;
};

export type OrdersControllerFindAllStatus = typeof OrdersControllerFindAllStatus[keyof typeof OrdersControllerFindAllStatus];


export const OrdersControllerFindAllStatus = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  IN_PROGRESS: 'IN_PROGRESS',
  PARTIALLY_EXECUTED: 'PARTIALLY_EXECUTED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  SENT_TO_DTM: 'SENT_TO_DTM',
} as const;

export type OrdersControllerFindAllSortOrder = typeof OrdersControllerFindAllSortOrder[keyof typeof OrdersControllerFindAllSortOrder];


export const OrdersControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type OrdersControllerFindEligibleForProgramsParams = {
search?: string;
sortBy?: string;
sortOrder?: OrdersControllerFindEligibleForProgramsSortOrder;
/**
 * @minimum 1
 */
page?: Object;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: Object;
};

export type OrdersControllerFindEligibleForProgramsSortOrder = typeof OrdersControllerFindEligibleForProgramsSortOrder[keyof typeof OrdersControllerFindEligibleForProgramsSortOrder];


export const OrdersControllerFindEligibleForProgramsSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type ProgramsControllerFindAllParams = {
orderId?: number;
userId?: number;
status?: ProgramsControllerFindAllStatus;
dtmStatus?: string;
/**
 * @minimum 1
 */
page?: Object;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: Object;
search?: string;
sortBy?: string;
sortOrder?: ProgramsControllerFindAllSortOrder;
};

export type ProgramsControllerFindAllStatus = typeof ProgramsControllerFindAllStatus[keyof typeof ProgramsControllerFindAllStatus];


export const ProgramsControllerFindAllStatus = {
  DRAFT: 'DRAFT',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  SENT_TO_DTM: 'SENT_TO_DTM',
  CONFIRMED: 'CONFIRMED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export type ProgramsControllerFindAllSortOrder = typeof ProgramsControllerFindAllSortOrder[keyof typeof ProgramsControllerFindAllSortOrder];


export const ProgramsControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type CustomersControllerFindAllParams = {
typeId?: string;
isActive?: boolean;
/**
 * @minimum 1
 */
page?: Object;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: Object;
search?: string;
sortBy?: string;
sortOrder?: CustomersControllerFindAllSortOrder;
};

export type CustomersControllerFindAllSortOrder = typeof CustomersControllerFindAllSortOrder[keyof typeof CustomersControllerFindAllSortOrder];


export const CustomersControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type ClaimsControllerFindAllParams = {
customerId?: number;
userId?: number;
orderId?: number;
operationId?: string;
type?: ClaimsControllerFindAllType;
status?: ClaimsControllerFindAllStatus;
priority?: ClaimsControllerFindAllPriority;
/**
 * @minimum 1
 */
page?: Object;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: Object;
search?: string;
sortBy?: string;
sortOrder?: ClaimsControllerFindAllSortOrder;
};

export type ClaimsControllerFindAllType = typeof ClaimsControllerFindAllType[keyof typeof ClaimsControllerFindAllType];


export const ClaimsControllerFindAllType = {
  DELIVERY_DELAY: 'DELIVERY_DELAY',
  DAMAGED_GOODS: 'DAMAGED_GOODS',
  INCORRECT_QUANTITY: 'INCORRECT_QUANTITY',
  NON_COMPLIANT_QUALITY: 'NON_COMPLIANT_QUALITY',
  BILLING_ISSUE: 'BILLING_ISSUE',
  DOCUMENTATION_PROBLEM: 'DOCUMENTATION_PROBLEM',
  CUSTOMER_SERVICE: 'CUSTOMER_SERVICE',
  OTHER: 'OTHER',
} as const;

export type ClaimsControllerFindAllStatus = typeof ClaimsControllerFindAllStatus[keyof typeof ClaimsControllerFindAllStatus];


export const ClaimsControllerFindAllStatus = {
  NEW: 'NEW',
  IN_PROGRESS: 'IN_PROGRESS',
  AWAITING_INFO: 'AWAITING_INFO',
  IN_TREATMENT: 'IN_TREATMENT',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
  REJECTED: 'REJECTED',
  SENT_TO_DTM: 'SENT_TO_DTM',
} as const;

export type ClaimsControllerFindAllPriority = typeof ClaimsControllerFindAllPriority[keyof typeof ClaimsControllerFindAllPriority];


export const ClaimsControllerFindAllPriority = {
  low: 'low',
  medium: 'medium',
  high: 'high',
  urgent: 'urgent',
} as const;

export type ClaimsControllerFindAllSortOrder = typeof ClaimsControllerFindAllSortOrder[keyof typeof ClaimsControllerFindAllSortOrder];


export const ClaimsControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

