/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ONCF ECommand API
 * ONCF freight order management
 * OpenAPI spec version: 1.0
 */
export type RegistrationStatus = typeof RegistrationStatus[keyof typeof RegistrationStatus];


export const RegistrationStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;

export type UserListDtoRole = {
  id: string;
  name: string;
};

export type UserListDtoUserCustomersItem = {
  customerId: number;
};

export interface UserListDto {
  registrationStatus: RegistrationStatus;
  id: number;
  email: string;
  lastName: string;
  firstName: string;
  /** @nullable */
  employeeCode: string | null;
  /** @nullable */
  type: string | null;
  roleId: string;
  role: UserListDtoRole;
  /** @nullable */
  customerId: number | null;
  userCustomers: UserListDtoUserCustomersItem[];
  /** @nullable */
  agencyId: number | null;
  createdAt: string;
  updatedAt: string;
  isActive: boolean;
  /** @nullable */
  lastLogin: string | null;
}

export type ApiErrorCode = typeof ApiErrorCode[keyof typeof ApiErrorCode];


export const ApiErrorCode = {
  CUSTOMER_TYPE_NOT_FOUND: 'CUSTOMER_TYPE_NOT_FOUND',
  AGENCY_NOT_FOUND: 'AGENCY_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  GOODS_TYPE_NOT_FOUND: 'GOODS_TYPE_NOT_FOUND',
  GOODS_NOT_FOUND: 'GOODS_NOT_FOUND',
  STATION_NOT_FOUND: 'STATION_NOT_FOUND',
  PORT_NOT_FOUND: 'PORT_NOT_FOUND',
  BERTH_NOT_FOUND: 'BERTH_NOT_FOUND',
  SIDING_NOT_FOUND: 'SIDING_NOT_FOUND',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_STATUS_NOT_FOUND: 'ORDER_STATUS_NOT_FOUND',
  MOVEMENT_TYPE_NOT_FOUND: 'MOVEMENT_TYPE_NOT_FOUND',
  UNIT_NOT_FOUND: 'UNIT_NOT_FOUND',
  PICKUP_LOCATION_TYPE_NOT_FOUND: 'PICKUP_LOCATION_TYPE_NOT_FOUND',
  DISPATCH_TYPE_NOT_FOUND: 'DISPATCH_TYPE_NOT_FOUND',
  PROGRAM_STATUS_NOT_FOUND: 'PROGRAM_STATUS_NOT_FOUND',
  FORECAST_PROGRAM_NOT_FOUND: 'FORECAST_PROGRAM_NOT_FOUND',
  ATTRIBUTE_NOT_FOUND: 'ATTRIBUTE_NOT_FOUND',
  ACCESSORY_OPERATION_NOT_FOUND: 'ACCESSORY_OPERATION_NOT_FOUND',
  REJECTION_REASON_NOT_FOUND: 'REJECTION_REASON_NOT_FOUND',
  CLAIM_NOT_FOUND: 'CLAIM_NOT_FOUND',
  CLAIM_TYPE_NOT_FOUND: 'CLAIM_TYPE_NOT_FOUND',
  CLAIM_STATUS_NOT_FOUND: 'CLAIM_STATUS_NOT_FOUND',
  TRAIN_NOT_FOUND: 'TRAIN_NOT_FOUND',
  WAGON_NOT_FOUND: 'WAGON_NOT_FOUND',
  NOTIFICATION_TYPE_NOT_FOUND: 'NOTIFICATION_TYPE_NOT_FOUND',
  NOTIFICATION_CHANNEL_NOT_FOUND: 'NOTIFICATION_CHANNEL_NOT_FOUND',
  DTM_REQUEST_TYPE_NOT_FOUND: 'DTM_REQUEST_TYPE_NOT_FOUND',
  PARENT_ORDER_NOT_FOUND: 'PARENT_ORDER_NOT_FOUND',
  PERMISSION_NOT_FOUND: 'PERMISSION_NOT_FOUND',
  DUPLICATE_AGENCY_NAME: 'DUPLICATE_AGENCY_NAME',
  DUPLICATE_USER_EMAIL: 'DUPLICATE_USER_EMAIL',
  DUPLICATE_USER_EMPLOYEE_CODE: 'DUPLICATE_USER_EMPLOYEE_CODE',
  DUPLICATE_CUSTOMER_CODE: 'DUPLICATE_CUSTOMER_CODE',
  DUPLICATE_CUSTOMER_TYPE_NAME: 'DUPLICATE_CUSTOMER_TYPE_NAME',
  DUPLICATE_ROLE_NAME: 'DUPLICATE_ROLE_NAME',
  DUPLICATE_PERMISSION_NAME: 'DUPLICATE_PERMISSION_NAME',
  DUPLICATE_GOODS_TYPE_NAME: 'DUPLICATE_GOODS_TYPE_NAME',
  DUPLICATE_GOODS_CODE: 'DUPLICATE_GOODS_CODE',
  DUPLICATE_STATION_NAME: 'DUPLICATE_STATION_NAME',
  DUPLICATE_STATION_CODE: 'DUPLICATE_STATION_CODE',
  DUPLICATE_PORT_NAME: 'DUPLICATE_PORT_NAME',
  DUPLICATE_SIDING_NAME: 'DUPLICATE_SIDING_NAME',
  DUPLICATE_ATTRIBUTE_NAME: 'DUPLICATE_ATTRIBUTE_NAME',
  DUPLICATE_ORDER_NUMBER: 'DUPLICATE_ORDER_NUMBER',
  DUPLICATE_ORDER_STATUS_NAME: 'DUPLICATE_ORDER_STATUS_NAME',
  DUPLICATE_MOVEMENT_TYPE_NAME: 'DUPLICATE_MOVEMENT_TYPE_NAME',
  DUPLICATE_UNIT_NAME: 'DUPLICATE_UNIT_NAME',
  DUPLICATE_PICKUP_LOCATION_TYPE_NAME: 'DUPLICATE_PICKUP_LOCATION_TYPE_NAME',
  DUPLICATE_DISPATCH_TYPE_NAME: 'DUPLICATE_DISPATCH_TYPE_NAME',
  DUPLICATE_PROGRAM_STATUS_NAME: 'DUPLICATE_PROGRAM_STATUS_NAME',
  DUPLICATE_PROGRAM_NUMBER: 'DUPLICATE_PROGRAM_NUMBER',
  DUPLICATE_ACCESSORY_OPERATION_NAME: 'DUPLICATE_ACCESSORY_OPERATION_NAME',
  DUPLICATE_REJECTION_REASON_NAME: 'DUPLICATE_REJECTION_REASON_NAME',
  DUPLICATE_SHIPPING_COMPANY_NAME: 'DUPLICATE_SHIPPING_COMPANY_NAME',
  DUPLICATE_VESSEL_NAME: 'DUPLICATE_VESSEL_NAME',
  DUPLICATE_IMPORTER_NAME: 'DUPLICATE_IMPORTER_NAME',
  DUPLICATE_REPRESENTATIVE_NAME: 'DUPLICATE_REPRESENTATIVE_NAME',
  DUPLICATE_CLAIM_TYPE_NAME: 'DUPLICATE_CLAIM_TYPE_NAME',
  DUPLICATE_CLAIM_STATUS_NAME: 'DUPLICATE_CLAIM_STATUS_NAME',
  DUPLICATE_TRAIN_NUMBER: 'DUPLICATE_TRAIN_NUMBER',
  DUPLICATE_TRAIN_EXTERNAL_ID: 'DUPLICATE_TRAIN_EXTERNAL_ID',
  DUPLICATE_WAGON_NUMBER: 'DUPLICATE_WAGON_NUMBER',
  DUPLICATE_WAGON_EXTERNAL_ID: 'DUPLICATE_WAGON_EXTERNAL_ID',
  DUPLICATE_NOTIFICATION_TYPE_NAME: 'DUPLICATE_NOTIFICATION_TYPE_NAME',
  DUPLICATE_NOTIFICATION_CHANNEL_NAME: 'DUPLICATE_NOTIFICATION_CHANNEL_NAME',
  DUPLICATE_DTM_REQUEST_TYPE_NAME: 'DUPLICATE_DTM_REQUEST_TYPE_NAME',
  DUPLICATE_PASSWORD_RESET_TOKEN: 'DUPLICATE_PASSWORD_RESET_TOKEN',
  DUPLICATE_SESSION_TOKEN: 'DUPLICATE_SESSION_TOKEN',
  DUPLICATE_ORDER_ATTRIBUTE: 'DUPLICATE_ORDER_ATTRIBUTE',
  DUPLICATE_PARAMETRIZATION: 'DUPLICATE_PARAMETRIZATION',
  DUPLICATE_CUSTOMER_PARAMETRIZATION: 'DUPLICATE_CUSTOMER_PARAMETRIZATION',
  DUPLICATE_ORDER_SHARE: 'DUPLICATE_ORDER_SHARE',
  DUPLICATE_PROGRAM_CONVOI: 'DUPLICATE_PROGRAM_CONVOI',
  ACCOUNT_REGISTRATION_NOT_PENDING: 'ACCOUNT_REGISTRATION_NOT_PENDING',
  ACCESS_DENIED: 'ACCESS_DENIED',
  CLAIM_COMMENT_NOT_FOUND: 'CLAIM_COMMENT_NOT_FOUND',
  CLAIM_ORDER_CUSTOMER_MISMATCH: 'CLAIM_ORDER_CUSTOMER_MISMATCH',
  CLAIM_RESOLUTION_REQUIRED: 'CLAIM_RESOLUTION_REQUIRED',
  CLAIM_TRANSITION_INVALID: 'CLAIM_TRANSITION_INVALID',
  CATALOG_GOODS_TYPE_HAS_ACTIVE_GOODS: 'CATALOG_GOODS_TYPE_HAS_ACTIVE_GOODS',
  CATALOG_GOODS_TYPE_INACTIVE: 'CATALOG_GOODS_TYPE_INACTIVE',
  CURRENT_PASSWORD_INVALID: 'CURRENT_PASSWORD_INVALID',
  CUSTOMER_IDENTITY_INVALID: 'CUSTOMER_IDENTITY_INVALID',
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_IDENTIFIER: 'INVALID_IDENTIFIER',
  LAST_ACTIVE_ADMIN: 'LAST_ACTIVE_ADMIN',
  ORDER_ALREADY_PROGRAMMED: 'ORDER_ALREADY_PROGRAMMED',
  ORDER_DATE_RANGE_INVALID: 'ORDER_DATE_RANGE_INVALID',
  ORDER_MUST_BE_DRAFT: 'ORDER_MUST_BE_DRAFT',
  ORDER_NOT_ELIGIBLE_FOR_PROGRAM: 'ORDER_NOT_ELIGIBLE_FOR_PROGRAM',
  ORDER_QUANTITY_INVALID: 'ORDER_QUANTITY_INVALID',
  ORDER_TRANSITION_INVALID: 'ORDER_TRANSITION_INVALID',
  ORDER_UPDATE_CONFLICT: 'ORDER_UPDATE_CONFLICT',
  PROGRAM_MUST_BE_DRAFT: 'PROGRAM_MUST_BE_DRAFT',
  PROGRAM_NOT_FOUND: 'PROGRAM_NOT_FOUND',
  PROGRAM_TRANSITION_INVALID: 'PROGRAM_TRANSITION_INVALID',
  RATE_LIMITED: 'RATE_LIMITED',
  REQUEST_FAILED: 'REQUEST_FAILED',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  ROLE_PERMISSION_UNAVAILABLE: 'ROLE_PERMISSION_UNAVAILABLE',
  ROLE_PROFILE_IN_USE: 'ROLE_PROFILE_IN_USE',
  RESET_TOKEN_EXPIRED: 'RESET_TOKEN_EXPIRED',
  RESET_TOKEN_INVALID: 'RESET_TOKEN_INVALID',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  USER_EMAIL_ALREADY_EXISTS: 'USER_EMAIL_ALREADY_EXISTS',
  USER_ROLE_NOT_FOUND: 'USER_ROLE_NOT_FOUND',
  CUSTOMER_ASSIGNMENT_REQUIRED: 'CUSTOMER_ASSIGNMENT_REQUIRED',
  CUSTOMER_OUTSIDE_PORTFOLIO: 'CUSTOMER_OUTSIDE_PORTFOLIO',
  TRACKED_TRAIN_NOT_FOUND: 'TRACKED_TRAIN_NOT_FOUND',
  TRACKED_WAGON_NOT_FOUND: 'TRACKED_WAGON_NOT_FOUND',
  ATTACHMENT_NOT_FOUND: 'ATTACHMENT_NOT_FOUND',
  ORDER_FILE_NOT_FOUND: 'ORDER_FILE_NOT_FOUND',
  REPORT_DATE_INVALID: 'REPORT_DATE_INVALID',
  REPORT_DATE_RANGE_INVALID: 'REPORT_DATE_RANGE_INVALID',
  ORDER_CUSTOMER_REQUIRED: 'ORDER_CUSTOMER_REQUIRED',
  ORDER_CUSTOMER_ACCESS_DENIED: 'ORDER_CUSTOMER_ACCESS_DENIED',
  ORDER_STATUS_CHANGE_FORBIDDEN: 'ORDER_STATUS_CHANGE_FORBIDDEN',
  ORDER_OWNERSHIP_CHANGE_FORBIDDEN: 'ORDER_OWNERSHIP_CHANGE_FORBIDDEN',
  PROGRAM_CUSTOMER_ACCESS_DENIED: 'PROGRAM_CUSTOMER_ACCESS_DENIED',
  PROGRAM_OWNERSHIP_CHANGE_FORBIDDEN: 'PROGRAM_OWNERSHIP_CHANGE_FORBIDDEN',
  PROGRAM_STATUS_CHANGE_FORBIDDEN: 'PROGRAM_STATUS_CHANGE_FORBIDDEN',
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
} as const;

export type ApiErrorDetailsDtoFieldsItem = typeof ApiErrorDetailsDtoFieldsItem[keyof typeof ApiErrorDetailsDtoFieldsItem];


export const ApiErrorDetailsDtoFieldsItem = {
  ARRAY_UNIQUE: 'ARRAY_UNIQUE',
  IS_ARRAY: 'IS_ARRAY',
  IS_BOOLEAN: 'IS_BOOLEAN',
  IS_DATE_STRING: 'IS_DATE_STRING',
  IS_EMAIL: 'IS_EMAIL',
  IS_ENUM: 'IS_ENUM',
  IS_IN: 'IS_IN',
  IS_INT: 'IS_INT',
  IS_NOT_EMPTY: 'IS_NOT_EMPTY',
  IS_NUMBER: 'IS_NUMBER',
  IS_NUMBER_STRING: 'IS_NUMBER_STRING',
  IS_OBJECT: 'IS_OBJECT',
  IS_STRING: 'IS_STRING',
  IS_UUID: 'IS_UUID',
  MATCHES: 'MATCHES',
  MAX: 'MAX',
  MAX_LENGTH: 'MAX_LENGTH',
  MIN: 'MIN',
  MIN_LENGTH: 'MIN_LENGTH',
  UNKNOWN: 'UNKNOWN',
} as const;

export type ApiErrorDetailsDtoFields = {[key: string]: ApiErrorDetailsDtoFieldsItem[]};

export interface ApiErrorDetailsDto {
  fields?: ApiErrorDetailsDtoFields;
  permissions?: string[];
}

export interface ApiErrorResponseDto {
  code: ApiErrorCode;
  /**
     * @minimum 400
     * @maximum 599
     */
  statusCode: number;
  details?: ApiErrorDetailsDto;
}

export type UserDetailDtoRole = {
  id: string;
  name: string;
};

export type UserDetailDtoUserCustomersItem = {
  customerId: number;
};

export interface UserDetailDto {
  registrationStatus: RegistrationStatus;
  id: number;
  email: string;
  lastName: string;
  firstName: string;
  /** @nullable */
  employeeCode: string | null;
  /** @nullable */
  type: string | null;
  roleId: string;
  role: UserDetailDtoRole;
  /** @nullable */
  customerId: number | null;
  userCustomers: UserDetailDtoUserCustomersItem[];
  /** @nullable */
  agencyId: number | null;
  createdAt: string;
  updatedAt: string;
  isActive: boolean;
  /** @nullable */
  lastLogin: string | null;
}

export type CreateUserDtoRole = typeof CreateUserDtoRole[keyof typeof CreateUserDtoRole];


export const CreateUserDtoRole = {
  ADMIN: 'ADMIN',
  AGENT_COMMERCIAL: 'AGENT_COMMERCIAL',
  CLIENT_REPRESENTATIVE: 'CLIENT_REPRESENTATIVE',
} as const;

/**
 * @maxLength 20
 */
export type CreateUserDtoType = typeof CreateUserDtoType[keyof typeof CreateUserDtoType];


export const CreateUserDtoType = {
  internal: 'internal',
  external: 'external',
} as const;

export interface CreateUserDto {
  /** @maxLength 100 */
  email: string;
  /**
     * @minLength 8
     * @maxLength 255
     */
  password: string;
  /** @maxLength 100 */
  firstName: string;
  /** @maxLength 100 */
  lastName: string;
  role?: CreateUserDtoRole;
  roleId?: string;
  /** @maxLength 50 */
  employeeCode?: string;
  /** @maxLength 20 */
  type?: CreateUserDtoType;
  /** @minimum 1 */
  customerId?: number;
  /** @items.minimum 1 */
  customerIds?: number[];
  agencyId?: number;
  isActive?: boolean;
}

export type UpdateUserDtoRole = typeof UpdateUserDtoRole[keyof typeof UpdateUserDtoRole];


export const UpdateUserDtoRole = {
  ADMIN: 'ADMIN',
  AGENT_COMMERCIAL: 'AGENT_COMMERCIAL',
  CLIENT_REPRESENTATIVE: 'CLIENT_REPRESENTATIVE',
} as const;

/**
 * @maxLength 20
 */
export type UpdateUserDtoType = typeof UpdateUserDtoType[keyof typeof UpdateUserDtoType];


export const UpdateUserDtoType = {
  internal: 'internal',
  external: 'external',
} as const;

export interface UpdateUserDto {
  /** @maxLength 100 */
  email?: string;
  /** @maxLength 100 */
  firstName?: string;
  /** @maxLength 100 */
  lastName?: string;
  role?: UpdateUserDtoRole;
  roleId?: string;
  /** @maxLength 50 */
  employeeCode?: string;
  /** @maxLength 20 */
  type?: UpdateUserDtoType;
  /** @minimum 1 */
  customerId?: number;
  /** @items.minimum 1 */
  customerIds?: number[];
  agencyId?: number;
  isActive?: boolean;
}

export type ReviewUserRegistrationDtoStatus = typeof ReviewUserRegistrationDtoStatus[keyof typeof ReviewUserRegistrationDtoStatus];


export const ReviewUserRegistrationDtoStatus = {
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;

export interface ReviewUserRegistrationDto {
  status: ReviewUserRegistrationDtoStatus;
}

export interface UserDeleteDto {
  id: number;
}

export interface LoginDto {
  /**
     * @minLength 1
     * @maxLength 100
     * @pattern \S
     */
  username: string;
  /** @minLength 8 */
  password: string;
}

export interface LoginDetailDto {
  access_token: string;
}

export interface RegisterClientDto {
  /** @pattern ^\d{15}$ */
  ice: string;
  /** @maxLength 100 */
  email: string;
  /** @maxLength 255 */
  password: string;
  /**
     * @minLength 1
     * @maxLength 100
     */
  firstName: string;
  /**
     * @minLength 1
     * @maxLength 100
     */
  lastName: string;
  /**
     * @minLength 1
     * @maxLength 50
     */
  customerCode: string;
}

export type RegistrationSubmittedDtoCode = typeof RegistrationSubmittedDtoCode[keyof typeof RegistrationSubmittedDtoCode];


export const RegistrationSubmittedDtoCode = {
  REGISTRATION_SUBMITTED_FOR_REVIEW: 'REGISTRATION_SUBMITTED_FOR_REVIEW',
} as const;

export interface RegistrationSubmittedDto {
  code: RegistrationSubmittedDtoCode;
}

export interface ChangePasswordDto {
  currentPassword: string;
  newPassword: string;
}

export type SuccessResponseDtoCode = typeof SuccessResponseDtoCode[keyof typeof SuccessResponseDtoCode];


export const SuccessResponseDtoCode = {
  AUTH_LOGGED_OUT: 'AUTH_LOGGED_OUT',
  AUTH_PASSWORD_CHANGED: 'AUTH_PASSWORD_CHANGED',
  AUTH_PASSWORD_RESET: 'AUTH_PASSWORD_RESET',
  AUTH_PASSWORD_RESET_REQUEST_ACCEPTED: 'AUTH_PASSWORD_RESET_REQUEST_ACCEPTED',
  NOTIFICATIONS_MARKED_READ: 'NOTIFICATIONS_MARKED_READ',
  ORDER_ATTACHMENT_DELETED: 'ORDER_ATTACHMENT_DELETED',
  REGISTRATION_SUBMITTED_FOR_REVIEW: 'REGISTRATION_SUBMITTED_FOR_REVIEW',
} as const;

export interface SuccessResponseDto {
  code: SuccessResponseDtoCode;
}

export interface ForgotPasswordDto {
  email: string;
}

export interface ResetPasswordDto {
  token: string;
  newPassword: string;
}

export interface CustomerPortfolioOptionDto {
  id: number;
  companyName: string;
  /** @nullable */
  customerCode: string | null;
}

export interface CustomerTypeReferenceDto {
  name: string;
}

export interface CustomerListDto {
  id: number;
  createdAt: string;
  isActive: boolean;
  updatedAt: string;
  companyName: string;
  /** @nullable */
  address: string | null;
  /** @nullable */
  city: string | null;
  /** @nullable */
  phone: string | null;
  /** @nullable */
  email: string | null;
  /** @nullable */
  typeId: string | null;
  /** @nullable */
  customerType: CustomerTypeReferenceDto | null;
  /** @nullable */
  customerCode: string | null;
  /** @nullable */
  ice: string | null;
}

export interface CustomerDetailDto {
  id: number;
  companyName: string;
  /** @nullable */
  address: string | null;
  /** @nullable */
  city: string | null;
  /** @nullable */
  phone: string | null;
  /** @nullable */
  email: string | null;
  /** @nullable */
  typeId: string | null;
  /** @nullable */
  customerType: CustomerTypeReferenceDto | null;
  createdAt: string;
  updatedAt: string;
  isActive: boolean;
  /** @nullable */
  customerCode: string | null;
  /** @nullable */
  ice: string | null;
}

export interface CreateCustomerDto {
  /** @pattern ^\d{15}$ */
  ice?: string;
  /** @maxLength 300 */
  companyName: string;
  /** @maxLength 500 */
  address?: string;
  /** @maxLength 100 */
  city?: string;
  /** @maxLength 20 */
  phone?: string;
  /** @maxLength 100 */
  email?: string;
  typeId?: string;
  /** @maxLength 50 */
  customerCode?: string;
  isActive?: boolean;
}

export interface UpdateCustomerDto {
  /** @pattern ^\d{15}$ */
  ice?: string;
  /** @maxLength 300 */
  companyName?: string;
  /** @maxLength 500 */
  address?: string;
  /** @maxLength 100 */
  city?: string;
  /** @maxLength 20 */
  phone?: string;
  /** @maxLength 100 */
  email?: string;
  typeId?: string;
  /** @maxLength 50 */
  customerCode?: string;
  isActive?: boolean;
}

export interface CustomerDeleteDto {
  id: number;
}

export type CreateOrderDtoStatus = typeof CreateOrderDtoStatus[keyof typeof CreateOrderDtoStatus];


export const CreateOrderDtoStatus = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  IN_PROGRESS: 'IN_PROGRESS',
  PARTIALLY_EXECUTED: 'PARTIALLY_EXECUTED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  SENT_TO_DTM: 'SENT_TO_DTM',
} as const;

export interface CreateOrderDto {
  goodsId: number;
  customerId: number;
  status?: CreateOrderDtoStatus;
  /** @maxLength 200 */
  supervisor?: string;
  movementTypeId?: string;
  parentOrderId?: number;
  quantityDemanded: string;
  quantityAchieved?: string;
  unitId: string;
  departureStationId?: number;
  debtorCustomerId?: number;
  pickupLocationTypeId?: string;
  dispatchTypeId?: string;
  destinationCustomerId?: number;
  arrivalStationId?: number;
  deliveryLocationTypeId?: string;
  pickupPortId?: number;
  pickupBerthId?: number;
  pickupSidingId?: number;
  deliveryPortId?: number;
  deliveryBerthId?: number;
  deliverySidingId?: number;
  remarks?: string;
  orderDate?: string;
  startDate?: string;
  endDate?: string;
}

export type OrderDetailDtoOrderStatus = {
  id: string;
  name: string;
};

export type OrderDetailDtoForecastProgramsItem = {
  id: number;
  createdByUserId: number;
  statusId: string;
  createdAt: string;
  updatedAt: string;
  orderId: number;
  programNumber: string;
  plannedDate: string;
  quantityPlanned: string;
  /** @nullable */
  quantityRealized: string | null;
  /** @nullable */
  deviationReason: string | null;
  /** @nullable */
  realizedAt: string | null;
  /** @nullable */
  realizedByUserId: number | null;
  /** @nullable */
  sentToDtmAt: string | null;
  /** @nullable */
  dtmStatus: string | null;
};

export type OrderDetailDtoOrderExecutionsItem = {
  id: number;
  createdAt: string;
  orderId: number;
  /** @nullable */
  comment: string | null;
  /** @nullable */
  completionRate: string | null;
  executionDate: string;
  quantityExecuted: string;
  executedByUserId: number;
};

export type OrderDetailDtoOrderFilesItemAttachment = {
  fileSize?: number;
  mimeType?: string;
};

export type OrderDetailDtoOrderFilesItem = {
  id: number;
  /** @nullable */
  description: string | null;
  orderId: number;
  fileName: string;
  uploadedByUserId: number;
  uploadedAt: string;
  attachment: OrderDetailDtoOrderFilesItemAttachment;
};

export type OrderDetailDtoClaimsItem = {
  id: number;
  claimNumber: string;
  customerId: number;
  createdByUserId: number;
  statusId: string;
  createdAt: string;
  updatedAt: string;
  typeId: string;
  description: string;
  /** @nullable */
  orderId: number | null;
  /** @nullable */
  operationId: string | null;
  /** @nullable */
  priority: string | null;
  /** @nullable */
  resolution: string | null;
  /** @nullable */
  closedByUserId: number | null;
  /** @nullable */
  closedAt: string | null;
};

export type OrderDetailDtoUnit = {
  name: string;
};

export type OrderDetailDtoCustomer = {
  id: number;
  companyName: string;
};

export type OrderDetailDtoOrderStatusHistoriesItem = {
  id: number;
  statusId: string;
  orderId: number;
  changedById: number;
  changedAt: string;
  /** @nullable */
  comment: string | null;
  /** @nullable */
  rejectionReasonId: string | null;
};

export type OrderDetailDtoGood = {
  id: number;
  name: string;
};

export type OrderDetailDtoCreatedByUser = {
  id: number;
  lastName: string;
  firstName: string;
};

export interface OrderDetailDto {
  id: number;
  goodsId: number;
  customerId: number;
  createdByUserId: number;
  statusId: string;
  /** @nullable */
  supervisor: string | null;
  orderNumber: string;
  /** @nullable */
  movementTypeId: string | null;
  /** @nullable */
  parentOrderId: number | null;
  quantityDemanded: string;
  /** @nullable */
  quantityAchieved: string | null;
  unitId: string;
  /** @nullable */
  departureStationId: number | null;
  /** @nullable */
  debtorCustomerId: number | null;
  /** @nullable */
  pickupLocationTypeId: string | null;
  /** @nullable */
  dispatchTypeId: string | null;
  /** @nullable */
  destinationCustomerId: number | null;
  /** @nullable */
  arrivalStationId: number | null;
  /** @nullable */
  deliveryLocationTypeId: string | null;
  /** @nullable */
  pickupPortId: number | null;
  /** @nullable */
  pickupBerthId: number | null;
  /** @nullable */
  pickupSidingId: number | null;
  /** @nullable */
  deliveryPortId: number | null;
  /** @nullable */
  deliveryBerthId: number | null;
  /** @nullable */
  deliverySidingId: number | null;
  /** @nullable */
  remarks: string | null;
  orderDate: string;
  /** @nullable */
  startDate: string | null;
  /** @nullable */
  endDate: string | null;
  createdAt: string;
  updatedAt: string;
  orderStatus: OrderDetailDtoOrderStatus;
  forecastPrograms: OrderDetailDtoForecastProgramsItem[];
  orderExecutions: OrderDetailDtoOrderExecutionsItem[];
  orderFiles: OrderDetailDtoOrderFilesItem[];
  claims: OrderDetailDtoClaimsItem[];
  unit: OrderDetailDtoUnit;
  customer: OrderDetailDtoCustomer;
  orderStatusHistories: OrderDetailDtoOrderStatusHistoriesItem[];
  good: OrderDetailDtoGood;
  createdByUser: OrderDetailDtoCreatedByUser;
}

export type OrderListDtoOrderStatus = {
  id: string;
  name: string;
};

export type OrderListDtoUnit = {
  name: string;
};

export type OrderListDtoCustomer = {
  id: number;
  companyName: string;
};

export type OrderListDtoGood = {
  id: number;
  name: string;
};

export type OrderListDtoCreatedByUser = {
  id: number;
  lastName: string;
  firstName: string;
};

export interface OrderListDto {
  id: number;
  createdAt: string;
  orderNumber: string;
  quantityDemanded: string;
  /** @nullable */
  quantityAchieved: string | null;
  orderDate: string;
  /** @nullable */
  startDate: string | null;
  /** @nullable */
  endDate: string | null;
  orderStatus: OrderListDtoOrderStatus;
  unit: OrderListDtoUnit;
  customer: OrderListDtoCustomer;
  good: OrderListDtoGood;
  createdByUser: OrderListDtoCreatedByUser;
}

export interface EligibleOrderForProgramDto {
  id: number;
  orderNumber: string;
  quantityDemanded: string;
}

export type UpdateOrderDtoStatus = typeof UpdateOrderDtoStatus[keyof typeof UpdateOrderDtoStatus];


export const UpdateOrderDtoStatus = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  IN_PROGRESS: 'IN_PROGRESS',
  PARTIALLY_EXECUTED: 'PARTIALLY_EXECUTED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  SENT_TO_DTM: 'SENT_TO_DTM',
} as const;

export interface UpdateOrderDto {
  goodsId?: number;
  customerId?: number;
  status?: UpdateOrderDtoStatus;
  /** @maxLength 200 */
  supervisor?: string;
  movementTypeId?: string;
  parentOrderId?: number;
  quantityDemanded?: string;
  quantityAchieved?: string;
  unitId?: string;
  departureStationId?: number;
  debtorCustomerId?: number;
  pickupLocationTypeId?: string;
  dispatchTypeId?: string;
  destinationCustomerId?: number;
  arrivalStationId?: number;
  deliveryLocationTypeId?: string;
  pickupPortId?: number;
  pickupBerthId?: number;
  pickupSidingId?: number;
  deliveryPortId?: number;
  deliveryBerthId?: number;
  deliverySidingId?: number;
  remarks?: string;
  orderDate?: string;
  startDate?: string;
  endDate?: string;
}

export interface RejectOrderDto {
  reason: string;
}

export interface OrderDeleteDto {
  id: number;
}

export interface UploadFileDto {
  description?: string;
}

export interface FileDto {
  id: number;
  orderId: number;
  fileName: string;
  /** @nullable */
  description: string | null;
  fileSize: number;
  mimeType: string;
  uploadedByUserId: number;
  uploadedAt: string;
}

export type NotificationMessageCode = typeof NotificationMessageCode[keyof typeof NotificationMessageCode];


export const NotificationMessageCode = {
  ORDER_STATUS_CHANGED: 'ORDER_STATUS_CHANGED',
  PROGRAM_STATUS_CHANGED: 'PROGRAM_STATUS_CHANGED',
  CLAIM_STATUS_CHANGED: 'CLAIM_STATUS_CHANGED',
  CLAIM_COMMENT_ADDED: 'CLAIM_COMMENT_ADDED',
  LEGACY_UPDATE: 'LEGACY_UPDATE',
} as const;

export interface NotificationTypeDto {
  id: string;
  name: string;
}

export interface NotificationChannelDto {
  id: string;
  name: string;
}

export type NotificationListDtoMessageParameters = {[key: string]: string};

export interface NotificationListDto {
  id: number;
  createdAt: string;
  typeId: string;
  recipientUserId: number;
  status: string;
  channelId: string;
  messageCode: NotificationMessageCode;
  messageParameters: NotificationListDtoMessageParameters;
  /** @nullable */
  relatedEntityType: string | null;
  /** @nullable */
  relatedEntityId: number | null;
  /** @nullable */
  sentAt: string | null;
  /** @nullable */
  readAt: string | null;
  /** @nullable */
  retryCount: number | null;
  /** @nullable */
  notificationType: NotificationTypeDto | null;
  /** @nullable */
  notificationChannel: NotificationChannelDto | null;
}

export interface NotificationUnreadCountDto {
  count: number;
}

export interface NotificationRecipientDto {
  id: number;
  lastName: string;
  firstName: string;
}

export type NotificationDetailDtoMessageParameters = {[key: string]: string};

export interface NotificationDetailDto {
  id: number;
  recipientUserId: number;
  typeId: string;
  channelId: string;
  messageCode: NotificationMessageCode;
  messageParameters: NotificationDetailDtoMessageParameters;
  /** @nullable */
  relatedEntityType: string | null;
  /** @nullable */
  relatedEntityId: number | null;
  status: string;
  /** @nullable */
  sentAt: string | null;
  /** @nullable */
  readAt: string | null;
  /** @nullable */
  retryCount: number | null;
  createdAt: string;
  /** @nullable */
  recipientUser: NotificationRecipientDto | null;
  /** @nullable */
  notificationType: NotificationTypeDto | null;
  /** @nullable */
  notificationChannel: NotificationChannelDto | null;
}

export type NotificationsMarkedReadDtoCode = typeof NotificationsMarkedReadDtoCode[keyof typeof NotificationsMarkedReadDtoCode];


export const NotificationsMarkedReadDtoCode = {
  NOTIFICATIONS_MARKED_READ: 'NOTIFICATIONS_MARKED_READ',
} as const;

export interface NotificationsMarkedReadDto {
  code: NotificationsMarkedReadDtoCode;
  count: number;
}

export type CreateProgramDtoStatus = typeof CreateProgramDtoStatus[keyof typeof CreateProgramDtoStatus];


export const CreateProgramDtoStatus = {
  DRAFT: 'DRAFT',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  SENT_TO_DTM: 'SENT_TO_DTM',
  CONFIRMED: 'CONFIRMED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export interface CreateProgramDto {
  orderId: number;
  userId?: number;
  status?: CreateProgramDtoStatus;
  plannedDate: string;
  quantityPlanned: string;
  quantityRealized?: string;
  dtmStatus?: string;
}

export type ProgramDetailDtoProgramStatus = {
  id: string;
  name: string;
};

export type ProgramDetailDtoOrderWagonsItem = {
  id: number;
  orderId: number;
  createdAt: string;
  /** @nullable */
  trainId: number | null;
  wagonId: number;
  /** @nullable */
  quantityLoaded: string | null;
  /** @nullable */
  forecastProgramId: number | null;
};

export type ProgramDetailDtoForecastProgramHistoriesItem = {
  id: number;
  /** @nullable */
  quantityRealized: string | null;
  /** @nullable */
  deviationReason: string | null;
  changedAt: string;
  /** @nullable */
  programId: number | null;
  eventType: string;
  /** @nullable */
  oldQuantity: string | null;
  /** @nullable */
  newQuantity: string | null;
  /** @nullable */
  oldStatusId: string | null;
  /** @nullable */
  newStatusId: string | null;
  /** @nullable */
  oldPlannedDate: string | null;
  /** @nullable */
  newPlannedDate: string | null;
  /** @nullable */
  completionRate: string | null;
  /** @nullable */
  changedByName: string | null;
  changedByUserId: number;
  /** @nullable */
  reason: string | null;
};

export type ProgramDetailDtoOrder = {
  id: number;
  orderNumber: string;
};

export type ProgramDetailDtoCreatedByUser = {
  id: number;
  lastName: string;
  firstName: string;
};

export type ProgramDetailDtoRealizedByUser = {
  id: number;
  lastName: string;
  firstName: string;
};

export type ProgramDetailDtoProgramConvoisItem = {
  id: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  status: string | null;
  trainId: number;
  forecastProgramId: number;
  /** @nullable */
  lastLatitude: string | null;
  /** @nullable */
  lastLongitude: string | null;
  convoy: string;
  /** @nullable */
  since: string | null;
  /** @nullable */
  quantity: string | null;
  /** @nullable */
  unit: string | null;
  /** @nullable */
  wagonCount: number | null;
  /** @nullable */
  eta: string | null;
  /** @nullable */
  delayMinutes: number | null;
};

export interface ProgramDetailDto {
  id: number;
  programNumber: string;
  orderId: number;
  statusId: string;
  plannedDate: string;
  quantityPlanned: string;
  /** @nullable */
  quantityRealized: string | null;
  /** @nullable */
  deviationReason: string | null;
  /** @nullable */
  realizedAt: string | null;
  /** @nullable */
  realizedByUserId: number | null;
  createdByUserId: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  sentToDtmAt: string | null;
  /** @nullable */
  dtmStatus: string | null;
  programStatus: ProgramDetailDtoProgramStatus;
  orderWagons: ProgramDetailDtoOrderWagonsItem[];
  forecastProgramHistories: ProgramDetailDtoForecastProgramHistoriesItem[];
  order: ProgramDetailDtoOrder;
  createdByUser: ProgramDetailDtoCreatedByUser;
  realizedByUser: ProgramDetailDtoRealizedByUser;
  programConvois: ProgramDetailDtoProgramConvoisItem[];
}

export type ProgramListDtoProgramStatus = {
  id: string;
  name: string;
};

export type ProgramListDtoOrder = {
  id: number;
  orderNumber: string;
};

export type ProgramListDtoCreatedByUser = {
  id: number;
  lastName: string;
  firstName: string;
};

export interface ProgramListDto {
  id: number;
  createdAt: string;
  /** @nullable */
  quantityRealized: string | null;
  plannedDate: string;
  quantityPlanned: string;
  /** @nullable */
  sentToDtmAt: string | null;
  programNumber: string;
  programStatus: ProgramListDtoProgramStatus;
  order: ProgramListDtoOrder;
  createdByUser: ProgramListDtoCreatedByUser;
}

export type UpdateProgramDtoStatus = typeof UpdateProgramDtoStatus[keyof typeof UpdateProgramDtoStatus];


export const UpdateProgramDtoStatus = {
  DRAFT: 'DRAFT',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  SENT_TO_DTM: 'SENT_TO_DTM',
  CONFIRMED: 'CONFIRMED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export interface UpdateProgramDto {
  orderId?: number;
  userId?: number;
  status?: UpdateProgramDtoStatus;
  plannedDate?: string;
  quantityPlanned?: string;
  quantityRealized?: string;
  dtmStatus?: string;
}

export interface ProgramDeleteDto {
  id: number;
}

export type CreateClaimDtoType = typeof CreateClaimDtoType[keyof typeof CreateClaimDtoType];


export const CreateClaimDtoType = {
  DELIVERY_DELAY: 'DELIVERY_DELAY',
  DAMAGED_GOODS: 'DAMAGED_GOODS',
  INCORRECT_QUANTITY: 'INCORRECT_QUANTITY',
  NON_COMPLIANT_QUALITY: 'NON_COMPLIANT_QUALITY',
  BILLING_ISSUE: 'BILLING_ISSUE',
  DOCUMENTATION_PROBLEM: 'DOCUMENTATION_PROBLEM',
  CUSTOMER_SERVICE: 'CUSTOMER_SERVICE',
  OTHER: 'OTHER',
} as const;

export type CreateClaimDtoStatus = typeof CreateClaimDtoStatus[keyof typeof CreateClaimDtoStatus];


export const CreateClaimDtoStatus = {
  NEW: 'NEW',
  IN_PROGRESS: 'IN_PROGRESS',
  AWAITING_INFO: 'AWAITING_INFO',
  IN_TREATMENT: 'IN_TREATMENT',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
  REJECTED: 'REJECTED',
  SENT_TO_DTM: 'SENT_TO_DTM',
} as const;

export type CreateClaimDtoPriority = typeof CreateClaimDtoPriority[keyof typeof CreateClaimDtoPriority];


export const CreateClaimDtoPriority = {
  low: 'low',
  medium: 'medium',
  high: 'high',
  urgent: 'urgent',
} as const;

export interface CreateClaimDto {
  customerId: number;
  userId?: number;
  orderId?: number;
  operationId?: string;
  type: CreateClaimDtoType;
  status?: CreateClaimDtoStatus;
  priority?: CreateClaimDtoPriority;
  description: string;
  /** @maxLength 1000 */
  resolution?: string;
}

export type ClaimDetailDtoClaimStatus = {
  id: string;
  name: string;
};

export type ClaimDetailDtoClaimCommentsItem = {
  id: number;
  createdAt: string;
  comment: string;
  claimId: number;
  authorUserId: number;
};

export type ClaimDetailDtoCustomer = {
  id: number;
  companyName: string;
};

export type ClaimDetailDtoClaimStatusHistoriesItem = {
  id: number;
  statusId: string;
  changedAt: string;
  /** @nullable */
  comment: string | null;
  changedByUserId: number;
  claimId: number;
};

export type ClaimDetailDtoCreatedByUser = {
  id: number;
  lastName: string;
  firstName: string;
};

export type ClaimDetailDtoOrder = {
  id: number;
  orderNumber: string;
};

export type ClaimDetailDtoAccessoryOperation = {
  id: string;
  name: string;
};

export type ClaimDetailDtoClaimType = {
  id: string;
  name: string;
};

export type ClaimDetailDtoClosedByUser = {
  id: number;
  lastName: string;
  firstName: string;
};

export interface ClaimDetailDto {
  id: number;
  claimNumber: string;
  customerId: number;
  createdByUserId: number;
  /** @nullable */
  orderId: number | null;
  /** @nullable */
  operationId: string | null;
  typeId: string;
  statusId: string;
  /** @nullable */
  priority: string | null;
  description: string;
  /** @nullable */
  resolution: string | null;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  closedByUserId: number | null;
  /** @nullable */
  closedAt: string | null;
  claimStatus: ClaimDetailDtoClaimStatus;
  claimComments: ClaimDetailDtoClaimCommentsItem[];
  customer: ClaimDetailDtoCustomer;
  claimStatusHistories: ClaimDetailDtoClaimStatusHistoriesItem[];
  createdByUser: ClaimDetailDtoCreatedByUser;
  order: ClaimDetailDtoOrder;
  accessoryOperation: ClaimDetailDtoAccessoryOperation;
  claimType: ClaimDetailDtoClaimType;
  closedByUser: ClaimDetailDtoClosedByUser;
}

export type ClaimListDtoClaimStatus = {
  id: string;
  name: string;
};

export type ClaimListDtoCustomer = {
  id: number;
  companyName: string;
};

export type ClaimListDtoCreatedByUser = {
  id: number;
  lastName: string;
  firstName: string;
};

export type ClaimListDtoOrder = {
  id: number;
  orderNumber: string;
};

export type ClaimListDtoAccessoryOperation = {
  id: string;
  name: string;
};

export type ClaimListDtoClaimType = {
  id: string;
  name: string;
};

export interface ClaimListDto {
  id: number;
  claimNumber: string;
  description: string;
  createdAt: string;
  updatedAt: string;
  typeId: string;
  customerId: number;
  createdByUserId: number;
  statusId: string;
  /** @nullable */
  orderId: number | null;
  /** @nullable */
  operationId: string | null;
  /** @nullable */
  priority: string | null;
  /** @nullable */
  resolution: string | null;
  /** @nullable */
  closedByUserId: number | null;
  /** @nullable */
  closedAt: string | null;
  claimStatus: ClaimListDtoClaimStatus;
  customer: ClaimListDtoCustomer;
  createdByUser: ClaimListDtoCreatedByUser;
  order: ClaimListDtoOrder;
  accessoryOperation: ClaimListDtoAccessoryOperation;
  claimType: ClaimListDtoClaimType;
}

export type UpdateClaimDtoType = typeof UpdateClaimDtoType[keyof typeof UpdateClaimDtoType];


export const UpdateClaimDtoType = {
  DELIVERY_DELAY: 'DELIVERY_DELAY',
  DAMAGED_GOODS: 'DAMAGED_GOODS',
  INCORRECT_QUANTITY: 'INCORRECT_QUANTITY',
  NON_COMPLIANT_QUALITY: 'NON_COMPLIANT_QUALITY',
  BILLING_ISSUE: 'BILLING_ISSUE',
  DOCUMENTATION_PROBLEM: 'DOCUMENTATION_PROBLEM',
  CUSTOMER_SERVICE: 'CUSTOMER_SERVICE',
  OTHER: 'OTHER',
} as const;

export type UpdateClaimDtoStatus = typeof UpdateClaimDtoStatus[keyof typeof UpdateClaimDtoStatus];


export const UpdateClaimDtoStatus = {
  NEW: 'NEW',
  IN_PROGRESS: 'IN_PROGRESS',
  AWAITING_INFO: 'AWAITING_INFO',
  IN_TREATMENT: 'IN_TREATMENT',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
  REJECTED: 'REJECTED',
  SENT_TO_DTM: 'SENT_TO_DTM',
} as const;

export type UpdateClaimDtoPriority = typeof UpdateClaimDtoPriority[keyof typeof UpdateClaimDtoPriority];


export const UpdateClaimDtoPriority = {
  low: 'low',
  medium: 'medium',
  high: 'high',
  urgent: 'urgent',
} as const;

export interface UpdateClaimDto {
  customerId?: number;
  userId?: number;
  orderId?: number;
  operationId?: string;
  type?: UpdateClaimDtoType;
  status?: UpdateClaimDtoStatus;
  priority?: UpdateClaimDtoPriority;
  description?: string;
  /** @maxLength 1000 */
  resolution?: string;
}

export interface ClaimDeleteDto {
  id: number;
}

export interface CreateClaimCommentDto {
  /** @maxLength 2000 */
  content: string;
}

export interface ClaimCommentDto {
  /** @nullable */
  authorName: string | null;
  id: number;
  claimId: number;
  authorUserId: number;
  comment: string;
  createdAt: string;
}

export interface ResolveClaimDto {
  /** @maxLength 1000 */
  resolution: string;
}

export interface RejectClaimDto {
  /** @maxLength 1000 */
  rejectionReason: string;
}

export interface ProfileDto {
  id: number;
  email: string;
  lastName: string;
  firstName: string;
  role: string;
  permissions: string[];
  /** @nullable */
  employeeCode: string | null;
  /** @nullable */
  type: string | null;
  roleId: string;
  /** @nullable */
  customerId: number | null;
  /** @nullable */
  customerName: string | null;
  /** @nullable */
  customerCode: string | null;
  /** @nullable */
  agencyId: number | null;
  createdAt: string;
  /** @nullable */
  lastLogin: string | null;
}

export type AppearancePreferencesDtoTheme = typeof AppearancePreferencesDtoTheme[keyof typeof AppearancePreferencesDtoTheme];


export const AppearancePreferencesDtoTheme = {
  system: 'system',
  light: 'light',
  dark: 'dark',
  'mono-light': 'mono-light',
  'mono-dark': 'mono-dark',
} as const;

export type AppearancePreferencesDtoFontFamily = typeof AppearancePreferencesDtoFontFamily[keyof typeof AppearancePreferencesDtoFontFamily];


export const AppearancePreferencesDtoFontFamily = {
  inter: 'inter',
  geist: 'geist',
  system: 'system',
  arial: 'arial',
  serif: 'serif',
  monospace: 'monospace',
} as const;

export type AppearancePreferencesDtoTextSize = typeof AppearancePreferencesDtoTextSize[keyof typeof AppearancePreferencesDtoTextSize];


export const AppearancePreferencesDtoTextSize = {
  small: 'small',
  default: 'default',
  large: 'large',
} as const;

export type AppearancePreferencesDtoMotion = typeof AppearancePreferencesDtoMotion[keyof typeof AppearancePreferencesDtoMotion];


export const AppearancePreferencesDtoMotion = {
  system: 'system',
  reduced: 'reduced',
} as const;

export type AppearancePreferencesDtoWorkspaceLayout = typeof AppearancePreferencesDtoWorkspaceLayout[keyof typeof AppearancePreferencesDtoWorkspaceLayout];


export const AppearancePreferencesDtoWorkspaceLayout = {
  sidebar: 'sidebar',
  'centered-header': 'centered-header',
} as const;

export interface AppearancePreferencesDto {
  theme: AppearancePreferencesDtoTheme;
  fontFamily: AppearancePreferencesDtoFontFamily;
  textSize: AppearancePreferencesDtoTextSize;
  motion: AppearancePreferencesDtoMotion;
  workspaceLayout: AppearancePreferencesDtoWorkspaceLayout;
  updatedAt: string;
}

export type UpdateAppearancePreferencesDtoTheme = typeof UpdateAppearancePreferencesDtoTheme[keyof typeof UpdateAppearancePreferencesDtoTheme];


export const UpdateAppearancePreferencesDtoTheme = {
  system: 'system',
  light: 'light',
  dark: 'dark',
  'mono-light': 'mono-light',
  'mono-dark': 'mono-dark',
} as const;

export type UpdateAppearancePreferencesDtoFontFamily = typeof UpdateAppearancePreferencesDtoFontFamily[keyof typeof UpdateAppearancePreferencesDtoFontFamily];


export const UpdateAppearancePreferencesDtoFontFamily = {
  inter: 'inter',
  geist: 'geist',
  system: 'system',
  arial: 'arial',
  serif: 'serif',
  monospace: 'monospace',
} as const;

export type UpdateAppearancePreferencesDtoTextSize = typeof UpdateAppearancePreferencesDtoTextSize[keyof typeof UpdateAppearancePreferencesDtoTextSize];


export const UpdateAppearancePreferencesDtoTextSize = {
  small: 'small',
  default: 'default',
  large: 'large',
} as const;

export type UpdateAppearancePreferencesDtoMotion = typeof UpdateAppearancePreferencesDtoMotion[keyof typeof UpdateAppearancePreferencesDtoMotion];


export const UpdateAppearancePreferencesDtoMotion = {
  system: 'system',
  reduced: 'reduced',
} as const;

export type UpdateAppearancePreferencesDtoWorkspaceLayout = typeof UpdateAppearancePreferencesDtoWorkspaceLayout[keyof typeof UpdateAppearancePreferencesDtoWorkspaceLayout];


export const UpdateAppearancePreferencesDtoWorkspaceLayout = {
  sidebar: 'sidebar',
  'centered-header': 'centered-header',
} as const;

export interface UpdateAppearancePreferencesDto {
  theme: UpdateAppearancePreferencesDtoTheme;
  fontFamily: UpdateAppearancePreferencesDtoFontFamily;
  textSize: UpdateAppearancePreferencesDtoTextSize;
  motion: UpdateAppearancePreferencesDtoMotion;
  workspaceLayout: UpdateAppearancePreferencesDtoWorkspaceLayout;
}

export interface UpdateProfileDto {
  /** @maxLength 100 */
  email?: string;
  /** @maxLength 100 */
  firstName?: string;
  /** @maxLength 100 */
  lastName?: string;
}

export interface CustomerTypeDto {
  id: string;
  name: string;
  isActive: boolean;
  createdAt: string;
}

export interface UnitDto {
  id: string;
  name: string;
  isActive: boolean;
  createdAt: string;
}

export interface CreateUnitDto {
  name: string;
}

export interface UpdateUnitDto {
  /** @maxLength 50 */
  name: string;
  isActive: boolean;
}

export interface GoodsTypeDto {
  id: string;
  name: string;
  isActive: boolean;
  createdAt: string;
}

export interface CreateGoodsTypeDto {
  name: string;
}

export interface UpdateGoodsTypeDto {
  /** @maxLength 100 */
  name: string;
  isActive: boolean;
}

export interface GoodDto {
  id: number;
  name: string;
  createdAt: string;
  isActive: boolean;
  goodsTypeId: string;
  goodsCode: string;
  updatedAt: string;
}

export interface CreateGoodDto {
  name: string;
  goodsCode: string;
  goodsTypeId: string;
}

export interface UpdateGoodDto {
  /** @maxLength 200 */
  name: string;
  /** @maxLength 50 */
  goodsCode: string;
  goodsTypeId: string;
  isActive: boolean;
}

export interface AccessoryOperationDto {
  id: string;
  name: string;
  isActive: boolean;
  createdAt: string;
}

export interface CreateAccessoryOperationDto {
  name: string;
}

export interface UpdateAccessoryOperationDto {
  /** @maxLength 200 */
  name: string;
  isActive: boolean;
}

export interface RejectionReasonDto {
  id: string;
  name: string;
  isActive: boolean;
  createdAt: string;
}

export interface CreateRejectionReasonDto {
  name: string;
}

export interface UpdateRejectionReasonDto {
  /** @maxLength 300 */
  name: string;
  isActive: boolean;
}

export type RolePersona = typeof RolePersona[keyof typeof RolePersona];


export const RolePersona = {
  ADMIN: 'ADMIN',
  AGENT_COMMERCIAL: 'AGENT_COMMERCIAL',
  CLIENT_REPRESENTATIVE: 'CLIENT_REPRESENTATIVE',
} as const;

export interface RoleProfileDto {
  persona: RolePersona | null;
  id: string;
  name: string;
  /** @nullable */
  description: string | null;
  isSystem: boolean;
  isActive: boolean;
  permissionNames: string[];
  createdAt: string;
  updatedAt: string;
}

export interface PermissionDefinitionDto {
  parent?: string;
  name: string;
  assignable: boolean;
}

export type CreateRoleProfileDtoPersona = typeof CreateRoleProfileDtoPersona[keyof typeof CreateRoleProfileDtoPersona];


export const CreateRoleProfileDtoPersona = {
  AGENT_COMMERCIAL: 'AGENT_COMMERCIAL',
  CLIENT_REPRESENTATIVE: 'CLIENT_REPRESENTATIVE',
} as const;

export type CreateRoleProfileDtoPermissionNamesItem = typeof CreateRoleProfileDtoPermissionNamesItem[keyof typeof CreateRoleProfileDtoPermissionNamesItem];


export const CreateRoleProfileDtoPermissionNamesItem = {
  'users:create': 'users:create',
  'users:read': 'users:read',
  'users:update': 'users:update',
  'users:delete': 'users:delete',
  'users:manage': 'users:manage',
  'users:manage:other': 'users:manage:other',
  'orders:create': 'orders:create',
  'orders:read': 'orders:read',
  'orders:update': 'orders:update',
  'orders:delete': 'orders:delete',
  'orders:manage': 'orders:manage',
  'orders:manage:other': 'orders:manage:other',
  'orders:manage:ownership': 'orders:manage:ownership',
  'orders:manage:status': 'orders:manage:status',
  'orders:action': 'orders:action',
  'orders:action:submit': 'orders:action:submit',
  'orders:action:approve': 'orders:action:approve',
  'orders:action:reject': 'orders:action:reject',
  'orders:action:cancel': 'orders:action:cancel',
  'orders:action:send-to-dtm': 'orders:action:send-to-dtm',
  'customers:create': 'customers:create',
  'customers:read': 'customers:read',
  'customers:update': 'customers:update',
  'customers:delete': 'customers:delete',
  'customers:manage': 'customers:manage',
  'customers:manage:other': 'customers:manage:other',
  'programs:create': 'programs:create',
  'programs:read': 'programs:read',
  'programs:update': 'programs:update',
  'programs:delete': 'programs:delete',
  'programs:manage': 'programs:manage',
  'programs:manage:other': 'programs:manage:other',
  'programs:manage:ownership': 'programs:manage:ownership',
  'programs:manage:status': 'programs:manage:status',
  'programs:action': 'programs:action',
  'programs:action:submit': 'programs:action:submit',
  'programs:action:approve': 'programs:action:approve',
  'programs:action:confirm': 'programs:action:confirm',
  'programs:action:cancel': 'programs:action:cancel',
  'programs:action:send': 'programs:action:send',
  'programs:action:execute': 'programs:action:execute',
  'claims:create': 'claims:create',
  'claims:read': 'claims:read',
  'claims:update': 'claims:update',
  'claims:delete': 'claims:delete',
  'claims:manage': 'claims:manage',
  'claims:manage:other': 'claims:manage:other',
  'claims:manage:status': 'claims:manage:status',
  'claims:action': 'claims:action',
  'claims:action:comment': 'claims:action:comment',
  'claims:action:start-progress': 'claims:action:start-progress',
  'claims:action:await-info': 'claims:action:await-info',
  'claims:action:start-treatment': 'claims:action:start-treatment',
  'claims:action:resolve': 'claims:action:resolve',
  'claims:action:reject': 'claims:action:reject',
  'claims:action:send-to-dtm': 'claims:action:send-to-dtm',
  'claims:action:close': 'claims:action:close',
  'catalog:read': 'catalog:read',
  'catalog:manage': 'catalog:manage',
  'catalog:manage:units': 'catalog:manage:units',
  'catalog:manage:goods': 'catalog:manage:goods',
  'catalog:manage:goods-types': 'catalog:manage:goods-types',
  'catalog:manage:accessory-operations': 'catalog:manage:accessory-operations',
  'catalog:manage:rejection-reasons': 'catalog:manage:rejection-reasons',
  'tracking:read': 'tracking:read',
  'tracking:update': 'tracking:update',
  'tracking:manage': 'tracking:manage',
  'reports:read': 'reports:read',
  'reports:manage:other': 'reports:manage:other',
  'reports:action': 'reports:action',
  'reports:action:export': 'reports:action:export',
  'roles:manage': 'roles:manage',
  'permissions:manage': 'permissions:manage',
  'logs:read': 'logs:read',
  'profile:update': 'profile:update',
  'archival:read': 'archival:read',
  'archival:manage': 'archival:manage',
} as const;

export interface CreateRoleProfileDto {
  /** @maxLength 100 */
  name: string;
  /**
     * @maxLength 500
     * @nullable
     */
  description?: string | null;
  persona: CreateRoleProfileDtoPersona;
  permissionNames: CreateRoleProfileDtoPermissionNamesItem[];
}

export type UpdateRoleProfileDtoPersona = typeof UpdateRoleProfileDtoPersona[keyof typeof UpdateRoleProfileDtoPersona];


export const UpdateRoleProfileDtoPersona = {
  AGENT_COMMERCIAL: 'AGENT_COMMERCIAL',
  CLIENT_REPRESENTATIVE: 'CLIENT_REPRESENTATIVE',
} as const;

export type UpdateRoleProfileDtoPermissionNamesItem = typeof UpdateRoleProfileDtoPermissionNamesItem[keyof typeof UpdateRoleProfileDtoPermissionNamesItem];


export const UpdateRoleProfileDtoPermissionNamesItem = {
  'users:create': 'users:create',
  'users:read': 'users:read',
  'users:update': 'users:update',
  'users:delete': 'users:delete',
  'users:manage': 'users:manage',
  'users:manage:other': 'users:manage:other',
  'orders:create': 'orders:create',
  'orders:read': 'orders:read',
  'orders:update': 'orders:update',
  'orders:delete': 'orders:delete',
  'orders:manage': 'orders:manage',
  'orders:manage:other': 'orders:manage:other',
  'orders:manage:ownership': 'orders:manage:ownership',
  'orders:manage:status': 'orders:manage:status',
  'orders:action': 'orders:action',
  'orders:action:submit': 'orders:action:submit',
  'orders:action:approve': 'orders:action:approve',
  'orders:action:reject': 'orders:action:reject',
  'orders:action:cancel': 'orders:action:cancel',
  'orders:action:send-to-dtm': 'orders:action:send-to-dtm',
  'customers:create': 'customers:create',
  'customers:read': 'customers:read',
  'customers:update': 'customers:update',
  'customers:delete': 'customers:delete',
  'customers:manage': 'customers:manage',
  'customers:manage:other': 'customers:manage:other',
  'programs:create': 'programs:create',
  'programs:read': 'programs:read',
  'programs:update': 'programs:update',
  'programs:delete': 'programs:delete',
  'programs:manage': 'programs:manage',
  'programs:manage:other': 'programs:manage:other',
  'programs:manage:ownership': 'programs:manage:ownership',
  'programs:manage:status': 'programs:manage:status',
  'programs:action': 'programs:action',
  'programs:action:submit': 'programs:action:submit',
  'programs:action:approve': 'programs:action:approve',
  'programs:action:confirm': 'programs:action:confirm',
  'programs:action:cancel': 'programs:action:cancel',
  'programs:action:send': 'programs:action:send',
  'programs:action:execute': 'programs:action:execute',
  'claims:create': 'claims:create',
  'claims:read': 'claims:read',
  'claims:update': 'claims:update',
  'claims:delete': 'claims:delete',
  'claims:manage': 'claims:manage',
  'claims:manage:other': 'claims:manage:other',
  'claims:manage:status': 'claims:manage:status',
  'claims:action': 'claims:action',
  'claims:action:comment': 'claims:action:comment',
  'claims:action:start-progress': 'claims:action:start-progress',
  'claims:action:await-info': 'claims:action:await-info',
  'claims:action:start-treatment': 'claims:action:start-treatment',
  'claims:action:resolve': 'claims:action:resolve',
  'claims:action:reject': 'claims:action:reject',
  'claims:action:send-to-dtm': 'claims:action:send-to-dtm',
  'claims:action:close': 'claims:action:close',
  'catalog:read': 'catalog:read',
  'catalog:manage': 'catalog:manage',
  'catalog:manage:units': 'catalog:manage:units',
  'catalog:manage:goods': 'catalog:manage:goods',
  'catalog:manage:goods-types': 'catalog:manage:goods-types',
  'catalog:manage:accessory-operations': 'catalog:manage:accessory-operations',
  'catalog:manage:rejection-reasons': 'catalog:manage:rejection-reasons',
  'tracking:read': 'tracking:read',
  'tracking:update': 'tracking:update',
  'tracking:manage': 'tracking:manage',
  'reports:read': 'reports:read',
  'reports:manage:other': 'reports:manage:other',
  'reports:action': 'reports:action',
  'reports:action:export': 'reports:action:export',
  'roles:manage': 'roles:manage',
  'permissions:manage': 'permissions:manage',
  'logs:read': 'logs:read',
  'profile:update': 'profile:update',
  'archival:read': 'archival:read',
  'archival:manage': 'archival:manage',
} as const;

export interface UpdateRoleProfileDto {
  /** @maxLength 100 */
  name?: string;
  /**
     * @maxLength 500
     * @nullable
     */
  description?: string | null;
  persona?: UpdateRoleProfileDtoPersona;
  permissionNames?: UpdateRoleProfileDtoPermissionNamesItem[];
  isActive?: boolean;
}

export type TrackWagonDtoWagonTrackingsItem = {
  id: number;
  wagonId: number;
  /** @nullable */
  latitude: string | null;
  /** @nullable */
  longitude: string | null;
  /** @nullable */
  status: string | null;
  recordedAt: string;
};

export interface TrackWagonDto {
  id: number;
  /** @nullable */
  externalId: string | null;
  wagonNumber: string;
  /** @nullable */
  type: string | null;
  /** @nullable */
  capacity: string | null;
  createdAt: string;
  updatedAt: string;
  isActive: boolean;
  wagonTrackings: TrackWagonDtoWagonTrackingsItem[];
}

export type TrackTrainDtoTrainTrackingsItem = {
  id: number;
  trainId: number;
  /** @nullable */
  latitude: string | null;
  /** @nullable */
  longitude: string | null;
  /** @nullable */
  status: string | null;
  recordedAt: string;
};

export interface TrackTrainDto {
  id: number;
  /** @nullable */
  externalId: string | null;
  trainNumber: string;
  /** @nullable */
  status: string | null;
  createdAt: string;
  updatedAt: string;
  isActive: boolean;
  trainTrackings: TrackTrainDtoTrainTrackingsItem[];
}

export type TrackOrderDtoWagonWagonTrackingsItem = {
  id: number;
  /** @nullable */
  status: string | null;
  wagonId: number;
  /** @nullable */
  latitude: string | null;
  /** @nullable */
  longitude: string | null;
  recordedAt: string;
};

export type TrackOrderDtoWagon = {
  id: number;
  wagonNumber: string;
  wagonTrackings?: TrackOrderDtoWagonWagonTrackingsItem[];
};

export interface TrackOrderDto {
  orderId: number;
  wagonId: number;
  wagon: TrackOrderDtoWagon;
}

export interface UpdateWagonPositionDto {
  /**
     * @minimum -90
     * @maximum 90
     */
  latitude: number;
  /**
     * @minimum -180
     * @maximum 180
     */
  longitude: number;
  status?: string;
}

export interface WagonPositionDto {
  id: number;
  wagonId: number;
  /** @nullable */
  latitude: string | null;
  /** @nullable */
  longitude: string | null;
  /** @nullable */
  status: string | null;
  recordedAt: string;
}

export interface UpdateTrainPositionDto {
  /**
     * @minimum -90
     * @maximum 90
     */
  latitude: number;
  /**
     * @minimum -180
     * @maximum 180
     */
  longitude: number;
  status?: string;
}

export interface TrainPositionDto {
  id: number;
  trainId: number;
  /** @nullable */
  latitude: string | null;
  /** @nullable */
  longitude: string | null;
  /** @nullable */
  status: string | null;
  recordedAt: string;
}

export type CustomersControllerFindAllParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
typeId?: string;
isActive?: boolean;
search?: string;
sortBy?: string;
sortOrder?: CustomersControllerFindAllSortOrder;
};

export type CustomersControllerFindAllSortOrder = typeof CustomersControllerFindAllSortOrder[keyof typeof CustomersControllerFindAllSortOrder];


export const CustomersControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type OrdersControllerFindAllParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
goodsId?: number;
customerId?: number;
status?: OrdersControllerFindAllStatus;
movementTypeId?: string;
startDate?: string;
endDate?: string;
search?: string;
sortBy?: string;
sortOrder?: OrdersControllerFindAllSortOrder;
};

export type OrdersControllerFindAllStatus = typeof OrdersControllerFindAllStatus[keyof typeof OrdersControllerFindAllStatus];


export const OrdersControllerFindAllStatus = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  IN_PROGRESS: 'IN_PROGRESS',
  PARTIALLY_EXECUTED: 'PARTIALLY_EXECUTED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  SENT_TO_DTM: 'SENT_TO_DTM',
} as const;

export type OrdersControllerFindAllSortOrder = typeof OrdersControllerFindAllSortOrder[keyof typeof OrdersControllerFindAllSortOrder];


export const OrdersControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type OrdersControllerFindEligibleForProgramsParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
search?: string;
sortBy?: string;
sortOrder?: OrdersControllerFindEligibleForProgramsSortOrder;
};

export type OrdersControllerFindEligibleForProgramsSortOrder = typeof OrdersControllerFindEligibleForProgramsSortOrder[keyof typeof OrdersControllerFindEligibleForProgramsSortOrder];


export const OrdersControllerFindEligibleForProgramsSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type ProgramsControllerFindAllParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
orderId?: number;
userId?: number;
status?: ProgramsControllerFindAllStatus;
dtmStatus?: string;
search?: string;
sortBy?: string;
sortOrder?: ProgramsControllerFindAllSortOrder;
};

export type ProgramsControllerFindAllStatus = typeof ProgramsControllerFindAllStatus[keyof typeof ProgramsControllerFindAllStatus];


export const ProgramsControllerFindAllStatus = {
  DRAFT: 'DRAFT',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  SENT_TO_DTM: 'SENT_TO_DTM',
  CONFIRMED: 'CONFIRMED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export type ProgramsControllerFindAllSortOrder = typeof ProgramsControllerFindAllSortOrder[keyof typeof ProgramsControllerFindAllSortOrder];


export const ProgramsControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type ClaimsControllerFindAllParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
customerId?: number;
userId?: number;
orderId?: number;
operationId?: string;
type?: ClaimsControllerFindAllType;
status?: ClaimsControllerFindAllStatus;
priority?: ClaimsControllerFindAllPriority;
search?: string;
sortBy?: string;
sortOrder?: ClaimsControllerFindAllSortOrder;
};

export type ClaimsControllerFindAllType = typeof ClaimsControllerFindAllType[keyof typeof ClaimsControllerFindAllType];


export const ClaimsControllerFindAllType = {
  DELIVERY_DELAY: 'DELIVERY_DELAY',
  DAMAGED_GOODS: 'DAMAGED_GOODS',
  INCORRECT_QUANTITY: 'INCORRECT_QUANTITY',
  NON_COMPLIANT_QUALITY: 'NON_COMPLIANT_QUALITY',
  BILLING_ISSUE: 'BILLING_ISSUE',
  DOCUMENTATION_PROBLEM: 'DOCUMENTATION_PROBLEM',
  CUSTOMER_SERVICE: 'CUSTOMER_SERVICE',
  OTHER: 'OTHER',
} as const;

export type ClaimsControllerFindAllStatus = typeof ClaimsControllerFindAllStatus[keyof typeof ClaimsControllerFindAllStatus];


export const ClaimsControllerFindAllStatus = {
  NEW: 'NEW',
  IN_PROGRESS: 'IN_PROGRESS',
  AWAITING_INFO: 'AWAITING_INFO',
  IN_TREATMENT: 'IN_TREATMENT',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
  REJECTED: 'REJECTED',
  SENT_TO_DTM: 'SENT_TO_DTM',
} as const;

export type ClaimsControllerFindAllPriority = typeof ClaimsControllerFindAllPriority[keyof typeof ClaimsControllerFindAllPriority];


export const ClaimsControllerFindAllPriority = {
  low: 'low',
  medium: 'medium',
  high: 'high',
  urgent: 'urgent',
} as const;

export type ClaimsControllerFindAllSortOrder = typeof ClaimsControllerFindAllSortOrder[keyof typeof ClaimsControllerFindAllSortOrder];


export const ClaimsControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type ReportsControllerGetOrdersParams = {
/**
 * @pattern ^\d{4}-\d{2}-\d{2}$
 */
from?: string;
/**
 * @pattern ^\d{4}-\d{2}-\d{2}$
 */
to?: string;
};
