/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ONCF ECommand API
 * ONCF freight order management
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiErrorResponseDto,
  CreateIntegrationCredentialDto,
  CreatedIntegrationCredentialDto,
  IntegrationCredentialDto,
  RevokedIntegrationCredentialDto
} from './generated.schemas';

import { customFetch } from '../axios';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const integrationCredentialsControllerList = (

 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<IntegrationCredentialDto[]>(
      {url: `/integration-credentials`, method: 'GET', signal
    },
      options);
    }




export const getIntegrationCredentialsControllerListQueryKey = () => {
    return [
    `/integration-credentials`
    ] as const;
    }


export const getIntegrationCredentialsControllerListQueryOptions = <TData = Awaited<ReturnType<typeof integrationCredentialsControllerList>>, TError = ApiErrorResponseDto>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof integrationCredentialsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getIntegrationCredentialsControllerListQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof integrationCredentialsControllerList>>> = ({ signal }) => integrationCredentialsControllerList(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof integrationCredentialsControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type IntegrationCredentialsControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof integrationCredentialsControllerList>>>
export type IntegrationCredentialsControllerListQueryError = ApiErrorResponseDto


export function useIntegrationCredentialsControllerList<TData = Awaited<ReturnType<typeof integrationCredentialsControllerList>>, TError = ApiErrorResponseDto>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof integrationCredentialsControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof integrationCredentialsControllerList>>,
          TError,
          Awaited<ReturnType<typeof integrationCredentialsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useIntegrationCredentialsControllerList<TData = Awaited<ReturnType<typeof integrationCredentialsControllerList>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof integrationCredentialsControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof integrationCredentialsControllerList>>,
          TError,
          Awaited<ReturnType<typeof integrationCredentialsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useIntegrationCredentialsControllerList<TData = Awaited<ReturnType<typeof integrationCredentialsControllerList>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof integrationCredentialsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useIntegrationCredentialsControllerList<TData = Awaited<ReturnType<typeof integrationCredentialsControllerList>>, TError = ApiErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof integrationCredentialsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getIntegrationCredentialsControllerListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const integrationCredentialsControllerCreate = (
    createIntegrationCredentialDto: CreateIntegrationCredentialDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<CreatedIntegrationCredentialDto>(
      {url: `/integration-credentials`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createIntegrationCredentialDto, signal
    },
      options);
    }




export const getIntegrationCredentialsControllerCreateMutationOptions = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof integrationCredentialsControllerCreate>>, TError,{data: CreateIntegrationCredentialDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof integrationCredentialsControllerCreate>>, TError,{data: CreateIntegrationCredentialDto}, TContext> => {

const mutationKey = ['integrationCredentialsControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof integrationCredentialsControllerCreate>>, {data: CreateIntegrationCredentialDto}> = (props) => {
          const {data} = props ?? {};

          return  integrationCredentialsControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type IntegrationCredentialsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof integrationCredentialsControllerCreate>>>
    export type IntegrationCredentialsControllerCreateMutationBody = CreateIntegrationCredentialDto
    export type IntegrationCredentialsControllerCreateMutationError = ApiErrorResponseDto

    export const useIntegrationCredentialsControllerCreate = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof integrationCredentialsControllerCreate>>, TError,{data: CreateIntegrationCredentialDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof integrationCredentialsControllerCreate>>,
        TError,
        {data: CreateIntegrationCredentialDto},
        TContext
      > => {
      return useMutation(getIntegrationCredentialsControllerCreateMutationOptions(options), queryClient);
    }
    export const integrationCredentialsControllerRotate = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<CreatedIntegrationCredentialDto>(
      {url: `/integration-credentials/${id}/rotate`, method: 'POST', signal
    },
      options);
    }




export const getIntegrationCredentialsControllerRotateMutationOptions = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof integrationCredentialsControllerRotate>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof integrationCredentialsControllerRotate>>, TError,{id: number}, TContext> => {

const mutationKey = ['integrationCredentialsControllerRotate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof integrationCredentialsControllerRotate>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  integrationCredentialsControllerRotate(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type IntegrationCredentialsControllerRotateMutationResult = NonNullable<Awaited<ReturnType<typeof integrationCredentialsControllerRotate>>>

    export type IntegrationCredentialsControllerRotateMutationError = ApiErrorResponseDto

    export const useIntegrationCredentialsControllerRotate = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof integrationCredentialsControllerRotate>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof integrationCredentialsControllerRotate>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getIntegrationCredentialsControllerRotateMutationOptions(options), queryClient);
    }
    export const integrationCredentialsControllerRevoke = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<RevokedIntegrationCredentialDto>(
      {url: `/integration-credentials/${id}/revoke`, method: 'PATCH', signal
    },
      options);
    }




export const getIntegrationCredentialsControllerRevokeMutationOptions = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof integrationCredentialsControllerRevoke>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof integrationCredentialsControllerRevoke>>, TError,{id: number}, TContext> => {

const mutationKey = ['integrationCredentialsControllerRevoke'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof integrationCredentialsControllerRevoke>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  integrationCredentialsControllerRevoke(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type IntegrationCredentialsControllerRevokeMutationResult = NonNullable<Awaited<ReturnType<typeof integrationCredentialsControllerRevoke>>>

    export type IntegrationCredentialsControllerRevokeMutationError = ApiErrorResponseDto

    export const useIntegrationCredentialsControllerRevoke = <TError = ApiErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof integrationCredentialsControllerRevoke>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof integrationCredentialsControllerRevoke>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getIntegrationCredentialsControllerRevokeMutationOptions(options), queryClient);
    }
