/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ONCF Ecommand API
 * ONCF freight order management
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ProfileDto,
  UpdateProfileDto
} from './generated.schemas';

import { customFetch } from '../axios';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const profileControllerGetCurrent = (

 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<ProfileDto>(
      {url: `/profile`, method: 'GET', signal
    },
      options);
    }




export const getProfileControllerGetCurrentQueryKey = () => {
    return [
    `/profile`
    ] as const;
    }


export const getProfileControllerGetCurrentQueryOptions = <TData = Awaited<ReturnType<typeof profileControllerGetCurrent>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetCurrent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProfileControllerGetCurrentQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof profileControllerGetCurrent>>> = ({ signal }) => profileControllerGetCurrent(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetCurrent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProfileControllerGetCurrentQueryResult = NonNullable<Awaited<ReturnType<typeof profileControllerGetCurrent>>>
export type ProfileControllerGetCurrentQueryError = void


export function useProfileControllerGetCurrent<TData = Awaited<ReturnType<typeof profileControllerGetCurrent>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetCurrent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileControllerGetCurrent>>,
          TError,
          Awaited<ReturnType<typeof profileControllerGetCurrent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProfileControllerGetCurrent<TData = Awaited<ReturnType<typeof profileControllerGetCurrent>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetCurrent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileControllerGetCurrent>>,
          TError,
          Awaited<ReturnType<typeof profileControllerGetCurrent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProfileControllerGetCurrent<TData = Awaited<ReturnType<typeof profileControllerGetCurrent>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetCurrent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProfileControllerGetCurrent<TData = Awaited<ReturnType<typeof profileControllerGetCurrent>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetCurrent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProfileControllerGetCurrentQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const profileControllerUpdate = (
    updateProfileDto: UpdateProfileDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<ProfileDto>(
      {url: `/profile`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateProfileDto, signal
    },
      options);
    }




export const getProfileControllerUpdateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof profileControllerUpdate>>, TError,{data: UpdateProfileDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof profileControllerUpdate>>, TError,{data: UpdateProfileDto}, TContext> => {

const mutationKey = ['profileControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof profileControllerUpdate>>, {data: UpdateProfileDto}> = (props) => {
          const {data} = props ?? {};

          return  profileControllerUpdate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ProfileControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof profileControllerUpdate>>>
    export type ProfileControllerUpdateMutationBody = UpdateProfileDto
    export type ProfileControllerUpdateMutationError = void

    export const useProfileControllerUpdate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof profileControllerUpdate>>, TError,{data: UpdateProfileDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof profileControllerUpdate>>,
        TError,
        {data: UpdateProfileDto},
        TContext
      > => {
      return useMutation(getProfileControllerUpdateMutationOptions(options), queryClient);
    }
