/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ONCF Ecommand API
 * ONCF freight order management
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateProgramDto,
  ProgramDeleteDto,
  ProgramDetailDto,
  ProgramListDto,
  UpdateProgramDto
} from './generated.schemas';

import { customFetch } from '../axios';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const programsControllerCreate = (
    createProgramDto: CreateProgramDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<ProgramDetailDto>(
      {url: `/programs`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createProgramDto, signal
    },
      options);
    }




export const getProgramsControllerCreateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programsControllerCreate>>, TError,{data: CreateProgramDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof programsControllerCreate>>, TError,{data: CreateProgramDto}, TContext> => {

const mutationKey = ['programsControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof programsControllerCreate>>, {data: CreateProgramDto}> = (props) => {
          const {data} = props ?? {};

          return  programsControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ProgramsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof programsControllerCreate>>>
    export type ProgramsControllerCreateMutationBody = CreateProgramDto
    export type ProgramsControllerCreateMutationError = void

    export const useProgramsControllerCreate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programsControllerCreate>>, TError,{data: CreateProgramDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof programsControllerCreate>>,
        TError,
        {data: CreateProgramDto},
        TContext
      > => {
      return useMutation(getProgramsControllerCreateMutationOptions(options), queryClient);
    }
    export const programsControllerFindAll = (

 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<ProgramListDto[]>(
      {url: `/programs`, method: 'GET', signal
    },
      options);
    }




export const getProgramsControllerFindAllQueryKey = () => {
    return [
    `/programs`
    ] as const;
    }


export const getProgramsControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof programsControllerFindAll>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programsControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProgramsControllerFindAllQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof programsControllerFindAll>>> = ({ signal }) => programsControllerFindAll(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof programsControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProgramsControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof programsControllerFindAll>>>
export type ProgramsControllerFindAllQueryError = void


export function useProgramsControllerFindAll<TData = Awaited<ReturnType<typeof programsControllerFindAll>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof programsControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof programsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof programsControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProgramsControllerFindAll<TData = Awaited<ReturnType<typeof programsControllerFindAll>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programsControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof programsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof programsControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProgramsControllerFindAll<TData = Awaited<ReturnType<typeof programsControllerFindAll>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programsControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProgramsControllerFindAll<TData = Awaited<ReturnType<typeof programsControllerFindAll>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programsControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProgramsControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const programsControllerFindOne = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<ProgramDetailDto>(
      {url: `/programs/${id}`, method: 'GET', signal
    },
      options);
    }




export const getProgramsControllerFindOneQueryKey = (id: number,) => {
    return [
    `/programs/${id}`
    ] as const;
    }


export const getProgramsControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof programsControllerFindOne>>, TError = void>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProgramsControllerFindOneQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof programsControllerFindOne>>> = ({ signal }) => programsControllerFindOne(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof programsControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProgramsControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof programsControllerFindOne>>>
export type ProgramsControllerFindOneQueryError = void


export function useProgramsControllerFindOne<TData = Awaited<ReturnType<typeof programsControllerFindOne>>, TError = void>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof programsControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof programsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof programsControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProgramsControllerFindOne<TData = Awaited<ReturnType<typeof programsControllerFindOne>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programsControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof programsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof programsControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProgramsControllerFindOne<TData = Awaited<ReturnType<typeof programsControllerFindOne>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProgramsControllerFindOne<TData = Awaited<ReturnType<typeof programsControllerFindOne>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof programsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProgramsControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const programsControllerUpdate = (
    id: number,
    updateProgramDto: UpdateProgramDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<ProgramDetailDto>(
      {url: `/programs/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateProgramDto, signal
    },
      options);
    }




export const getProgramsControllerUpdateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programsControllerUpdate>>, TError,{id: number;data: UpdateProgramDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof programsControllerUpdate>>, TError,{id: number;data: UpdateProgramDto}, TContext> => {

const mutationKey = ['programsControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof programsControllerUpdate>>, {id: number;data: UpdateProgramDto}> = (props) => {
          const {id,data} = props ?? {};

          return  programsControllerUpdate(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ProgramsControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof programsControllerUpdate>>>
    export type ProgramsControllerUpdateMutationBody = UpdateProgramDto
    export type ProgramsControllerUpdateMutationError = void

    export const useProgramsControllerUpdate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programsControllerUpdate>>, TError,{id: number;data: UpdateProgramDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof programsControllerUpdate>>,
        TError,
        {id: number;data: UpdateProgramDto},
        TContext
      > => {
      return useMutation(getProgramsControllerUpdateMutationOptions(options), queryClient);
    }
    export const programsControllerRemove = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<ProgramDeleteDto>(
      {url: `/programs/${id}`, method: 'DELETE', signal
    },
      options);
    }




export const getProgramsControllerRemoveMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programsControllerRemove>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof programsControllerRemove>>, TError,{id: number}, TContext> => {

const mutationKey = ['programsControllerRemove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof programsControllerRemove>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  programsControllerRemove(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ProgramsControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof programsControllerRemove>>>

    export type ProgramsControllerRemoveMutationError = void

    export const useProgramsControllerRemove = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programsControllerRemove>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof programsControllerRemove>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getProgramsControllerRemoveMutationOptions(options), queryClient);
    }
    export const programsControllerSubmit = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<ProgramDetailDto>(
      {url: `/programs/${id}/submit`, method: 'POST', signal
    },
      options);
    }




export const getProgramsControllerSubmitMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programsControllerSubmit>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof programsControllerSubmit>>, TError,{id: number}, TContext> => {

const mutationKey = ['programsControllerSubmit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof programsControllerSubmit>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  programsControllerSubmit(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ProgramsControllerSubmitMutationResult = NonNullable<Awaited<ReturnType<typeof programsControllerSubmit>>>

    export type ProgramsControllerSubmitMutationError = void

    export const useProgramsControllerSubmit = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programsControllerSubmit>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof programsControllerSubmit>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getProgramsControllerSubmitMutationOptions(options), queryClient);
    }
    export const programsControllerApprove = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<ProgramDetailDto>(
      {url: `/programs/${id}/approve`, method: 'POST', signal
    },
      options);
    }




export const getProgramsControllerApproveMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programsControllerApprove>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof programsControllerApprove>>, TError,{id: number}, TContext> => {

const mutationKey = ['programsControllerApprove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof programsControllerApprove>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  programsControllerApprove(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ProgramsControllerApproveMutationResult = NonNullable<Awaited<ReturnType<typeof programsControllerApprove>>>

    export type ProgramsControllerApproveMutationError = void

    export const useProgramsControllerApprove = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programsControllerApprove>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof programsControllerApprove>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getProgramsControllerApproveMutationOptions(options), queryClient);
    }
    export const programsControllerConfirm = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<ProgramDetailDto>(
      {url: `/programs/${id}/confirm`, method: 'POST', signal
    },
      options);
    }




export const getProgramsControllerConfirmMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programsControllerConfirm>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof programsControllerConfirm>>, TError,{id: number}, TContext> => {

const mutationKey = ['programsControllerConfirm'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof programsControllerConfirm>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  programsControllerConfirm(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ProgramsControllerConfirmMutationResult = NonNullable<Awaited<ReturnType<typeof programsControllerConfirm>>>

    export type ProgramsControllerConfirmMutationError = void

    export const useProgramsControllerConfirm = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programsControllerConfirm>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof programsControllerConfirm>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getProgramsControllerConfirmMutationOptions(options), queryClient);
    }
    export const programsControllerSendToDtm = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<ProgramDetailDto>(
      {url: `/programs/${id}/send`, method: 'POST', signal
    },
      options);
    }




export const getProgramsControllerSendToDtmMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programsControllerSendToDtm>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof programsControllerSendToDtm>>, TError,{id: number}, TContext> => {

const mutationKey = ['programsControllerSendToDtm'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof programsControllerSendToDtm>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  programsControllerSendToDtm(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ProgramsControllerSendToDtmMutationResult = NonNullable<Awaited<ReturnType<typeof programsControllerSendToDtm>>>

    export type ProgramsControllerSendToDtmMutationError = void

    export const useProgramsControllerSendToDtm = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programsControllerSendToDtm>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof programsControllerSendToDtm>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getProgramsControllerSendToDtmMutationOptions(options), queryClient);
    }
    export const programsControllerCancel = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<ProgramDetailDto>(
      {url: `/programs/${id}/cancel`, method: 'POST', signal
    },
      options);
    }




export const getProgramsControllerCancelMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programsControllerCancel>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof programsControllerCancel>>, TError,{id: number}, TContext> => {

const mutationKey = ['programsControllerCancel'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof programsControllerCancel>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  programsControllerCancel(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ProgramsControllerCancelMutationResult = NonNullable<Awaited<ReturnType<typeof programsControllerCancel>>>

    export type ProgramsControllerCancelMutationError = void

    export const useProgramsControllerCancel = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof programsControllerCancel>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof programsControllerCancel>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getProgramsControllerCancelMutationOptions(options), queryClient);
    }
