/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ONCF ECommand API
 * ONCF freight order management
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ReportsControllerGetOrdersParams
} from './generated.schemas';

import { customFetch } from '../axios';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary Summarize accessible orders by status, customer, product, and month
 */
export const reportsControllerGetOrders = (
    params?: ReportsControllerGetOrdersParams,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<void>(
      {url: `/reports/orders`, method: 'GET',
        params, signal
    },
      options);
    }




export const getReportsControllerGetOrdersQueryKey = (params?: ReportsControllerGetOrdersParams,) => {
    return [
    `/reports/orders`, ...(params ? [params] : [])
    ] as const;
    }


export const getReportsControllerGetOrdersQueryOptions = <TData = Awaited<ReturnType<typeof reportsControllerGetOrders>>, TError = unknown>(params?: ReportsControllerGetOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetOrders>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReportsControllerGetOrdersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof reportsControllerGetOrders>>> = ({ signal }) => reportsControllerGetOrders(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetOrders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReportsControllerGetOrdersQueryResult = NonNullable<Awaited<ReturnType<typeof reportsControllerGetOrders>>>
export type ReportsControllerGetOrdersQueryError = unknown


export function useReportsControllerGetOrders<TData = Awaited<ReturnType<typeof reportsControllerGetOrders>>, TError = unknown>(
 params: undefined |  ReportsControllerGetOrdersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetOrders>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsControllerGetOrders>>,
          TError,
          Awaited<ReturnType<typeof reportsControllerGetOrders>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportsControllerGetOrders<TData = Awaited<ReturnType<typeof reportsControllerGetOrders>>, TError = unknown>(
 params?: ReportsControllerGetOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetOrders>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsControllerGetOrders>>,
          TError,
          Awaited<ReturnType<typeof reportsControllerGetOrders>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportsControllerGetOrders<TData = Awaited<ReturnType<typeof reportsControllerGetOrders>>, TError = unknown>(
 params?: ReportsControllerGetOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetOrders>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Summarize accessible orders by status, customer, product, and month
 */

export function useReportsControllerGetOrders<TData = Awaited<ReturnType<typeof reportsControllerGetOrders>>, TError = unknown>(
 params?: ReportsControllerGetOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerGetOrders>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReportsControllerGetOrdersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






