/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ONCF Ecommand API
 * ONCF freight order management
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  TrackOrderDto,
  TrackTrainDto,
  TrackWagonDto,
  TrainPositionDto,
  UpdateTrainPositionDto,
  UpdateWagonPositionDto,
  WagonPositionDto
} from './generated.schemas';

import { customFetch } from '../axios';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const trackingControllerTrackWagon = (
    wagonNumber: string,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<TrackWagonDto>(
      {url: `/tracking/wagon/${wagonNumber}`, method: 'GET', signal
    },
      options);
    }




export const getTrackingControllerTrackWagonQueryKey = (wagonNumber: string,) => {
    return [
    `/tracking/wagon/${wagonNumber}`
    ] as const;
    }


export const getTrackingControllerTrackWagonQueryOptions = <TData = Awaited<ReturnType<typeof trackingControllerTrackWagon>>, TError = void>(wagonNumber: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackingControllerTrackWagon>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTrackingControllerTrackWagonQueryKey(wagonNumber);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof trackingControllerTrackWagon>>> = ({ signal }) => trackingControllerTrackWagon(wagonNumber, requestOptions, signal);





   return  { queryKey, queryFn, enabled: wagonNumber !== null && wagonNumber !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof trackingControllerTrackWagon>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TrackingControllerTrackWagonQueryResult = NonNullable<Awaited<ReturnType<typeof trackingControllerTrackWagon>>>
export type TrackingControllerTrackWagonQueryError = void


export function useTrackingControllerTrackWagon<TData = Awaited<ReturnType<typeof trackingControllerTrackWagon>>, TError = void>(
 wagonNumber: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackingControllerTrackWagon>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof trackingControllerTrackWagon>>,
          TError,
          Awaited<ReturnType<typeof trackingControllerTrackWagon>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTrackingControllerTrackWagon<TData = Awaited<ReturnType<typeof trackingControllerTrackWagon>>, TError = void>(
 wagonNumber: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackingControllerTrackWagon>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof trackingControllerTrackWagon>>,
          TError,
          Awaited<ReturnType<typeof trackingControllerTrackWagon>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTrackingControllerTrackWagon<TData = Awaited<ReturnType<typeof trackingControllerTrackWagon>>, TError = void>(
 wagonNumber: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackingControllerTrackWagon>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTrackingControllerTrackWagon<TData = Awaited<ReturnType<typeof trackingControllerTrackWagon>>, TError = void>(
 wagonNumber: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackingControllerTrackWagon>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTrackingControllerTrackWagonQueryOptions(wagonNumber,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const trackingControllerTrackTrain = (
    trainNumber: string,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<TrackTrainDto>(
      {url: `/tracking/train/${trainNumber}`, method: 'GET', signal
    },
      options);
    }




export const getTrackingControllerTrackTrainQueryKey = (trainNumber: string,) => {
    return [
    `/tracking/train/${trainNumber}`
    ] as const;
    }


export const getTrackingControllerTrackTrainQueryOptions = <TData = Awaited<ReturnType<typeof trackingControllerTrackTrain>>, TError = void>(trainNumber: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackingControllerTrackTrain>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTrackingControllerTrackTrainQueryKey(trainNumber);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof trackingControllerTrackTrain>>> = ({ signal }) => trackingControllerTrackTrain(trainNumber, requestOptions, signal);





   return  { queryKey, queryFn, enabled: trainNumber !== null && trainNumber !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof trackingControllerTrackTrain>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TrackingControllerTrackTrainQueryResult = NonNullable<Awaited<ReturnType<typeof trackingControllerTrackTrain>>>
export type TrackingControllerTrackTrainQueryError = void


export function useTrackingControllerTrackTrain<TData = Awaited<ReturnType<typeof trackingControllerTrackTrain>>, TError = void>(
 trainNumber: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackingControllerTrackTrain>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof trackingControllerTrackTrain>>,
          TError,
          Awaited<ReturnType<typeof trackingControllerTrackTrain>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTrackingControllerTrackTrain<TData = Awaited<ReturnType<typeof trackingControllerTrackTrain>>, TError = void>(
 trainNumber: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackingControllerTrackTrain>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof trackingControllerTrackTrain>>,
          TError,
          Awaited<ReturnType<typeof trackingControllerTrackTrain>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTrackingControllerTrackTrain<TData = Awaited<ReturnType<typeof trackingControllerTrackTrain>>, TError = void>(
 trainNumber: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackingControllerTrackTrain>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTrackingControllerTrackTrain<TData = Awaited<ReturnType<typeof trackingControllerTrackTrain>>, TError = void>(
 trainNumber: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackingControllerTrackTrain>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTrackingControllerTrackTrainQueryOptions(trainNumber,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const trackingControllerTrackOrder = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<TrackOrderDto[]>(
      {url: `/tracking/order/${id}`, method: 'GET', signal
    },
      options);
    }




export const getTrackingControllerTrackOrderQueryKey = (id: number,) => {
    return [
    `/tracking/order/${id}`
    ] as const;
    }


export const getTrackingControllerTrackOrderQueryOptions = <TData = Awaited<ReturnType<typeof trackingControllerTrackOrder>>, TError = void>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackingControllerTrackOrder>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTrackingControllerTrackOrderQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof trackingControllerTrackOrder>>> = ({ signal }) => trackingControllerTrackOrder(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof trackingControllerTrackOrder>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TrackingControllerTrackOrderQueryResult = NonNullable<Awaited<ReturnType<typeof trackingControllerTrackOrder>>>
export type TrackingControllerTrackOrderQueryError = void


export function useTrackingControllerTrackOrder<TData = Awaited<ReturnType<typeof trackingControllerTrackOrder>>, TError = void>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackingControllerTrackOrder>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof trackingControllerTrackOrder>>,
          TError,
          Awaited<ReturnType<typeof trackingControllerTrackOrder>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTrackingControllerTrackOrder<TData = Awaited<ReturnType<typeof trackingControllerTrackOrder>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackingControllerTrackOrder>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof trackingControllerTrackOrder>>,
          TError,
          Awaited<ReturnType<typeof trackingControllerTrackOrder>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTrackingControllerTrackOrder<TData = Awaited<ReturnType<typeof trackingControllerTrackOrder>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackingControllerTrackOrder>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTrackingControllerTrackOrder<TData = Awaited<ReturnType<typeof trackingControllerTrackOrder>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackingControllerTrackOrder>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTrackingControllerTrackOrderQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const trackingControllerUpdateWagonPosition = (
    id: number,
    updateWagonPositionDto: UpdateWagonPositionDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<WagonPositionDto | void>(
      {url: `/tracking/wagon/${id}/position`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateWagonPositionDto, signal
    },
      options);
    }




export const getTrackingControllerUpdateWagonPositionMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof trackingControllerUpdateWagonPosition>>, TError,{id: number;data: UpdateWagonPositionDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof trackingControllerUpdateWagonPosition>>, TError,{id: number;data: UpdateWagonPositionDto}, TContext> => {

const mutationKey = ['trackingControllerUpdateWagonPosition'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof trackingControllerUpdateWagonPosition>>, {id: number;data: UpdateWagonPositionDto}> = (props) => {
          const {id,data} = props ?? {};

          return  trackingControllerUpdateWagonPosition(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TrackingControllerUpdateWagonPositionMutationResult = NonNullable<Awaited<ReturnType<typeof trackingControllerUpdateWagonPosition>>>
    export type TrackingControllerUpdateWagonPositionMutationBody = UpdateWagonPositionDto
    export type TrackingControllerUpdateWagonPositionMutationError = void

    export const useTrackingControllerUpdateWagonPosition = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof trackingControllerUpdateWagonPosition>>, TError,{id: number;data: UpdateWagonPositionDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof trackingControllerUpdateWagonPosition>>,
        TError,
        {id: number;data: UpdateWagonPositionDto},
        TContext
      > => {
      return useMutation(getTrackingControllerUpdateWagonPositionMutationOptions(options), queryClient);
    }
    export const trackingControllerUpdateTrainPosition = (
    id: number,
    updateTrainPositionDto: UpdateTrainPositionDto,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {


      return customFetch<TrainPositionDto | void>(
      {url: `/tracking/train/${id}/position`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateTrainPositionDto, signal
    },
      options);
    }




export const getTrackingControllerUpdateTrainPositionMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof trackingControllerUpdateTrainPosition>>, TError,{id: number;data: UpdateTrainPositionDto}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof trackingControllerUpdateTrainPosition>>, TError,{id: number;data: UpdateTrainPositionDto}, TContext> => {

const mutationKey = ['trackingControllerUpdateTrainPosition'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof trackingControllerUpdateTrainPosition>>, {id: number;data: UpdateTrainPositionDto}> = (props) => {
          const {id,data} = props ?? {};

          return  trackingControllerUpdateTrainPosition(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TrackingControllerUpdateTrainPositionMutationResult = NonNullable<Awaited<ReturnType<typeof trackingControllerUpdateTrainPosition>>>
    export type TrackingControllerUpdateTrainPositionMutationBody = UpdateTrainPositionDto
    export type TrackingControllerUpdateTrainPositionMutationError = void

    export const useTrackingControllerUpdateTrainPosition = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof trackingControllerUpdateTrainPosition>>, TError,{id: number;data: UpdateTrainPositionDto}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof trackingControllerUpdateTrainPosition>>,
        TError,
        {id: number;data: UpdateTrainPositionDto},
        TContext
      > => {
      return useMutation(getTrackingControllerUpdateTrainPositionMutationOptions(options), queryClient);
    }
