import { Assert, Equals } from "src/common/utils/type-assertions";
import { OrderDetail } from "../orders.types";

type _Assertion = Assert<Equals<OrderDetailDto, OrderDetail>>;

export class OrderDetailDto implements OrderDetail {
	id: number;
	goodsId: number;
	customerId: number;
	createdByUserId: number;
	statusId: number;
	supervisor: string | null;
	orderNumber: string | null;
	movementTypeId: number | null;
	parentOrderId: number | null;
	quantityDemanded: string;
	quantityAchieved: string | null;
	unitId: number;
	departureStationId: number | null;
	debtorCustomerId: number | null;
	pickupLocationTypeId: number | null;
	dispatchTypeId: number | null;
	destinationCustomerId: number | null;
	arrivalStationId: number | null;
	deliveryLocationTypeId: number | null;
	pickupPortId: number | null;
	pickupBerthId: number | null;
	pickupSidingId: number | null;
	deliveryPortId: number | null;
	deliveryBerthId: number | null;
	deliverySidingId: number | null;
	remarks: string | null;
	orderDate: string;
	startDate: string | null;
	endDate: string | null;
	createdAt: string;
	updatedAt: string;
	orderStatus: { id: number; name: string } | null;
	forecastPrograms: {
		id: number;
		createdByUserId: number;
		statusId: number;
		createdAt: string;
		updatedAt: string;
		orderId: number;
		programNumber: string;
		plannedDate: string;
		quantityPlanned: string;
		quantityRealized: string | null;
		deviationReason: string | null;
		realizedAt: string | null;
		realizedByUserId: number | null;
		sentToDtmAt: string | null;
		dtmStatus: string | null;
	}[];
	orderExecutions: {
		id: number;
		createdAt: string;
		orderId: number;
		comment: string | null;
		completionRate: string | null;
		executionDate: string;
		quantityExecuted: string;
		executedByUserId: number;
	}[];
	orderFiles: {
		description: string | null;
		orderId: number;
		fileId: number;
		fileName: string;
		fileType: string;
		fileSize: number;
		filePath: string;
		mimeType: string | null;
		uploadedByUserId: number;
		uploadedAt: string;
	}[];
	claims: {
		id: number;
		customerId: number;
		createdByUserId: number;
		statusId: number;
		createdAt: string;
		updatedAt: string;
		typeId: number;
		description: string;
		orderId: number | null;
		operationId: number | null;
		priority: string | null;
		resolution: string | null;
		closedByUserId: number | null;
		closedAt: string | null;
	}[];
	unit: { name: string } | null;
	customer: { id: number; companyName: string } | null;
	orderStatusHistories: {
		id: number;
		statusId: number;
		orderId: number;
		changedById: number;
		changedAt: string;
		comment: string | null;
		rejectionReasonId: number | null;
	}[];
	good: { id: number; name: string } | null;
	createdByUser: { id: number; lastName: string; firstName: string } | null;
}
