export enum ClaimType {
	DELIVERY_DELAY = "DELIVERY_DELAY",
	DAMAGED_GOODS = "DAMAGED_GOODS",
	INCORRECT_QUANTITY = "INCORRECT_QUANTITY",
	NON_COMPLIANT_QUALITY = "NON_COMPLIANT_QUALITY",
	BILLING_ISSUE = "BILLING_ISSUE",
	DOCUMENTATION_PROBLEM = "DOCUMENTATION_PROBLEM",
	CUSTOMER_SERVICE = "CUSTOMER_SERVICE",
	OTHER = "OTHER",
}

export enum ClaimStatus {
	NEW = "NEW",
	IN_PROGRESS = "IN_PROGRESS",
	AWAITING_INFO = "AWAITING_INFO",
	IN_TREATMENT = "IN_TREATMENT",
	RESOLVED = "RESOLVED",
	CLOSED = "CLOSED",
	REJECTED = "REJECTED",
	SENT_TO_DTM = "SENT_TO_DTM",
}

export enum ClaimPriority {
	LOW = "low",
	MEDIUM = "medium",
	HIGH = "high",
	URGENT = "urgent",
}

export enum RejectionReason {
	INSUFFICIENT_CAPACITY = "Insufficient capacity",
	INCOMPLETE_DOCUMENTATION = "Incomplete documentation",
	INCORRECT_INFORMATION = "Incorrect information",
	UNAUTHORIZED_CUSTOMER = "Unauthorized customer",
	UNAUTHORIZED_GOODS = "Unauthorized goods",
	PAYMENT_ISSUE = "Payment issue",
	OPERATIONAL_CONSTRAINTS = "Operational constraints",
	OTHER = "Other",
}
