export enum Role {
	ADMIN = "ADMIN",
	AGENT_COMMERCIAL = "AGENT_COMMERCIAL",
	CLIENT_REPRESENTATIVE = "CLIENT_REPRESENTATIVE",
}

export enum Permission {
	USERS_CREATE = "users:create",
	USERS_READ = "users:read",
	USERS_UPDATE = "users:update",
	USERS_DELETE = "users:delete",
	USERS_MANAGE = "users:manage",
	USERS_MANAGE_OTHER = "users:manage:other",

	ORDERS_CREATE = "orders:create",
	ORDERS_READ = "orders:read",
	ORDERS_UPDATE = "orders:update",
	ORDERS_DELETE = "orders:delete",
	ORDERS_MANAGE = "orders:manage",
	ORDERS_MANAGE_OTHER = "orders:manage:other",
	ORDERS_MANAGE_OWNERSHIP = "orders:manage:ownership",
	ORDERS_MANAGE_STATUS = "orders:manage:status",
	ORDERS_ACTION = "orders:action",
	ORDERS_ACTION_SUBMIT = "orders:action:submit",
	ORDERS_ACTION_APPROVE = "orders:action:approve",
	ORDERS_ACTION_REJECT = "orders:action:reject",
	ORDERS_ACTION_CANCEL = "orders:action:cancel",
	ORDERS_ACTION_SEND_TO_DTM = "orders:action:send-to-dtm",

	CUSTOMERS_CREATE = "customers:create",
	CUSTOMERS_READ = "customers:read",
	CUSTOMERS_UPDATE = "customers:update",
	CUSTOMERS_DELETE = "customers:delete",
	CUSTOMERS_MANAGE = "customers:manage",
	CUSTOMERS_MANAGE_OTHER = "customers:manage:other",

	PROGRAMS_CREATE = "programs:create",
	PROGRAMS_READ = "programs:read",
	PROGRAMS_UPDATE = "programs:update",
	PROGRAMS_DELETE = "programs:delete",
	PROGRAMS_MANAGE = "programs:manage",
	PROGRAMS_MANAGE_OTHER = "programs:manage:other",
	PROGRAMS_MANAGE_OWNERSHIP = "programs:manage:ownership",
	PROGRAMS_MANAGE_STATUS = "programs:manage:status",
	PROGRAMS_ACTION = "programs:action",
	PROGRAMS_ACTION_SUBMIT = "programs:action:submit",
	PROGRAMS_ACTION_APPROVE = "programs:action:approve",
	PROGRAMS_ACTION_CONFIRM = "programs:action:confirm",
	PROGRAMS_ACTION_CANCEL = "programs:action:cancel",
	PROGRAMS_ACTION_SEND = "programs:action:send",
	PROGRAMS_ACTION_EXECUTE = "programs:action:execute",

	CLAIMS_CREATE = "claims:create",
	CLAIMS_READ = "claims:read",
	CLAIMS_UPDATE = "claims:update",
	CLAIMS_DELETE = "claims:delete",
	CLAIMS_MANAGE = "claims:manage",
	CLAIMS_MANAGE_OTHER = "claims:manage:other",
	CLAIMS_MANAGE_STATUS = "claims:manage:status",
	CLAIMS_ACTION = "claims:action",
	CLAIMS_ACTION_START_PROGRESS = "claims:action:start-progress",
	CLAIMS_ACTION_AWAIT_INFO = "claims:action:await-info",
	CLAIMS_ACTION_START_TREATMENT = "claims:action:start-treatment",
	CLAIMS_ACTION_RESOLVE = "claims:action:resolve",
	CLAIMS_ACTION_REJECT = "claims:action:reject",
	CLAIMS_ACTION_SEND_TO_DTM = "claims:action:send-to-dtm",
	CLAIMS_ACTION_CLOSE = "claims:action:close",

	CATALOG_READ = "catalog:read",
	CATALOG_MANAGE = "catalog:manage",
	CATALOG_MANAGE_UNITS = "catalog:manage:units",
	CATALOG_MANAGE_GOODS = "catalog:manage:goods",
	CATALOG_MANAGE_GOODS_TYPES = "catalog:manage:goods-types",
	CATALOG_MANAGE_ACCESSORY_OPERATIONS = "catalog:manage:accessory-operations",
	CATALOG_MANAGE_REJECTION_REASONS = "catalog:manage:rejection-reasons",

	TRACKING_READ = "tracking:read",
	TRACKING_UPDATE = "tracking:update",
	TRACKING_MANAGE = "tracking:manage",

	REPORTS_READ = "reports:read",
	REPORTS_ACTION = "reports:action",
	REPORTS_ACTION_EXPORT = "reports:action:export",

	ROLES_MANAGE = "roles:manage",
	PERMISSIONS_MANAGE = "permissions:manage",

	LOGS_READ = "logs:read",

	PROFILE_UPDATE = "profile:update",

	ARCHIVAL_READ = "archival:read",
	ARCHIVAL_MANAGE = "archival:manage",
}
